// File used to initialize the database.

//https://www.linode.com/docs/guides/getting-started-with-nodejs-sqlite/

const constants = require('../../common/naming_constants.js');

var sqlite3 = require('sqlite3');
var db;

createDB();

function createDB() {
    // Connect to or create the database
    db = new sqlite3.Database('./unite_information.db', sqlite3.OPEN_READWRITE, (err) => {
        if (err && err.code == "SQLITE_CANTOPEN") {
            createDatabase();
            return;
            } else if (err) {
                console.log("Getting error " + err);
                process.exit(1);
        }
        clearDatabase(db, () => {
            createTables(db);
        });
    });

    // Function to create the database file itself if it doesn't exist
    function createDatabase() {
        var newdb = new sqlite3.Database('unite_information.db', (err) => {
            if (err) {
                console.log("Getting error " + err);
                process.exit(1);
            }
            createTables(newdb);
        });
    }

    // Function to create the tables themselves
    function createTables(newdb) {
        newdb.exec(`
        create table playable_characters (
            pokemon_id integer primary key AUTOINCREMENT not null,
            pokemon_name text not null,
            pokemon_class text not null
        );
        create table pokemon_attributes (
            pokemon_id int not null,
            attribute text not null,
            FOREIGN KEY (pokemon_id) REFERENCES playable_characters (pokemon_id)
        );
        create table comps (
            comp_id integer primary key AUTOINCREMENT not null,
            pokemon_1 int not null,
            pokemon_2 int not null,
            pokemon_3 int not null,
            pokemon_4 int not null,
            pokemon_5 int not null,
            FOREIGN KEY (pokemon_1) REFERENCES playable_characters(pokemon_id),
            FOREIGN KEY (pokemon_2) REFERENCES playable_characters(pokemon_id),
            FOREIGN KEY (pokemon_3) REFERENCES playable_characters(pokemon_id),
            FOREIGN KEY (pokemon_4) REFERENCES playable_characters(pokemon_id),
            FOREIGN KEY (pokemon_5) REFERENCES playable_characters(pokemon_id)
        );
        `, (err) => {
            if (err) {
                console.log("Error creating tables: " + err.message);
                process.exit(1);
            } else {
                console.log("Successfully created tables.");
                populateCharacters(newdb);
                populateAttributes(newdb);
                runQueries(newdb);
            }
        });
    }

    function populateCharacters(db) {
        db.exec(`
        insert into playable_characters (pokemon_name, pokemon_class) 
        values 
            ('${constants.CINDERACE_NAME}', '${constants.ATTACKER}'), 
            ('${constants.GARCHOMP_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.GENGAR_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.CRAMORANT_NAME}', '${constants.ATTACKER}'),
            ('${constants.ALOLANNINETALES_NAME}', '${constants.ATTACKER}'),
            ('${constants.WIGGLYTUFF_NAME}', '${constants.SUPPORTER}'),
            ('${constants.MACHAMP_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.ABSOL_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.SLOWBRO_NAME}', '${constants.DEFENDER}'),
            ('${constants.MRMIME_NAME}', '${constants.SUPPORTER}'),
            ('${constants.VENUSAUR_NAME}', '${constants.ATTACKER}'),
            ('${constants.LUCARIO_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.TALONFLAME_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.ELDEGOSS_NAME}', '${constants.SUPPORTER}'),
            ('${constants.GRENINJA_NAME}', '${constants.ATTACKER}'),
            ('${constants.CRUSTLE_NAME}', '${constants.DEFENDER}'),
            ('${constants.SNORLAX_NAME}', '${constants.DEFENDER}'),
            ('${constants.CHARIZARD_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.PIKACHU_NAME}', '${constants.ATTACKER}'),
            ('${constants.ZERAORA_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.GARDEVOIR_NAME}', '${constants.ATTACKER}'),
            ('${constants.BLISSEY_NAME}', '${constants.SUPPORTER}'),
            ('${constants.BLASTOISE_NAME}', '${constants.DEFENDER}'),
            ('${constants.MAMOSWINE_NAME}', '${constants.DEFENDER}'),
            ('${constants.SYLVEON_NAME}', '${constants.ATTACKER}'),
            ('${constants.GREEDENT_NAME}', '${constants.DEFENDER}'),
            ('${constants.DECIDUEYE_NAME}', '${constants.ATTACKER}'),
            ('${constants.TSAREENA_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.DRAGONITE_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.TREVENANT_NAME}', '${constants.DEFENDER}'),
            ('${constants.AEGISLASH_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.HOOPA_NAME}', '${constants.SUPPORTER}'),
            ('${constants.DURALUDON_NAME}', '${constants.ATTACKER}'),
            ('${constants.AZUMARILL_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.ESPEON_NAME}', '${constants.ATTACKER}'),
            ('${constants.DELPHOX_NAME}', '${constants.ATTACKER}'),
            ('${constants.GLACEON_NAME}', '${constants.ATTACKER}'),
            ('${constants.BUZZWOLE_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.TYRANITAR_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.MEW_NAME}', '${constants.ATTACKER}'),
            ('${constants.DODRIO_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.SCIZOR_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.SCYTHER_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.CLEFABLE_NAME}', '${constants.SUPPORTER}'),
            ('${constants.ZOROARK_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.SABLEYE_NAME}', '${constants.SUPPORTER}'),
            ('${constants.URSHIFUSS_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.URSHIFURS_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.DRAGAPULT_NAME}', '${constants.ATTACKER}'),
            ('${constants.COMFEY_NAME}', '${constants.SUPPORTER}'),
            ('${constants.ZACIAN_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.GOODRA_NAME}', '${constants.DEFENDER}'),
            ('${constants.LAPRAS_NAME}', '${constants.ATTACKER}'),
            ('${constants.CHANDELURE_NAME}', '${constants.ATTACKER}'),
            ('${constants.UMBREON_NAME}', '${constants.DEFENDER}'),
            ('${constants.LEAFEON_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.INTELEON_NAME}', '${constants.ATTACKER}'),
            ('${constants.MEWTWOY_NAME}', '${constants.ATTACKER}'),
            ('${constants.MEWTWOX_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.BLAZIKEN_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.MIMIKYU_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.MEOWSCARADA_NAME}', '${constants.SPEEDSTER}'),
            ('${constants.METAGROSS_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.GYARADOS_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.MIRAIDON_NAME}', '${constants.ATTACKER}'),
            ('${constants.FALINKS_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.CERULEDGE_NAME}', '${constants.ALL_ROUNDER}'),
            ('${constants.HOOH_NAME}', '${constants.DEFENDER}')
        `, (err) => {
            if (err) {
                console.log("Error inserting into playable_characters: " + err.message);
                process.exit(1);
            } else {
                console.log("Successfully inserted characters.");
            }
        });
    }

    // These are attributes inherent to the character themself. AKA These attributes
    // come from their STATS, PASSIVES, AUTO ATTACKS, ULTS
    function populateCharacterAttributes(db) {
        db.exec(`
        insert into pokemon_attributes (pokemon_id, attribute)
            values
                (1, '${constants.CAN_JUNGLE /* Cinderace */}'),
                (1, '${constants.STRONG_LATE}'),
                (1, '${constants.MID_RANGE}'),
                (1, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (1, '${constants.ADC}'),
                (1, '${constants.FAST_RIP}'),.
                (2, '${constants.CAN_LANE /* Garchomp */}'),
                (2, '${constants.CAN_JUNGLE}'),
                (2, '${constants.STRONG_EARLY}'),
                (2, '${constants.STRONG_LATE}'),
                (2, '${constants.MELEE}'),
                (2, '${constants.BRUISER}'),
                (2, '${constants.GOOD_SUSTAIN}'),
                (2, '${constants.GOOD_1V1}'),
                (2, '${constants.FAST_RIP}'),
                (3, '${constants.CAN_JUNGLE /* Gengar */}'),
                (3, '${constants.STRONG_MIDDLE}'),
                (3, '${constants.HIGH_MOBILITY}'),
                (3, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (3, '${constants.ASSASSAIN}'),
                (4, '${constants.CAN_LANE /* Cramorant */}'),
                (4, '${constants.CAN_JUNGLE}'),
                (4, '${constants.CONTROL_MAGE}'),
                (4, '${constants.TEAMFIGHTER}'),
                (5, '${constants.CONTROL_MAGE /* Alolan-Ninetales */}'),
                (5, '${constants.STRONG_EARLY}'),
                (5, '${constants.CAN_LANE}'),
                (5, '${constants.MID_RANGE}'),
                (5, '${constants.SINGLE_CC}'),
                (6, '${constants.CAN_LANE /* Wigglytuff */}'),
                (6, '${constants.MELEE}'),
                (6, '${constants.STRONG_EARLY}'),
                (6, '${constants.SINGLE_CC}'),
                (6, '${constants.GROUP_CC}'),
                (6, '${constants.USES_SHIELDS}'),
                (6, '${constants.GIVES_UNSTOPPABLE}'),
                (6, '${constants.CLERIC}'),
                (6, '${constants.TANK}'),
                (7, '${constants.BRUISER /* Machamp */}'),
                (7, '${constants.CAN_LANE}'),
                (7, '${constants.MELEE}'),
                (7, '${constants.GOOD_1V1}'),
                (7, '${constants.GOOD_SUSTAIN}'),
                (7, '${constants.STRONG_MIDDLE}'),
                (8, '${constants.CAN_JUNGLE /* Absol */}'),
                (8, '${constants.STRONG_EARLY}'),
                (8, '${constants.STRONG_MIDDLE}'),
                (8, '${constants.MELEE}'),
                (8, '${constants.ASSASSAIN}'),
                (8, '${constants.FAST_RIP}'),
                (9, '${constants.CAN_LANE /* Slowbro */}'),
                (9, '${constants.LOW_RANGE}'),
                (9, '${constants.TANK}'),
                (9, '${constants.GOOD_SUSTAIN}'),
                (9, '${constants.SINGLE_CC}'),
                (9, '${constants.LOCKDOWN}'),
                (10, '${constants.CAN_LANE /* Mr-Mime */}'),
                (10, '${constants.MELEE}'),
                (10, '${constants.ENGAGE}'),
                (10, '${constants.SINGLE_CC}'),
                (10, '${constants.GROUP_CC}'),
                (11, '${constants.CAN_JUNGLE /* Venusaur */}'),
                (11, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (11, '${constants.STRONG_MIDDLE}'),
                (11, '${constants.STRONG_LATE}'),
                (11, '${constants.MID_RANGE}'),
                (11, '${constants.SNOWBALL}'),
                (11, '${constants.FAST_RIP}'),
                (11, '${constants.TEAMFIGHTER}'),
                (12, '${constants.CAN_LANE /* Lucario */}'),
                (12, '${constants.STRONG_EARLY}'),
                (12, '${constants.STRONG_MIDDLE}'),
                (12, '${constants.MELEE}'),
                (12, '${constants.BRUISER}'),
                (13, '${constants.CAN_JUNGLE /* Talonflame */}'),
                (13, '${constants.STRONG_MIDDLE}'),
                (13, '${constants.MELEE}'),
                (13, '${constants.GOOD_SCORING}'),
                (13, '${constants.ASSASSAIN}'),
                (13, '${constants.GOOD_1V1}'),
                (13, '${constants.DISENGAGE}'),
                (14, '${constants.CAN_LANE /* Eldegoss */}'),
                (14, '${constants.STRONG_EARLY}'),
                (14, '${constants.MID_RANGE}'),
                (14, '${constants.SPLITS_JUNGLE}'),
                (14, '${constants.CLERIC}'),
                (14, '${constants.PEEL}'),
                (15, '${constants.CAN_JUNGLE /* Greninja */}'),
                (15, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (15, '${constants.STRONG_LATE}'),
                (15, '${constants.MID_RANGE}'),
                (15, '${constants.GOOD_1V1}'),
                (15, '${constants.FAST_RIP}'),
                (16, '${constants.CAN_LANE /* Crustle */}'),
                (16, '${constants.STRONG_MIDDLE}'),
                (16, '${constants.MELEE}'),
                (16, '${constants.TANK}'),
                (16, '${constants.USES_SHIELDS}'),
                (17, '${constants.CAN_LANE /* Snorlax */}'),
                (17, '${constants.STRONG_EARLY}'),
                (17, '${constants.MELEE}'),
                (17, '${constants.GROUP_CC}'),
                (18, '${constants.CAN_JUNGLE /* Charizard */}'),
                (18, '${constants.STRONG_LATE}'),
                (18, '${constants.LOW_RANGE}'),
                (18, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (18, '${constants.BRUISER}'),
                (19, '${constants.CAN_LANE /* Pikachu */}'),
                (19, '${constants.STRONG_EARLY}'),
                (19, '${constants.MID_RANGE}'),
                (19, '${constants.BURST_MAGE}'),
                (19, '${constants.TEAMFIGHTER}'),
                (20, '${constants.CAN_JUNGLE /* Zeraora */}'),
                (20, '${constants.STRONG_MIDDLE}'),
                (20, '${constants.MELEE}'),
                (20, '${constants.GOOD_SUSTAIN}'),
                (21, '${constants.CONTROL_MAGE /* Gardevoir */}'),
                (21, '${constants.CAN_JUNGLE}'),
                (21, '${constants.STRONG_LATE}'),
                (21, '${constants.MID_RANGE}'),
                (21, '${constants.GROUP_CC}'),
                (22, '${constants.HAS_UNSTOPPABLE /* Blissey */}'),
                (22, '${constants.STRONG_LATE}'),
                (22, '${constants.MELEE}'),
                (22, '${constants.BUFFS}'),
                (22, '${constants.USES_SHIELDS}'),
                (22, '${constants.CLERIC}'),
                (23, '${constants.STRONG_LATE /* Blastoise */}'),
                (23, '${constants.CAN_LANE}'),
                (23, '${constants.CAN_JUNGLE}'),
                (23, '${constants.MID_RANGE}'),
                (23, '${constants.TANK}'),
                (23, '${constants.GROUP_CC}'),
                (24, '${constants.STRONG_EARLY /* Mamoswine */}'),
                (24, '${constants.MELEE}'),
                (24, '${constants.SINGLE_CC}'),
                (24, '${constants.GROUP_CC}'),
                (24, '${constants.ENGAGE}'),
                (24, '${constants.TANK}'),
                (24, '${constants.LOCKDOWN}'),
                (25, '${constants.CAN_LANE /* Sylveon */}'),
                (25, '${constants.CAN_JUNGLE}'),
                (25, '${constants.STRONG_MIDDLE}'),
                (25, '${constants.MID_RANGE}'),
                (25, '${constants.FULL_SPLIT_JUNGLE}'),
                (25, '${constants.DRAIN_MAGE}'),
                (25, '${constants.GOOD_SUSTAIN}'),
                (26, '${constants.CAN_LANE /* Greedent */}'),
                (26, '${constants.MELEE}'),
                (26, '${constants.GOOD_SCORING}'),
                (26, '${constants.INVADES}'),
                (26, '${constants.TANK}'),
                (26, '${constants.GOOD_SUSTAIN}'),
                (26, '${constants.ENGAGE}'),
                (27, '${constants.CAN_LANE /* Decidueye */}'),
                (27, '${constants.CAN_JUNGLE}'),
                (27, '${constants.MID_RANGE}'),
                (27, '${constants.STRONG_LATE}'),
                (27, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (27, '${constants.ADC}'),
                (27, '${constants.TEAMFIGHTER}'),
                (27, '${constants.FAST_RIP}'),
                (28, '${constants.CAN_LANE /* Tsareena */}'),
                (28, '${constants.STRONG_LATE}'),
                (28, '${constants.MELEE}'),
                (28, '${constants.BRUISER}'),
                (28, '${constants.GOOD_SUSTAIN}'),
                (28, '${constants.SINGLE_CC}'),
                (29, '${constants.CAN_JUNGLE /* Dragonite */}'),
                (29, '${constants.LOW_RANGE}'),
                (29, '${constants.STRONG_LATE}'),
                (29, '${constants.GOOD_SCORING}'),
                (29, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (29, '${constants.BRUISER}'),
                (29, '${constants.ENGAGE}'),
                (29, '${constants.GOOD_SUSTAIN}'),
                (29, '${constants.FAST_RIP}'),
                (29, '${constants.GOOD_1V1}'),
                (30, '${constants.CAN_LANE /* Trevenant */}'),
                (30, '${constants.STRONG_EARLY}'),
                (30, '${constants.STRONG_MIDDLE}'),
                (30, '${constants.MELEE}'),
                (30, '${constants.TANK}'),
                (30, '${constants.GOOD_SUSTAIN}'),
                (30, '${constants.GROUP_CC}'),
                (31, '${constants.CAN_LANE /* Aegislash */}'),
                (31, '${constants.CAN_JUNGLE}'),
                (31, '${constants.STRONG_LATE}'),
                (31, '${constants.LOW_RANGE}'),
                (31, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (31, '${constants.GOOD_SUSTAIN}'),
                (31, '${constants.FAST_RIP}'),
                (32, '${constants.CAN_LANE /* Hoopa */}'),
                (32, '${constants.MID_RANGE}'),
                (32, '${constants.SPLITS_JUNGLE}'),
                (32, '${constants.CLERIC}'),
                (32, '${constants.SPACE_CONTROL}'),
                (32, '${constants.HIGH_MOBILITY}'),
                (33, '${constants.MID_RANGE /* Duraludon */}'),
                (33, '${constants.CAN_LANE}'),
                (33, '${constants.CAN_JUNGLE}'),
                (33, '${constants.STRONG_EARLY}'),
                (33, '${constants.ADC}'),
                (33, '${constants.HAS_UNSTOPPABLE}'),
                (33, '${constants.SPACE_CONTROL}'),
                (33, '${constants.FAST_RIP}'),
                (33, '${constants.TEAMFIGHTER}'),
                (34, '${constants.CAN_LANE /* Azumarill */}'),
                (34, '${constants.STRONG_EARLY}'),
                (34, '${constants.STRONG_MIDDLE}'),
                (34, '${constants.MELEE}'),
                (34, '${constants.ENGAGE}'),
                (34, '${constants.BRUISER}'),
                (34, '${constants.GOOD_SUSTAIN}'),
                (34, '${constants.GOOD_1V1}'),
                (34, '${constants.BACKLINE_ACCESS}'),
                (35, '${constants.CAN_LANE /* Espeon */}'),
                (35, '${constants.STRONG_EARLY}'),
                (35, '${constants.MID_RANGE}'),
                (35, '${constants.FULL_SPLIT_JUNGLE}'),
                (35, '${constants.BURST_MAGE}'),
                (35, '${constants.TEAMFIGHTER}'),
                (36, '${constants.CAN_JUNGLE /* Delphox */}'),
                (36, '${constants.STRONG_MIDDLE}'),
                (36, '${constants.MID_RANGE}'),
                (36, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (36, '${constants.FULL_SPLIT_JUNGLE}'),
                (36, '${constants.DEBUFFS}'),
                (36, '${constants.TEAMFIGHTER}'),
                (36, '${constants.SPACE_CONTROL}'),
                (37, '${constants.CAN_LANE /* Glaceon */}'),
                (37, '${constants.CAN_JUNGLE}'),
                (37, '${constants.STRONG_MIDDLE}'),
                (37, '${constants.MID_RANGE}'),
                (37, '${constants.FULL_SPLIT_JUNGLE}'),
                (37, '${constants.BURST_MAGE}'),
                (37, '${constants.DISENGAGE}'),
                (37, '${constants.FAST_RIP}'),
                (38, '${constants.CAN_LANE /* Buzzwole */}'),
                (38, '${constants.STRONG_EARLY}'),
                (38, '${constants.STRONG_MIDDLE}'),
                (38, '${constants.MELEE}'),
                (38, '${constants.BRUISER}'),
                (38, '${constants.ENGAGE}'),
                (38, '${constants.GOOD_SUSTAIN}'),
                (38, '${constants.GOOD_1V1}'),
                (39, '${constants.CAN_LANE /* Tyranitar */}'),
                (39, '${constants.CAN_JUNGLE}'),
                (39, '${constants.STRONG_LATE}'),
                (39, '${constants.MELEE}'),
                (39, '${constants.TRUE_DAMAGE}'),
                (39, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (39, '${constants.BRUISER}'),
                (39, '${constants.SOLO_CARRY}'),
                (39, '${constants.TEAMFIGHTER}'),
                (39, '${constants.GOOD_1V1}'),
                (40, '${constants.CAN_LANE /* Mew */}'),
                (40, '${constants.STRONG_EARLY}'),
                (40, '${constants.MID_RANGE}'),
                (40, '${constants.LONG_RANGE}'),
                (40, '${constants.MEDIUM_MOBILITY}'),
                (40, '${constants.HIGH_MOBILITY}'),
                (40, '${constants.CONTROL_MAGE}'),
                (40, '${constants.SELF_PEEL}'),
                (40, '${constants.ENGAGE}'),
                (40, '${constants.DISENGAGE}'),
                (40, '${constants.POKE}'),
                (40, '${constants.BUFFS}'),
                (40, '${constants.GROUP_CC}'),
                (40, '${constants.BURST_DAMAGE}'),
                (40, '${constants.GOOD_SECURE}'),
                (40, '${constants.TEAMFIGHTER}'),
                (41, '${constants.CAN_JUNGLE /* Dodrio */}'),
                (41, '${constants.CAN_LANE}'),
                (41, '${constants.STRONG_MIDDLE}'),
                (41, '${constants.MELEE}'),
                (41, '${constants.LOW_RANGE}'),
                (41, '${constants.HIGH_MOBILITY}'),
                (41, '${constants.GOOD_SCORING}'),
                (41, '${constants.BRUISER}'),
                (41, '${constants.ENGAGE}'),
                (41, '${constants.DISENGAGE}'),
                (41, '${constants.GOOD_SUSTAIN}'),
                (41, '${constants.TEAMFIGHTER}'),
                (41, '${constants.FINDS_PICKS}'),
                (41, '${constants.BACKLINE_ACCESS}'),
                (42, '${constants.CAN_LANE /* Scizor */}'),
                (42, '${constants.STRONG_MIDDLE}'),
                (42, '${constants.MELEE}'),
                (42, '${constants.BRUISER}'),
                (42, '${constants.ENGAGE}'),
                (42, '${constants.GOOD_1V1}'),
                (43, '${constants.CAN_JUNGLE /* Scyther */}'),
                (43, '${constants.MELEE}'),
                (43, '${constants.ASSASSAIN}'),
                (43, '${constants.ENGAGE}'),
                (43, '${constants.GOOD_1V1}'),
                (44, '${constants.USES_SHIELDS /* Clefable */}'),
                (44, '${constants.CAN_LANE}'),
                (44, '${constants.STRONG_LATE}'),
                (44, '${constants.MELEE}'),
                (44, '${constants.GROUP_HEALING}'),
                (44, '${constants.GOOD_SECURE}'),
                (44, '${constants.PEEL}'),
                (45, '${constants.DISENGAGE /* Zoroark */}'),
                (45, '${constants.CAN_JUNGLE}'),
                (45, '${constants.STRONG_EARLY}'),
                (45, '${constants.STRONG_MIDDLE}'),
                (45, '${constants.MELEE}'),
                (45, '${constants.ASSASSAIN}'),
                (45, '${constants.BURST_DAMAGE}'),
                (46, '${constants.CAN_LANE /* Sableye */}'),
                (46, '${constants.MELEE}'),
                (46, '${constants.GOOD_SCORING}'),
                (46, '${constants.INVADES}'),
                (46, '${constants.LOCKDOWN}'),
                (46, '${constants.DISENGAGE}'),
                (46, '${constants.ENGAGE}'),
                (46, '${constants.STRONG_EARLY}'),
                (46, '${constants.SINGLE_CC}'),
                (46, '${constants.GROUP_CC}'),
                (47, '${constants.CAN_JUNGLE /* Urshifu-SS */}'),
                (47, '${constants.STRONG_MIDDLE}'),
                (47, '${constants.MELEE}'),
                (47, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (47, '${constants.BRUISER}'),
                (47, '${constants.SINGLE_CC}'),
                (47, '${constants.USES_SHIELDS}'),
                (47, '${constants.TEAMFIGHTER}'),
                (48, '${constants.CAN_JUNGLE /* Urshifu-RS */}'),
                (48, '${constants.STRONG_MIDDLE}'),
                (48, '${constants.MELEE}'),
                (48, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (48, '${constants.BRUISER}'),
                (48, '${constants.GOOD_SUSTAIN}'),
                (48, '${constants.GOOD_1V1}'),
                (48, '${constants.FINDS_PICKS}'),
                (49, '${constants.CAN_JUNGLE /* Dragapult */}'),
                (49, '${constants.STRONG_LATE}'),
                (49, '${constants.MID_RANGE}'),
                (49, '${constants.SUSCEPTIBLE_TO_INVADES}'),
                (49, '${constants.ADC}'),
                (49, '${constants.POKE}'),
                (49, '${constants.SOLO_CARRY}'),
                (49, '${constants.BURST_DAMAGE}'),
                (49, '${constants.TEAMFIGHTER}'),
                (50, '${constants.CAN_LANE /* Comfey */}'),
                (50, '${constants.STRONG_MIDDLE}'),
                (50, '${constants.STRONG_LATE}'),
                (50, '${constants.LOW_RANGE}'),
                (50, '${constants.MEDIUM_MOBILITY}'),
                (50, '${constants.CLERIC}'),
                (50, '${constants.SINGLE_TARGET_HEALING}'),
                (51, '${constants.CAN_LANE /* Zacian */}'),
                (51, '${constants.STRONG_EARLY}'),
                (51, '${constants.STRONG_MIDDLE}'),
                (51, '${constants.MELEE}'),
                (51, '${constants.MEDIUM_MOBILITY}'),
                (51, '${constants.HAS_UNSTOPPABLE}'),
                (51, '${constants.BRUISER}'),
                (51, '${constants.FAST_RIP}'),
                (51, '${constants.GOOD_1V1}'),
                (52, '${constants.CAN_LANE /* Goodra */}'),
                (52, '${constants.LOW_RANGE}'),
                (52, '${constants.TANK}'),
                (52, '${constants.STRONG_EARLY}'),
                (52, '${constants.LOCKDOWN}'),
                (52, '${constants.GOOD_SUSTAIN}'),
                (53, '${constants.CAN_LANE /* Lapras */}'),
                (53, '${constants.STRONG_LATE}'),
                (53, '${constants.LOW_RANGE}'),
                (53, '${constants.TANK}'),
                (53, '${constants.HIGH_MOBILITY}'),
                (53, '${constants.ENGAGE}'),
                (53, '${constants.PEEL}'),
                (54, '${constants.CAN_JUNGLE /* Chandelure */}'),
                (54, '${constants.STRONG_LATE}'),
                (54, '${constants.MID_RANGE}'),
                (54, '${constants.CONTROL_MAGE}'),
                (54, '${constants.DISENGAGE}'),
                (54, '${constants.SOLO_CARRY}'),
                (54, '${constants.TEAMFIGHTER}'),
                (55, '${constants.CAN_LANE /* Umbreon */}'),
                (55, '${constants.STRONG_MIDDLE}'),
                (55, '${constants.STRONG_LATE}'),
                (55, '${constants.MELEE}'),
                (55, '${constants.TANK}'),
                (55, '${constants.GOOD_SUSTAIN}'),
                (55, '${constants.HAS_UNSTOPPABLE}'),
                (55, '${constants.GROUP_CC}'),
                (56, '${constants.CAN_LANE /* Leafeon */}'),
                (56, '${constants.CAN_JUNGLE}'),
                (56, '${constants.STRONG_EARLY}'),
                (56, '${constants.STRONG_MIDDLE}'),
                (56, '${constants.MELEE}'),
                (56, '${constants.HIGH_MOBILITY}'),
                (56, '${constants.FULL_SPLIT_JUNGLE}'),
                (56, '${constants.ASSASSAIN}'),
                (56, '${constants.ENGAGE}'),
                (56, '${constants.BURST_DAMAGE}'),
                (56, '${constants.GOOD_1V1}'),
                (57, '${constants.CAN_LANE /* Inteleon */}'),
                (57, '${constants.CAN_JUNGLE}'),
                (57, '${constants.STRONG_LATE}'),
                (57, '${constants.MID_RANGE}'),
                (57, '${constants.ADC}'),
                (57, '${constants.FAST_RIP}'),
                (58, '${constants.CAN_LANE /* Mewtwo-Y */}'),
                (58, '${constants.STRONG_LATE}'),
                (58, '${constants.MID_RANGE}'),
                (58, '${constants.ADC}'),
                (58, '${constants.GOOD_SUSTAIN}'),
                (58, '${constants.SOLO_CARRY}'),
                (58, '${constants.TEAMFIGHTER}'),
                (59, '${constants.CAN_LANE /* Mewtwo-X */}'),
                (59, '${constants.STRONG_MIDDLE}'),
                (59, '${constants.MELEE}'),
                (59, '${constants.BRUISER}'),
                (59, '${constants.GOOD_SUSTAIN}'),
                (59, '${constants.LOCKDOWN}'),
                (59, '${constants.GOOD_1V1}'),
                (60, '${constants.CAN_LANE /* Blaziken */}'),
                (60, '${constants.STRONG_MIDDLE}'),
                (60, '${constants.BRUISER}'),
                (60, '${constants.ENGAGE}'),
                (60, '${constants.POKE}'),
                (60, '${constants.HAS_UNSTOPPABLE}'),
                (60, '${constants.HAS_UNSTOPPABLE}'),
                (60, '${constants.BURST_DAMAGE}'),
                (60, '${constants.GOOD_1V1}'),
                (60, '${constants.GOOD_SECURE}'),
                (60, '${constants.MEDIUM_MOBILITY}'),
                (60, '${constants.MEDIUM_MOBILITY}'),
                (61, '${constants.CAN_LANE /* Mimikyu */}'),
                (61, '${constants.CAN_JUNGLE}'),
                (61, '${constants.STRONG_MIDDLE}'),
                (61, '${constants.MELEE}'),
                (61, '${constants.BRUISER}'),
                (61, '${constants.GOOD_SUSTAIN}'),
                (61, '${constants.SINGLE_CC}'),
                (61, '${constants.GOOD_1V1}'),
                (62, '${constants.CAN_LANE /* Meowscarada */}'),
                (62, '${constants.CAN_JUNGLE}'),
                (62, '${constants.STRONG_MIDDLE}'),
                (62, '${constants.MELEE}'),
                (62, '${constants.MEDIUM_MOBILITY}'),
                (62, '${constants.ASSASSAIN}'),
                (62, '${constants.GOOD_1V1}'),
                (62, '${constants.SNOWBALL}'),
                (63, '${constants.CAN_LANE /* Metagross */}'),
                (63, '${constants.STRONG_LATE}'),
                (63, '${constants.MELEE}'),
                (63, '${constants.BRUISER}'),
                (63, '${constants.SINGLE_CC}'),
                (63, '${constants.GOOD_1V1}'),
                (63, '${constants.TEAMFIGHTER}'),
                (64, '${constants.CAN_LANE /* Gyarados */}'),
                (64, '${constants.STRONG_MIDDLE}'),
                (64, '${constants.MELEE}'),
                (64, '${constants.BRUISER}'),
                (64, '${constants.ENGAGE}'),
                (64, '${constants.DISENGAGE}'),
                (64, '${constants.GOOD_SUSTAIN}'),
                (64, '${constants.GOOD_1V1}'), 
                (65, '${constants.CAN_LANE /* Miraidon */}'),
                (65, '${constants.STRONG_LATE}'),
                (65, '${constants.LONG_RANGE}'),
                (65, '${constants.BURST_MAGE}'),
                (65, '${constants.POKE}'),
                (65, '${constants.BUFFS}'),
                (65, '${constants.TEAMFIGHTER}'),
                (66, '${constants.CAN_LANE /* Falinks */}'),
                (66, '${constants.STRONG_EARLY}'),
                (66, '${constants.STRONG_MIDDLE}'),
                (66, '${constants.MELEE}'),
                (66, '${constants.BRUISER}'),
                (66, '${constants.ENGAGE}'),
                (67, '${constants.CAN_LANE /* Ho-Oh */}'),
                (67, '${constants.LOW_RANGE}'),
                (67, '${constants.TANK}'),
                (67, '${constants.GOOD_SUSTAIN}'),
                (67, '${constants.GROUP_HEALING}'),
                (67, '${constants.TEAMFIGHTER}'),
                ;
        `, (err) => {
            if (err) {
                console.log("Error inserting into pokemon_attributes: " + err.message);
                process.exit(1);
            } else {
                console.log("Successfully inserted attributess.");
            }
        });
    }

    // These are attributes coming from each specific move
    function populateMoveAttributes(db) {
        db.exec(`
        insert into move_attributes (pokemon_id, move_name, attribute)
            values
                (1, '${constants.CINDERACE_MOVE_1A_PYROBALL /* Cinderace */}', '${}'),
                (1, '${constants.CINDERACE_MOVE_1B_BLAZEKICK}', '${}'),
                (1, '${constants.CINDERACE_MOVE_2A_LOWSWEEP}', '${}'),
                (1, '${constants.CINDERACE_MOVE_2B_FEINT}', '${}'),
                (2, '${constants.GARCHOMP_MOVE_1A_DIG /* Garchomp */}', '${}'),
                (2, '${constants.GARCHOMP_MOVE_1B_DRAGONRUSH}', '${}'),
                (2, '${constants.GARCHOMP_MOVE_2A_EARTHQUAKE}', '${}'),
                (2, '${constants.GARCHOMP_MOVE_2B_DRAGONCLAW}', '${}'),
                (3, '${constants.GENGAR_MOVE_1A_SHADOWBALL /* Gengar */}', '${}'),
                (3, '${constants.GENGAR_MOVE_1B_SLUDGEBOMB}', '${}'),
                (3, '${constants.GENGAR_MOVE_2A_DREAMEATER}', '${}'),
                (3, '${constants.GENGAR_MOVE_2B_HEX}', '${}'),
                (4, '${constants.CRAMORANT_MOVE_1A_SURF /* Cramorant */}', '${}'),
                (4, '${constants.CRAMORANT_MOVE_1B_DIVE}', '${}'),
                (4, '${constants.CRAMORANT_MOVE_2A_HURRICANE}', '${}'),
                (4, '${constants.CRAMORANT_MOVE_2B_AIRSLASH}', '${}'),
                (5, '${constants.ALOLANNINETALES_MOVE_1A_AVALANCHE /* Alolan-Ninetales */}', '${}'),
                (5, '${constants.ALOLANNINETALES_MOVE_1B_DAZZLINGGLEAM}', '${}'),
                (5, '${constants.ALOLANNINETALES_MOVE_2A_BLIZZARD}', '${}'),
                (5, '${constants.ALOLANNINETALES_MOVE_2B_AURORAVEIL}', '${}'),
                (6, '${constants.WIGGLYTUFF_MOVE_1A_DOUBLESLAP /* Wigglytuff */}', '${}'),
                (6, '${constants.WIGGLYTUFF_MOVE_1B_DAZZLINGGLEAM}', '${}'),
                (6, '${constants.WIGGLYTUFF_MOVE_2A_ROLLOUT}', '${}'),
                (6, '${constants.WIGGLYTUFF_MOVE_2B_SING}', '${}'),
                (7, '${constants.MACHAMP_MOVE_1A_CLOSECOMBAT /* Machamp */}', '${}'),
                (7, '${constants.MACHAMP_MOVE_1B_CROSSCHOP}', '${}'),
                (7, '${constants.MACHAMP_MOVE_2A_DYNAMICPUNCH}', '${}'),
                (7, '${constants.MACHAMP_MOVE_2B_SUBMISSION}', '${}'),
                (8, '${constants.ABSOL_MOVE_1A_NIGHTSLASH /* Absol */}', '${}'),
                (8, '${constants.ABSOL_MOVE_1B_PURSUIT}', '${}'),
                (8, '${constants.ABSOL_MOVE_2A_PSYCHOCUT}', '${}'),
                (8, '${constants.ABSOL_MOVE_2B_SUCKERPUNCH}', '${}'),
                (9, '${constants.SLOWBRO_MOVE_1A_SCALD /* Slowbro */}', '${}'),
                (9, '${constants.SLOWBRO_MOVE_1B_SURF}', '${}'),
                (9, '${constants.SLOWBRO_MOVE_2A_AMNESIA}', '${}'),
                (9, '${constants.SLOWBRO_MOVE_2B_TELEKINESIS}', '${}'),
                (10, '${constants.MRMIME_MOVE_1A_CONFUSION /* Mr-Mime */}', '${}'),
                (10, '${constants.MRMIME_MOVE_1B_PSYCHIC}', '${}'),
                (10, '${constants.MRMIME_MOVE_2A_BARRIER}', '${}'),
                (10, '${constants.MRMIME_MOVE_2B_POWERSWAP}', '${}'),
                (11, '${constants.VENUSAUR_MOVE_1A_SLUDGEBOMB /* Venusaur */}', '${}'),
                (11, '${constants.VENUSAUR_MOVE_1B_GIGADRAIN}', '${}'),
                (11, '${constants.VENUSAUR_MOVE_2A_SOLARBEAM}', '${}'),
                (11, '${constants.VENUSAUR_MOVE_2B_PETALDANCE}', '${}'),
                (12, '${constants.LUCARIO_MOVE_1A_EXTREMESPEED /* Lucario */}', '${}'),
                (12, '${constants.LUCARIO_MOVE_1B_POWERUPPUNCH}', '${}'),
                (12, '${constants.LUCARIO_MOVE_2A_BONERUSH}', '${}'),
                (12, '${constants.LUCARIO_MOVE_2B_CLOSECOMBAT}', '${}'),
                (13, '${constants.TALONFLAME_MOVE_1A_FLAMECHARGE /* Talonflame */}', '${}'),
                (13, '${constants.TALONFLAME_MOVE_1B_AERIALACE}', '${}'),
                (13, '${constants.TALONFLAME_MOVE_2A_FLY}', '${}'),
                (13, '${constants.TALONFLAME_MOVE_2B_BRAVEBIRD}', '${}'),
                (14, '${constants.ELDEGOSS_MOVE_1A_POLLENPUFF /* Eldegoss */}', '${}'),
                (14, '${constants.ELDEGOSS_MOVE_1B_LEAFTORNADO}', '${}'),
                (14, '${constants.ELDEGOSS_MOVE_2A_COTTONGUARD}', '${}'),
                (14, '${constants.ELDEGOSS_MOVE_2B_COTTONSPORE}', '${}'),
                (15, '${constants.GRENINJA_MOVE_1A_WATERSHURIKEN /* Greninja */}', '${}'),
                (15, '${constants.GRENINJA_MOVE_1B_SURF}', '${}'),
                (15, '${constants.GRENINJA_MOVE_2A_DOUBLETEAM}', '${}'),
                (15, '${constants.GRENINJA_MOVE_2B_SMOKESCREEN}', '${}'),
                (16, '${constants.CRUSTLE_MOVE_1A_ROCKTOMB /* Crustle */}', '${}'),
                (16, '${constants.CRUSTLE_MOVE_1B_SHELLSMASH}', '${}'),
                (16, '${constants.CRUSTLE_MOVE_2A_STEALTHROCK}', '${}'),
                (16, '${constants.CRUSTLE_MOVE_2B_XSCISSOR}', '${}'),
                (17, '${constants.SNORLAX_MOVE_1A_HEAVYSLAM /* Snorlax */}', '${}'),
                (17, '${constants.SNORLAX_MOVE_1B_FLAIL}', '${}'),
                (17, '${constants.SNORLAX_MOVE_2A_BLOCK}', '${}'),
                (17, '${constants.SNORLAX_MOVE_2B_YAWN}', '${}'),
                (18, '${constants.CHARIZARD_MOVE_1A_FLAMETHROWER /* Charizard */}', '${}'),
                (18, '${constants.CHARIZARD_MOVE_1B_FIREPUNCH}', '${}'),
                (18, '${constants.CHARIZARD_MOVE_2A_FIREBLAST}', '${}'),
                (18, '${constants.CHARIZARD_MOVE_2B_FLAREBLITZ}', '${}'),
                (19, '${constants.PIKACHU_MOVE_1A_ELECTROBALL /* Pikachu */}', '${}'),
                (19, '${constants.PIKACHU_MOVE_1B_THUNDER}', '${}'),
                (19, '${constants.PIKACHU_MOVE_2A_VOLTTACKLE}', '${}'),
                (19, '${constants.PIKACHU_MOVE_2B_THUNDERBOLT}', '${}'),
                (20, '${constants.ZERAORA_MOVE_1A_VOLTSWITCH /* Zeraora */}', '${}'),
                (20, '${constants.ZERAORA_MOVE_1B_SPARK}', '${}'),
                (20, '${constants.ZERAORA_MOVE_2A_DISCHARGE}', '${}'),
                (20, '${constants.ZERAORA_MOVE_2B_WILDCHARGE}', '${}'),
                (21, '${constants.GARDEVOIR_MOVE_1A_PSYCHIC /* Gardevoir */}', '${}'),
                (21, '${constants.GARDEVOIR_MOVE_1B_MOONBLAST}', '${}'),
                (21, '${constants.GARDEVOIR_MOVE_2A_PSYSHOCK}', '${}'),
                (21, '${constants.GARDEVOIR_MOVE_2B_FUTURESIGHT}', '${}'),
                (22, '${constants.BLISSEY_MOVE_1A_EGGBOMB /* Blissey */}', '${}'),
                (22, '${constants.BLISSEY_MOVE_1B_HELPINGHAND}', '${}'),
                (22, '${constants.BLISSEY_MOVE_2A_SOFTBOILED}', '${}'),
                (22, '${constants.BLISSEY_MOVE_2B_SAFEGUARD}', '${}'),
                (23, '${constants.BLASTOISE_MOVE_1A_HYDROPUMP /* Blastoise */}', '${}'),
                (23, '${constants.BLASTOISE_MOVE_1B_WATERSPOUT}', '${}'),
                (23, '${constants.BLASTOISE_MOVE_2A_SURF}', '${}'),
                (23, '${constants.BLASTOISE_MOVE_2B_RAPIDSPIN}', '${}'),
                (24, '${constants.MAMOSWINE_MOVE_1A_ICICLECRASH /* Mamoswine */}', '${}'),
                (24, '${constants.MAMOSWINE_MOVE_1B_ICEFANG}', '${}'),
                (24, '${constants.MAMOSWINE_MOVE_2A_HIGHHORSEPOWER}', '${}'),
                (24, '${constants.MAMOSWINE_MOVE_2B_EARTHQUAKE}', '${}'),
                (25, '${constants.SYLVEON_MOVE_1A_MYSTICALFIRE /* Sylveon */}', '${}'),
                (25, '${constants.SYLVEON_MOVE_1B_HYPERVOICE}', '${}'),
                (25, '${constants.SYLVEON_MOVE_2A_DRAININGKISS}', '${}'),
                (25, '${constants.SYLVEON_MOVE_2B_CALMMIND}', '${}'),
                (26, '${constants.GREEDENT_MOVE_1A_BULLETSEED /* Greedent */}', '${}'),
                (26, '${constants.GREEDENT_MOVE_1B_BELCH}', '${}'),
                (26, '${constants.GREEDENT_MOVE_2A_STUFFCHEEKS}', '${}'),
                (26, '${constants.GREEDENT_MOVE_2B_COVET}', '${}'),
                (27, '${constants.DECIDUEYE_MOVE_1A_RAZORLEAF /* Decidueye */}', '${}'),
                (27, '${constants.DECIDUEYE_MOVE_1B_SPIRITSHACKLE}', '${}'),
                (27, '${constants.DECIDUEYE_MOVE_2A_LEAFSTORM}', '${}'),
                (27, '${constants.DECIDUEYE_MOVE_2B_SHADOWSNEAK}', '${}'),
                (28, '${constants.TSAREENA_MOVE_1A_TRIPLEAXEL /* Tsareena */}', '${}'),
                (28, '${constants.TSAREENA_MOVE_1B_STOMP}', '${}'),
                (28, '${constants.TSAREENA_MOVE_2A_TROPKICK}', '${}'),
                (28, '${constants.TSAREENA_MOVE_2B_GRASSYGLIDE}', '${}'),
                (29, '${constants.DRAGONITE_MOVE_1A_DRAGONDANCE /* Dragonite */}', '${}'),
                (29, '${constants.DRAGONITE_MOVE_1B_EXTREMESPEED}', '${}'),
                (29, '${constants.DRAGONITE_MOVE_2A_HYPERBEAM}', '${}'),
                (29, '${constants.DRAGONITE_MOVE_2B_OUTRAGE}', '${}'),
                (30, '${constants.TREVENANT_MOVE_1A_WOODHAMMER /* Trevenant */}', '${}'),
                (30, '${constants.TREVENANT_MOVE_1B_CURSE}', '${}'),
                (30, '${constants.TREVENANT_MOVE_2A_HORNLEECH}', '${}'),
                (30, '${constants.TREVENANT_MOVE_2B_PAINSPLIT}', '${}'),
                (31, '${constants.AEGISLASH_MOVE_1A_SACREDSWORD /* Aegislash */}', '${}'),
                (31, '${constants.AEGISLASH_MOVE_1B_SHADOWCLAW}', '${}'),
                (31, '${constants.AEGISLASH_MOVE_2A_WIDEGUARD}', '${}'),
                (31, '${constants.AEGISLASH_MOVE_2B_IRONHEAD}', '${}'),
                (32, '${constants.HOOPA_MOVE_1A_PHANTOMFORCE /* Hoopa */}', '${}'),
                (32, '${constants.HOOPA_MOVE_1B_SHADOWBALL}', '${}'),
                (32, '${constants.HOOPA_MOVE_2A_HYPERSPACEHOLE}', '${}'),
                (32, '${constants.HOOPA_MOVE_2B_TRICK}', '${}'),
                (33, '${constants.DURALUDON_MOVE_1A_FLASHCANNON /* Duraludon */}', '${}'),
                (33, '${constants.DURALUDON_MOVE_1B_DRAGONPULSE}', '${}'),
                (33, '${constants.DURALUDON_MOVE_2A_DRAGONTAIL}', '${}'),
                (33, '${constants.DURALUDON_MOVE_2B_STEALTHROCK}', '${}'),
                (34, '${constants.AZUMARILL_MOVE_1A_PLAYROUGH /* Azumarill */}', '${}'),
                (34, '${constants.AZUMARILL_MOVE_1B_WATERPULSE}', '${}'),
                (34, '${constants.AZUMARILL_MOVE_2A_WHIRLPOOL}', '${}'),
                (34, '${constants.AZUMARILL_MOVE_2B_AQUATAIL}', '${}'),
                (35, '${constants.ESPEON_MOVE_1A_PSYSHOCK /* Espeon */}', '${}'),
                (35, '${constants.ESPEON_MOVE_1B_STOREDPOWER}', '${}'),
                (35, '${constants.ESPEON_MOVE_2A_PSYBEAM}', '${}'),
                (35, '${constants.ESPEON_MOVE_2B_FUTURESIGHT}', '${}'),
                (36, '${constants.DELPHOX_MOVE_1A_FIREBLAST /* Delphox */}', '${}'),
                (36, '${constants.DELPHOX_MOVE_1B_MYSTICALFIRE}', '${}'),
                (36, '${constants.DELPHOX_MOVE_2A_FIRESPIN}', '${}'),
                (36, '${constants.DELPHOX_MOVE_2B_FLAMECHARGE}', '${}'),
                (37, '${constants.GLACEON_MOVE_1A_ICICLESPEAR /* Glaceon */}', '${}'),
                (37, '${constants.GLACEON_MOVE_1B_ICYWIND}', '${}'),
                (37, '${constants.GLACEON_MOVE_2A_ICESHARD}', '${}'),
                (37, '${constants.GLACEON_MOVE_2B_FREEZEDRY}', '${}'),
                (38, '${constants.BUZZWOLE_MOVE_1A_LUNGE /* Buzzwole */}', '${}'),
                (38, '${constants.BUZZWOLE_MOVE_1B_SMACKDOWN}', '${}'),
                (38, '${constants.BUZZWOLE_MOVE_2A_LEECHLIFE}', '${}'),
                (38, '${constants.BUZZWOLE_MOVE_2B_SUPERPOWER}', '${}'),
                (39, '${constants.TYRANITAR_MOVE_1A_DARKPULSE /* Tyranitar */}', '${}'),
                (39, '${constants.TYRANITAR_MOVE_1B_STONEEDGE}', '${}'),
                (39, '${constants.TYRANITAR_MOVE_2A_ANCIENTPOWER}', '${}'),
                (39, '${constants.TYRANITAR_MOVE_2B_SANDTOMB}', '${}'),
                (41, '${constants.DODRIO_MOVE_1A_TRIATTACK /* Dodrio */}', '${}'),
                (41, '${constants.DODRIO_MOVE_1B_DRILLPECK}', '${}'),
                (41, '${constants.DODRIO_MOVE_2A_AGILITY}', '${}'),
                (41, '${constants.DODRIO_MOVE_2B_JUMPKICK}', '${}'),
                (42, '${constants.SCIZOR_MOVE_1A_BULLETPUNCH /* Scizor */}', '${}'),
                (42, '${constants.SCIZOR_MOVE_2A_DOUBLEHIT}', '${}'),
                (42, '${constants.SCIZOR_MOVE_2B_SWORDSDANCE}', '${}'),
                (43, '${constants.SCYTHER_MOVE_1A_DUALWINGBEAT /* Scyther */}', '${}'),
                (43, '${constants.SCYTHER_MOVE_2A_DOUBLEHIT}', '${}'),
                (43, '${constants.SCYTHER_MOVE_2B_SWORDSDANCE}', '${}'),
                (44, '${constants.CLEFABLE_MOVE_1A_MOONLIGHT /* Clefable */}', '${}'),
                (44, '${constants.CLEFABLE_MOVE_1B_DRAININGKISS}', '${}'),
                (44, '${constants.CLEFABLE_MOVE_2A_GRAVITY}', '${}'),
                (44, '${constants.CLEFABLE_MOVE_2B_FOLLOWME}', '${}'),
                (45, '${constants.ZOROARK_MOVE_1A_SHADOWCLAW /* Zoroark */}', '${}'),
                (45, '${constants.ZOROARK_MOVE_1B_CUT}', '${}'),
                (45, '${constants.ZOROARK_MOVE_2A_NIGHTSLASH}', '${}'),
                (45, '${constants.ZOROARK_MOVE_2B_FEINTATTACK}', '${}'),
                (46, '${constants.SABLEYE_MOVE_1A_KNOCKOFF /* Sableye */}', '${}'),
                (40, '${constants.SABLEYE_MOVE_1B_SHADOWSNEAK}', '${}'),
                (46, '${constants.SABLEYE_MOVE_2A_FEINTATTACK}', '${}'),
                (46, '${constants.SABLEYE_MOVE_2B_CONFUSERAY}', '${}'),
                (47, '${constants.URSHIFUSS_MOVE_1A_WICKEDBLOW /* Urshifu-SS */}', '${}'),
                (47, '${constants.URSHIFUSS_MOVE_2A_THROATCHOP}', '${}'),
                (48, '${constants.URSHIFURS_MOVE_1A_SURGINGSTRIKES /* Urshifu-RS */}', '${}'),
                (48, '${constants.URSHIFURS_MOVE_2A_LIQUIDATION}', '${}'),
                (49, '${constants.DRAGAPULT_MOVE_1A_DRAGONBREATH /* Dragapult */}', '${}'),
                (49, '${constants.DRAGAPULT_MOVE_1B_SHADOWBALL}', '${}'),
                (49, '${constants.DRAGAPULT_MOVE_2A_DRAGONDANCE}', '${}'),
                (49, '${constants.DRAGAPULT_MOVE_2B_PHANTOMFORCE}', '${}'),
                (50, '${constants.COMFEY_MOVE_1A_FLORALHEALING /* Comfey */}', '${}'),
                (50, '${constants.COMFEY_MOVE_1B_SWEETKISS}', '${}'),
                (50, '${constants.COMFEY_MOVE_2A_MAGICALLEAF}', '${}'),
                (50, '${constants.COMFEY_MOVE_2B_GRASSKNOT}', '${}'),
                (51, '${constants.ZACIAN_MOVE_1A_METALCLAW /* Zacian */}', '${}'),
                (51, '${constants.ZACIAN_MOVE_1B_SACREDSWORD}', '${}'),
                (51, '${constants.ZACIAN_MOVE_2A_AGILITY}', '${}'),
                (51, '${constants.ZACIAN_MOVE_2B_PLAYROUGH}', '${}'),
                (52, '${constants.GOODRA_MOVE_1A_MUDDYWATER /* Goodra */}', '${}'),
                (52, '${constants.GOODRA_MOVE_1B_DRAGONPULSE}', '${}'),
                (52, '${constants.GOODRA_MOVE_2A_POWERWHIP}', '${}'),
                (52, '${constants.GOODRA_MOVE_2B_ACIDSPRAY}', '${}'),
                (53, '${constants.LAPRAS_MOVE_1A_WATERPULSE /* Lapras */}', '${}'),
                (53, '${constants.LAPRAS_MOVE_1B_PERISHSONG}', '${}'),
                (53, '${constants.LAPRAS_MOVE_2A_BUBBLEBEAM}', '${}'),
                (53, '${constants.LAPRAS_MOVE_2B_ICEBEAM}', '${}'),
                (54, '${constants.CHANDELURE_MOVE_1A_FLAMETHROWER /* Chandelure */}', '${}'),
                (54, '${constants.CHANDELURE_MOVE_1B_OVERHEAT}', '${}'),
                (54, '${constants.CHANDELURE_MOVE_2A_POLTERGEIST}', '${}'),
                (54, '${constants.CHANDELURE_MOVE_2B_IMPRISON}', '${}'),
                (55, '${constants.UMBREON_MOVE_1A_MEANLOOK /* Umbreon */}', '${}'),
                (55, '${constants.UMBREON_MOVE_1B_FOULPLAY}', '${}'),
                (55, '${constants.UMBREON_MOVE_2A_WISH}', '${}'),
                (55, '${constants.UMBREON_MOVE_2B_SNARL}', '${}'),
                (56, '${constants.LEAFEON_MOVE_1A_RAZORLEAF /* Leafeon */}', '${}'),
                (56, '${constants.LEAFEON_MOVE_1B_SOLARBLADE}', '${}'),
                (56, '${constants.LEAFEON_MOVE_2A_AERIALACE}', '${}'),
                (56, '${constants.LEAFEON_MOVE_2B_LEAFBLADE}', '${}'),
                (57, '${constants.INTELEON_MOVE_1A_FELLSTINGER /* Inteleon */}', '${}'),
                (57, '${constants.INTELEON_MOVE_1B_ACROBATICS}', '${}'),
                (57, '${constants.INTELEON_MOVE_2A_SNIPESHOT}', '${}'),
                (57, '${constants.INTELEON_MOVE_2B_LIQUIDATION}', '${}'),
                (58, '${constants.MEWTWOY_MOVE_1A_FUTURESIGHT /* Mewtwo-Y */}', '${}'),
                (58, '${constants.MEWTWOY_MOVE_1B_PSYSTRIKE}', '${}'),
                (58, '${constants.MEWTWOY_MOVE_2A_RECOVER}', '${}'),
                (58, '${constants.MEWTWOY_MOVE_2B_TELEPORT}', '${}'),
                (59, '${constants.MEWTWOX_MOVE_1A_FUTURESIGHT /* Mewtwo-X */}', '${}'),
                (59, '${constants.MEWTWOX_MOVE_1B_PSYSTRIKE}', '${}'),
                (59, '${constants.MEWTWOX_MOVE_2A_RECOVER}', '${}'),
                (59, '${constants.MEWTWOX_MOVE_2B_TELEPORT}', '${}'),
                (61, '${constants.MIMIKYU_MOVE_1A_PLAYROUGH /* Mimikyu */}', '${}'),
                (61, '${constants.MIMIKYU_MOVE_1B_SHADOWCLAW}', '${}'),
                (61, '${constants.MIMIKYU_MOVE_2A_SHADOWSNEAK}', '${}'),
                (61, '${constants.MIMIKYU_MOVE_2B_TRICKROOM}', '${}'),
                (62, '${constants.MEOWSCARADA_MOVE_1A_FLOWERTRICK /* Meowscarada */}', '${}'),
                (62, '${constants.MEOWSCARADA_MOVE_1B_NIGHTSLASH}', '${}'),
                (62, '${constants.MEOWSCARADA_MOVE_2A_DOUBLETEAM}', '${}'),
                (62, '${constants.MEOWSCARADA_MOVE_2B_TRAILBLAZE}', '${}'),
                (63, '${constants.METAGROSS_MOVE_1A_METEORMASH /* Metagross */}', '${}'),
                (63, '${constants.METAGROSS_MOVE_1B_GYROBALL}', '${}'),
                (63, '${constants.METAGROSS_MOVE_2A_ZENHEADBUTT}', '${}'),
                (63, '${constants.METAGROSS_MOVE_2B_MAGNETRISE}', '${}'),
                (64, '${constants.GYARADOS_MOVE_1A_DRAGONBREATH /* Gyarados */}', '${}'),
                (64, '${constants.GYARADOS_MOVE_1B_AQUATAIL}', '${}'),
                (64, '${constants.GYARADOS_MOVE_2A_WATERFALL}', '${}'),
                (64, '${constants.GYARADOS_MOVE_2B_BOUNCE}', '${}'),
                (65, '${constants.MIRAIDON_MOVE_1A_CHARGEBEAM /* Miraidon */}', '${}'),
                (65, '${constants.MIRAIDON_MOVE_1B_ELECTRODRIFT}', '${}'),
                (65, '${constants.MIRAIDON_MOVE_2A_THUNDER}', '${}'),
                (65, '${constants.MIRAIDON_MOVE_2B_PARABOLICCHARGE}', '${}'),
                (66, '${constants.FALINKS_MOVE_1A_MEGAHORN /* Falinks */}', '${}'),
                (66, '${constants.FALINKS_MOVE_1B_IRONHEAD}', '${}'),
                (66, '${constants.FALINKS_MOVE_2A_NORETREAT}', '${}'),
                (66, '${constants.FALINKS_MOVE_2B_BEATUP}', '${}'),
                (67, '${constants.HOOH_MOVE_1A_FLY /* Ho-Oh */}', '${}'),
                (67, '${constants.HOOH_MOVE_1B_FIRESPIN}', '${}'),
                (67, '${constants.HOOH_MOVE_2A_FLAMETHROWER}', '${}'),
                (67, '${constants.HOOH_MOVE_2B_SKYATTACK}', '${}'),
                ;
        `, (err) => {
            if (err) {
                console.log("Error inserting into pokemon_attributes: " + err.message);
                process.exit(1);
            } else {
                console.log("Successfully inserted attributess.");
            }
        });
    }

    // Testing to make sure the database populated correctly
    function runQueries(db) {
        db.all(`
        select * from playable_characters natural join pokemon_attributes`, (err, rows) => {
            if (err) {
                console.log("Getting error " + err);
                return;
            }
            rows.forEach(row => {
                console.log(row.pokemon_id, row.pokemon_name, row.pokemon_class, row.attribute);
            });
        });
    }

    // Drops all existing tables to clear the database
    function clearDatabase(db, callback) {
        db.exec(`
        DROP TABLE IF EXISTS pokemon_attributes;
        DROP TABLE IF EXISTS playable_characters;
        `, (err) => {
            if (err) {
                console.log("Getting error " + err);
                return;
            }
            callback();
        });
    }
}