const compsData = [
  {
    "t1poke1": "Sylveon",
    "t1poke2": "Metagross",
    "t1poke3": "Mr_Mime",
    "t1poke4": "Blaziken",
    "t1poke5": "Eldegoss",
    "t1ban1": "Gyarados",
    "t1ban2": "Falinks",
    "t1poke1move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t1poke1move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t1poke2move1": "METAGROSS_MOVE_1B_GYROBALL: 'Gyro Ball',",
    "t1poke2move2": "METAGROSS_MOVE_2B_MAGNETRISE: 'Magnet Rise',",
    "t1poke3move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke3move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke4move1": "BLAZIKEN_ALL_MOVES",
    "t1poke4move2": "BLAZIKEN_ALL_MOVES",
    "t1poke5move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t1poke5move2": "ELDEGOSS_MOVE_2B_COTTONSPORE: 'Cotton Spore',",
    "t1name": "Exile",
    "t1region": "NA",
    "t1player1": "symp",
    "t1player2": "oblivion",
    "t1player3": "pure",
    "t1player4": "freaky",
    "t1player5": "neon",
    "t2poke1": "Crustle",
    "t2poke2": "Leafeon",
    "t2poke3": "Espeon",
    "t2poke4": "Hoopa",
    "t2poke5": "Garchomp",
    "t2ban1": "Trevenant",
    "t2ban2": "Tyranitar",
    "t2poke1move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t2poke1move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t2poke2move1": "LEAFEON_MOVE_1B_SOLARBLADE: 'Solar Blade',",
    "t2poke2move2": "LEAFEON_MOVE_2B_LEAFBLADE: 'Leaf Blade',",
    "t2poke3move1": "ESPEON_MOVE_1B_STOREDPOWER: 'Stored Power',",
    "t2poke3move2": "ESPEON_MOVE_2A_PSYBEAM: 'Psybeam',",
    "t2poke4move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t2poke4move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t2poke5move1": "GARCHOMP_MOVE_1B_DRAGONRUSH: 'Dragon Rush',",
    "t2poke5move2": "GARCHOMP_MOVE_2B_DRAGONCLAW: 'Dragon Claw',",
    "t2name": "Ignorance",
    "t2region": "NA",
    "t2player1": "SoupChef2",
    "t2player2": "BroteinShake",
    "t2player3": "nayeon",
    "t2player4": "Scrublenaut",
    "t2player5": "Gupiter",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "1"
  },
  {
    "t1poke1": "Sylveon",
    "t1poke2": "Mr_Mime",
    "t1poke3": "Crustle",
    "t1poke4": "Falinks",
    "t1poke5": "Blaziken",
    "t1ban1": "Trevenant",
    "t1ban2": "Comfey",
    "t1poke1move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t1poke1move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t1poke2move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke2move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke3move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t1poke3move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t1poke4move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t1poke4move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t1poke5move1": "BLAZIKEN_ALL_MOVES",
    "t1poke5move2": "BLAZIKEN_ALL_MOVES",
    "t1name": "Ignorance",
    "t1region": "NA",
    "t1player1": "nayeon",
    "t1player2": "Scrublenaut",
    "t1player3": "SoupChef2",
    "t1player4": "Gupiter",
    "t1player5": "BroteinShake",
    "t2poke1": "Metagross",
    "t2poke2": "Eldegoss",
    "t2poke3": "Cramorant",
    "t2poke4": "Umbreon",
    "t2poke5": "Scizor",
    "t2ban1": "Gyarados",
    "t2ban2": "Tyranitar",
    "t2poke1move1": "METAGROSS_MOVE_1B_GYROBALL: 'Gyro Ball',",
    "t2poke1move2": "METAGROSS_MOVE_2B_MAGNETRISE: 'Magnet Rise',",
    "t2poke2move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t2poke2move2": "ELDEGOSS_MOVE_2B_COTTONSPORE: 'Cotton Spore',",
    "t2poke3move1": "CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',",
    "t2poke3move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t2poke4move1": "UMBREON_MOVE_1B_FOULPLAY: 'Foul Play',",
    "t2poke4move2": "UMBREON_MOVE_2B_SNARL: 'Snarl',",
    "t2poke5move1": "SCIZOR_MOVE_1A_BULLETPUNCH: 'Bullet Punch',",
    "t2poke5move2": "SCIZOR_MOVE_2B_SWORDSDANCE: 'Swords Dance',",
    "t2name": "Exile",
    "t2region": "NA",
    "t2player1": "oblivion",
    "t2player2": "neon",
    "t2player3": "symp",
    "t2player4": "pure",
    "t2player5": "freaky",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "1"
  },
  {
    "t1poke1": "Tyranitar",
    "t1poke2": "Blaziken",
    "t1poke3": "Mr_Mime",
    "t1poke4": "Cramorant",
    "t1poke5": "Eldegoss",
    "t1ban1": "Gyarados",
    "t1ban2": "Falinks",
    "t1poke1move1": "TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',",
    "t1poke1move2": "TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',",
    "t1poke2move1": "BLAZIKEN_ALL_MOVES",
    "t1poke2move2": "BLAZIKEN_ALL_MOVES",
    "t1poke3move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke3move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke4move1": "CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',",
    "t1poke4move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t1poke5move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t1poke5move2": "ELDEGOSS_MOVE_2B_COTTONSPORE: 'Cotton Spore',",
    "t1name": "Exile",
    "t1region": "NA",
    "t1player1": "oblivion",
    "t1player2": "freaky",
    "t1player3": "pure",
    "t1player4": "symp",
    "t1player5": "neon",
    "t2poke1": "Crustle",
    "t2poke2": "Leafeon",
    "t2poke3": "Machamp",
    "t2poke4": "Hoopa",
    "t2poke5": "Delphox",
    "t2ban1": "Trevenant",
    "t2ban2": "Sylveon",
    "t2poke1move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t2poke1move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t2poke2move1": "LEAFEON_MOVE_1B_SOLARBLADE: 'Solar Blade',",
    "t2poke2move2": "LEAFEON_MOVE_2B_LEAFBLADE: 'Leaf Blade',",
    "t2poke3move1": "MACHAMP_MOVE_1A_DYNAMICPUNCH: 'Dynamic Punch',",
    "t2poke3move2": "MACHAMP_MOVE_2B_CROSSCHOP: 'Cross Chop',",
    "t2poke4move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t2poke4move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t2poke5move1": "DELPHOX_MOVE_1B_MYSTICALFIRE: 'Mystical Fire',",
    "t2poke5move2": "DELPHOX_MOVE_2B_FLAMECHARGE: 'Flame Charge',",
    "t2name": "Ignorance",
    "t2region": "NA",
    "t2player1": "SoupChef2",
    "t2player2": "BroteinShake",
    "t2player3": "Gupiter",
    "t2player4": "Scrublenaut",
    "t2player5": "nayeon",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "1"
  },
  {
    "t1poke1": "Leafeon",
    "t1poke2": "Mr_Mime",
    "t1poke3": "Cramorant",
    "t1poke4": "Blissey",
    "t1poke5": "Falinks",
    "t1ban1": "Umbreon",
    "t1ban2": "Sylveon",
    "t1poke1move1": "LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',",
    "t1poke1move2": "LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',",
    "t1poke2move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke2move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke3move1": "CRAMORANT_MOVE_1A_HURRICANE: 'Hurricane',",
    "t1poke3move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t1poke4move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t1poke4move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t1poke5move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t1poke5move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t1name": "Luminosity Gaming",
    "t1region": "NA",
    "t1player1": "Overlord",
    "t1player2": "Joey",
    "t1player3": "otter",
    "t1player4": "JL",
    "t1player5": "Lutano",
    "t2poke1": "Snorlax",
    "t2poke2": "Hoopa",
    "t2poke3": "Inteleon",
    "t2poke4": "Meowscarada",
    "t2poke5": "Talonflame",
    "t2ban1": "Tyranitar",
    "t2ban2": "Trevenant",
    "t2poke1move1": "SNORLAX_MOVE_1A_HEAVYSLAM: 'Heavy Slam',",
    "t2poke1move2": "SNORLAX_MOVE_2B_YAWN: 'Yawn',",
    "t2poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t2poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t2poke3move1": "INTELEON_MOVE_1A_FELLSTINGER: 'Fell Stinger',",
    "t2poke3move2": "INTELEON_MOVE_2A_SNIPESHOT: 'Snipe Shot',",
    "t2poke4move1": "MEOWSCARADA_MOVE_1A_FLOWERTRICK: 'Flower Trick',",
    "t2poke4move2": "MEOWSCARADA_MOVE_2A_DOUBLETEAM: 'Double Team',",
    "t2poke5move1": "TALONFLAME_MOVE_1A_FLAMECHARGE: 'Flame Charge',",
    "t2poke5move2": "TALONFLAME_MOVE_2A_FLY: 'Fly',",
    "t2name": "Brave Birders",
    "t2region": "NA",
    "t2player1": "owo",
    "t2player2": "Vinny256",
    "t2player3": "RSG_Red",
    "t2player4": "Ascha",
    "t2player5": "Kolintang",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "2"
  },
  {
    "t1poke1": "Leafeon",
    "t1poke2": "Snorlax",
    "t1poke3": "Hoopa",
    "t1poke4": "Meowscarada",
    "t1poke5": "Venusaur",
    "t1ban1": "Trevenant",
    "t1ban2": "Falinks",
    "t1poke1move1": "LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',",
    "t1poke1move2": "LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',",
    "t1poke2move1": "SNORLAX_MOVE_1A_HEAVYSLAM: 'Heavy Slam',",
    "t1poke2move2": "SNORLAX_MOVE_2B_YAWN: 'Yawn',",
    "t1poke3move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke3move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke4move1": "MEOWSCARADA_MOVE_1A_FLOWERTRICK: 'Flower Trick',",
    "t1poke4move2": "MEOWSCARADA_MOVE_2A_DOUBLETEAM: 'Double Team',",
    "t1poke5move1": "VENUSAUR_MOVE_1B_GIGADRAIN: 'Giga Drain',",
    "t1poke5move2": "VENUSAUR_MOVE_2B_PETALDANCE: 'Petal Dance',",
    "t1name": "Brave Birders",
    "t1region": "NA",
    "t1player1": "Kolintang",
    "t1player2": "owo",
    "t1player3": "Vinny256",
    "t1player4": "Ascha",
    "t1player5": "RSG_Red",
    "t2poke1": "Cramorant",
    "t2poke2": "Sylveon",
    "t2poke3": "Zoroark",
    "t2poke4": "Mr_Mime",
    "t2poke5": "Comfey",
    "t2ban1": "Tyranitar",
    "t2ban2": "Umbreon",
    "t2poke1move1": "CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',",
    "t2poke1move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t2poke2move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t2poke2move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t2poke3move1": "ZOROARK_MOVE_1B_FEINTATTACK: 'Feint Attack',",
    "t2poke3move2": "ZOROARK_MOVE_2A_SHADOWCLAW: 'Shadow Claw',",
    "t2poke4move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t2poke4move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t2poke5move1": "COMFEY_MOVE_1A_FLORALHEALING: 'Floral Healing',",
    "t2poke5move2": "COMFEY_MOVE_2A_MAGICALLEAF: 'Magical Leaf',",
    "t2name": "Luminosity Gaming",
    "t2region": "NA",
    "t2player1": "otter",
    "t2player2": "Lutano",
    "t2player3": "Overlord",
    "t2player4": "Joey",
    "t2player5": "JL",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "2"
  },
  {
    "t1poke1": "Blissey",
    "t1poke2": "Falinks",
    "t1poke3": "Snorlax",
    "t1poke4": "Cramorant",
    "t1poke5": "Blaziken",
    "t1ban1": "Sylveon",
    "t1ban2": "Tyranitar",
    "t1poke1move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t1poke1move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t1poke2move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t1poke2move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t1poke3move1": "SNORLAX_MOVE_1A_HEAVYSLAM: 'Heavy Slam',",
    "t1poke3move2": "SNORLAX_MOVE_2B_YAWN: 'Yawn',",
    "t1poke4move1": "CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',",
    "t1poke4move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t1poke5move1": "BLAZIKEN_ALL_MOVES",
    "t1poke5move2": "BLAZIKEN_ALL_MOVES",
    "t1name": "Orange Juicers",
    "t1region": "NA",
    "t1player1": "Rollin",
    "t1player2": "Kraitos",
    "t1player3": "zugrug",
    "t1player4": "Flareons",
    "t1player5": "Machizzle",
    "t2poke1": "Leafeon",
    "t2poke2": "Trevenant",
    "t2poke3": "Mew",
    "t2poke4": "Hoopa",
    "t2poke5": "Lucario",
    "t2ban1": "Umbreon",
    "t2ban2": "Dodrio",
    "t2poke1move1": "LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',",
    "t2poke1move2": "LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',",
    "t2poke2move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke2move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke3move1": "MEW_ALL_MOVES",
    "t2poke3move2": "MEW_ALL_MOVES",
    "t2poke4move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t2poke4move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t2poke5move1": "LUCARIO_MOVE_1A_EXTREMESPEED: 'Extreme Speed',",
    "t2poke5move2": "LUCARIO_MOVE_2A_BONERUSH: 'Bone Rush',",
    "t2name": "Gee",
    "t2region": "NA",
    "t2player1": "Zel0ot",
    "t2player2": "slash",
    "t2player3": "BlackCH",
    "t2player4": "EggN00b",
    "t2player5": "OGwastaken",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "3"
  },
  {
    "t1poke1": "Umbreon",
    "t1poke2": "Hoopa",
    "t1poke3": "Gyarados",
    "t1poke4": "Meowscarada",
    "t1poke5": "Greninja",
    "t1ban1": "Dodrio",
    "t1ban2": "Mew",
    "t1poke1move1": "UMBREON_MOVE_1B_FOULPLAY: 'Foul Play',",
    "t1poke1move2": "UMBREON_MOVE_2A_WISH: 'Wish',",
    "t1poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke3move1": "GYARADOS_MOVE_1B_BOUNCE: 'Bounce',",
    "t1poke3move2": "GYARADOS_MOVE_2A_DRAGONBREATH: 'Dragon Breath',",
    "t1poke4move1": "MEOWSCARADA_MOVE_1A_FLOWERTRICK: 'Flower Trick',",
    "t1poke4move2": "MEOWSCARADA_MOVE_2A_DOUBLETEAM: 'Double Team',",
    "t1poke5move1": "GRENINJA_MOVE_1A_DOUBLETEAM: 'Double Team',",
    "t1poke5move2": "GRENINJA_MOVE_2A_WATERSHURIKEN: 'Water Shuriken',",
    "t1name": "Gee",
    "t1region": "NA",
    "t1player1": "slash",
    "t1player2": "EggN00b",
    "t1player3": "OGwastaken",
    "t1player4": "Zel0ot",
    "t1player5": "BlackCH",
    "t2poke1": "Trevenant",
    "t2poke2": "Blissey",
    "t2poke3": "Snorlax",
    "t2poke4": "Falinks",
    "t2poke5": "Cramorant",
    "t2ban1": "Sylveon",
    "t2ban2": "Tyranitar",
    "t2poke1move1": "TREVENANT_MOVE_1B_CURSE: 'Curse',",
    "t2poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke2move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke2move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke3move1": "SNORLAX_MOVE_1A_HEAVYSLAM: 'Heavy Slam',",
    "t2poke3move2": "SNORLAX_MOVE_2A_BLOCK: 'Block',",
    "t2poke4move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t2poke4move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t2poke5move1": "CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',",
    "t2poke5move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t2name": "Orange Juicers",
    "t2region": "NA",
    "t2player1": "Machizzle",
    "t2player2": "Rollin",
    "t2player3": "zugrug",
    "t2player4": "Kraitos",
    "t2player5": "Flareons",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "3"
  },
  {
    "t1poke1": "Crustle",
    "t1poke2": "Hoopa",
    "t1poke3": "Mew",
    "t1poke4": "Gyarados",
    "t1poke5": "Blaziken",
    "t1ban1": "Trevenant",
    "t1ban2": "Sylveon",
    "t1poke1move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t1poke1move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t1poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke3move1": "MEW_ALL_MOVES",
    "t1poke3move2": "MEW_ALL_MOVES",
    "t1poke4move1": "GYARADOS_MOVE_1B_BOUNCE: 'Bounce',",
    "t1poke4move2": "GYARADOS_MOVE_2A_DRAGONBREATH: 'Dragon Breath',",
    "t1poke5move1": "BLAZIKEN_ALL_MOVES",
    "t1poke5move2": "BLAZIKEN_ALL_MOVES",
    "t1name": "Ignorance",
    "t1region": "NA",
    "t1player1": "SoupChef2",
    "t1player2": "Scrublenaut",
    "t1player3": "nayeon",
    "t1player4": "Gupiter",
    "t1player5": "BroteinShake",
    "t2poke1": "Leafeon",
    "t2poke2": "Falinks",
    "t2poke3": "Blissey",
    "t2poke4": "Umbreon",
    "t2poke5": "Cramorant",
    "t2ban1": "Tyranitar",
    "t2ban2": "Venusaur",
    "t2poke1move1": "LEAFEON_MOVE_1B_SOLARBLADE: 'Solar Blade',",
    "t2poke1move2": "LEAFEON_MOVE_2B_LEAFBLADE: 'Leaf Blade',",
    "t2poke2move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t2poke2move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t2poke3move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke3move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke4move1": "UMBREON_MOVE_1B_FOULPLAY: 'Foul Play',",
    "t2poke4move2": "UMBREON_MOVE_2A_WISH: 'Wish',",
    "t2poke5move1": "CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',",
    "t2poke5move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t2name": "Gee",
    "t2region": "NA",
    "t2player1": "Zel0ot",
    "t2player2": "OGwastaken",
    "t2player3": "EggN00b",
    "t2player4": "slash",
    "t2player5": "BlackCH",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "4"
  },
  {
    "t1poke1": "Umbreon",
    "t1poke2": "Hoopa",
    "t1poke3": "Mew",
    "t1poke4": "Meowscarada",
    "t1poke5": "Blaziken",
    "t1ban1": "Tyranitar",
    "t1ban2": "Blissey",
    "t1poke1move1": "UMBREON_MOVE_1B_FOULPLAY: 'Foul Play',",
    "t1poke1move2": "UMBREON_MOVE_2A_WISH: 'Wish',",
    "t1poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke3move1": "MEW_ALL_MOVES",
    "t1poke3move2": "MEW_ALL_MOVES",
    "t1poke4move1": "MEOWSCARADA_MOVE_1A_FLOWERTRICK: 'Flower Trick',",
    "t1poke4move2": "MEOWSCARADA_MOVE_2A_DOUBLETEAM: 'Double Team',",
    "t1poke5move1": "BLAZIKEN_ALL_MOVES",
    "t1poke5move2": "BLAZIKEN_ALL_MOVES",
    "t1name": "Gee",
    "t1region": "NA",
    "t1player1": "slash",
    "t1player2": "EggN00b",
    "t1player3": "BlackCH",
    "t1player4": "Zel0ot",
    "t1player5": "OGwastaken",
    "t2poke1": "Sylveon",
    "t2poke2": "Leafeon",
    "t2poke3": "Lapras",
    "t2poke4": "Sableye",
    "t2poke5": "Metagross",
    "t2ban1": "Trevenant",
    "t2ban2": "Falinks",
    "t2poke1move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t2poke1move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t2poke2move1": "LEAFEON_MOVE_1B_SOLARBLADE: 'Solar Blade',",
    "t2poke2move2": "LEAFEON_MOVE_2B_LEAFBLADE: 'Leaf Blade',",
    "t2poke3move1": "LAPRAS_MOVE_1A_WATERPULSE: 'Water Pulse',",
    "t2poke3move2": "LAPRAS_MOVE_2B_ICEBEAM: 'Ice Beam',",
    "t2poke4move1": "SABLEYE_MOVE_1B_SHADOWSNEAK: 'Shadow Sneak',",
    "t2poke4move2": "SABLEYE_MOVE_2A_FEINTATTACK: 'Feint Attack',",
    "t2poke5move1": "METAGROSS_MOVE_1B_GYROBALL: 'Gyro Ball',",
    "t2poke5move2": "METAGROSS_MOVE_2B_MAGNETRISE: 'Magnet Rise',",
    "t2name": "Ignorance",
    "t2region": "NA",
    "t2player1": "nayeon",
    "t2player2": "BroteinShake",
    "t2player3": "SoupChef2",
    "t2player4": "Scrublenaut",
    "t2player5": "Gupiter",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "4"
  },
  {
    "t1poke1": "Leafeon",
    "t1poke2": "Hoopa",
    "t1poke3": "Mr_Mime",
    "t1poke4": "Dodrio",
    "t1poke5": "Gardevoir",
    "t1ban1": "Umbreon",
    "t1ban2": "Sylveon",
    "t1poke1move1": "LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',",
    "t1poke1move2": "LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',",
    "t1poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke3move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke3move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke4move1": "DODRIO_MOVE_1A_TRIATTACK: 'Tri Attack',",
    "t1poke4move2": "DODRIO_MOVE_2B_JUMPKICK: 'Jump Kick',",
    "t1poke5move1": "GARDEVOIR_MOVE_1A_PSYCHIC: 'Psychic',",
    "t1poke5move2": "GARDEVOIR_MOVE_2A_PSYSHOCK: 'Psyshock',",
    "t1name": "Luminosity Gaming",
    "t1region": "NA",
    "t1player1": "otter",
    "t1player2": "JL",
    "t1player3": "Joey",
    "t1player4": "Overlord",
    "t1player5": "Lutano",
    "t2poke1": "Trevenant",
    "t2poke2": "Crustle",
    "t2poke3": "Chandelure",
    "t2poke4": "Blastoise",
    "t2poke5": "Greedent",
    "t2ban1": "Tyranitar",
    "t2ban2": "Cramorant",
    "t2poke1move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke2move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t2poke2move2": "CRUSTLE_MOVE_2A_STEALTHROCK: 'Stealth Rock',",
    "t2poke3move1": "CHANDELURE_MOVE_1B_OVERHEAT: 'Overheat',",
    "t2poke3move2": "CHANDELURE_MOVE_2B_IMPRISON: 'Imprison',",
    "t2poke4move1": "BLASTOISE_MOVE_1A_HYDROPUMP: 'Hydro Pump',",
    "t2poke4move2": "BLASTOISE_MOVE_2B_RAPIDSPIN: 'Rapid Spin',",
    "t2poke5move1": "GREEDENT_MOVE_1B_COVET: 'Covet',",
    "t2poke5move2": "GREEDENT_MOVE_2B_BELCH: 'Belch',",
    "t2name": "Ni Hao",
    "t2region": "NA",
    "t2player1": "Duskrunner5",
    "t2player2": "Kirtan",
    "t2player3": "Victorin",
    "t2player4": "bits",
    "t2player5": "Waterboy",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "5"
  },
  {
    "t1poke1": "Tyranitar",
    "t1poke2": "Mr_Mime",
    "t1poke3": "Cramorant",
    "t1poke4": "Dodrio",
    "t1poke5": "Hoopa",
    "t1ban1": "Umbreon",
    "t1ban2": "Sylveon",
    "t1poke1move1": "TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',",
    "t1poke1move2": "TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',",
    "t1poke2move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke2move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke3move1": "CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',",
    "t1poke3move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t1poke4move1": "DODRIO_MOVE_1A_TRIATTACK: 'Tri Attack',",
    "t1poke4move2": "DODRIO_MOVE_2B_JUMPKICK: 'Jump Kick',",
    "t1poke5move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke5move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1name": "Luminosity Gaming",
    "t1region": "NA",
    "t1player1": "Lutano",
    "t1player2": "Joey",
    "t1player3": "otter",
    "t1player4": "Overlord",
    "t1player5": "JL",
    "t2poke1": "Trevenant",
    "t2poke2": "Blissey",
    "t2poke3": "Glaceon",
    "t2poke4": "Dragonite",
    "t2poke5": "Greninja",
    "t2ban1": "Leafeon",
    "t2ban2": "Falinks",
    "t2poke1move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke2move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke2move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke3move1": "GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',",
    "t2poke3move2": "GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',",
    "t2poke4move1": "DRAGONITE_MOVE_1A_DRAGONDANCE: 'Dragon Dance',",
    "t2poke4move2": "DRAGONITE_MOVE_2B_OUTRAGE: 'Outrage',",
    "t2poke5move1": "GRENINJA_MOVE_1A_DOUBLETEAM: 'Double Team',",
    "t2poke5move2": "GRENINJA_MOVE_2A_WATERSHURIKEN: 'Water Shuriken',",
    "t2name": "Ni Hao",
    "t2region": "NA",
    "t2player1": "Duskrunner5",
    "t2player2": "Kirtan",
    "t2player3": "Victorin",
    "t2player4": "bits",
    "t2player5": "Waterboy",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "5"
  },
  {
    "t1poke1": "Tyranitar",
    "t1poke2": "Hoopa",
    "t1poke3": "Cramorant",
    "t1poke4": "Mr_Mime",
    "t1poke5": "Dodrio",
    "t1ban1": "Umbreon",
    "t1ban2": "Blissey",
    "t1poke1move1": "TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',",
    "t1poke1move2": "TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',",
    "t1poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke3move1": "CRAMORANT_MOVE_1A_HURRICANE: 'Hurricane',",
    "t1poke3move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t1poke4move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke4move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke5move1": "DODRIO_MOVE_1B_DRILLPECK: 'Drill Peck',",
    "t1poke5move2": "DODRIO_MOVE_2B_JUMPKICK: 'Jump Kick',",
    "t1name": "Luminosity Gaming",
    "t1region": "NA",
    "t1player1": "Lutano",
    "t1player2": "JL",
    "t1player3": "otter",
    "t1player4": "Joey",
    "t1player5": "Overlord",
    "t2poke1": "Trevenant",
    "t2poke2": "Sylveon",
    "t2poke3": "Eldegoss",
    "t2poke4": "Garchomp",
    "t2poke5": "Greninja",
    "t2ban1": "Leafeon",
    "t2ban2": "Falinks",
    "t2poke1move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke2move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t2poke2move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t2poke3move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t2poke3move2": "ELDEGOSS_MOVE_2B_COTTONSPORE: 'Cotton Spore',",
    "t2poke4move1": "GARCHOMP_MOVE_1B_DRAGONRUSH: 'Dragon Rush',",
    "t2poke4move2": "GARCHOMP_MOVE_2B_DRAGONCLAW: 'Dragon Claw',",
    "t2poke5move1": "GRENINJA_MOVE_1A_DOUBLETEAM: 'Double Team',",
    "t2poke5move2": "GRENINJA_MOVE_2A_WATERSHURIKEN: 'Water Shuriken',",
    "t2name": "Ni Hao",
    "t2region": "NA",
    "t2player1": "Duskrunner5",
    "t2player2": "Victorin",
    "t2player3": "Kirtan",
    "t2player4": "bits",
    "t2player5": "Waterboy",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "5"
  },
  {
    "t1poke1": "Trevenant",
    "t1poke2": "Sylveon",
    "t1poke3": "Falinks",
    "t1poke4": "Hoopa",
    "t1poke5": "Crustle",
    "t1ban1": "Cramorant",
    "t1ban2": "Leafeon",
    "t1poke1move1": "TREVENANT_MOVE_1B_CURSE: 'Curse',",
    "t1poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t1poke2move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t1poke2move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t1poke3move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t1poke3move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t1poke4move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke4move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke5move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t1poke5move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t1name": "Orange Juicers",
    "t1region": "NA",
    "t1player1": "Machizzle",
    "t1player2": "Flareons",
    "t1player3": "Kraitos",
    "t1player4": "Rollin",
    "t1player5": "Machizzle",
    "t2poke1": "Blissey",
    "t2poke2": "Blaziken",
    "t2poke3": "Chandelure",
    "t2poke4": "Slowbro",
    "t2poke5": "Metagross",
    "t2ban1": "Umbreon",
    "t2ban2": "Tyranitar",
    "t2poke1move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke1move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke2move1": "BLAZIKEN_ALL_MOVES",
    "t2poke2move2": "BLAZIKEN_ALL_MOVES",
    "t2poke3move1": "CHANDELURE_MOVE_1A_FLAMETHROWER: 'Flamethrower',",
    "t2poke3move2": "CHANDELURE_MOVE_2B_IMPRISON: 'Imprison',",
    "t2poke4move1": "SLOWBRO_MOVE_1B_SURF: 'Surf',",
    "t2poke4move2": "SLOWBRO_MOVE_2A_AMNESIA: 'Amnesia',",
    "t2poke5move1": "METAGROSS_MOVE_1B_GYROBALL: 'Gyro Ball',",
    "t2poke5move2": "METAGROSS_MOVE_2B_MAGNETRISE: 'Magnet Rise',",
    "t2name": "Nemesis",
    "t2region": "NA",
    "t2player1": "Reckzz",
    "t2player2": "Trainer",
    "t2player3": "Yeat",
    "t2player4": "Aznable",
    "t2player5": "Metallic",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "6"
  },
  {
    "t1poke1": "Trevenant",
    "t1poke2": "Blissey",
    "t1poke3": "Crustle",
    "t1poke4": "Mew",
    "t1poke5": "Blaziken",
    "t1ban1": "Cramorant",
    "t1ban2": "Leafeon",
    "t1poke1move1": "TREVENANT_MOVE_1B_CURSE: 'Curse',",
    "t1poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t1poke2move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t1poke2move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t1poke3move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t1poke3move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t1poke4move1": "MEW_ALL_MOVES",
    "t1poke4move2": "MEW_ALL_MOVES",
    "t1poke5move1": "BLAZIKEN_ALL_MOVES",
    "t1poke5move2": "BLAZIKEN_ALL_MOVES",
    "t1name": "Orange Juicers",
    "t1region": "NA",
    "t1player1": "Machizzle",
    "t1player2": "Rollin",
    "t1player3": "zugrug",
    "t1player4": "Flareons",
    "t1player5": "Kraitos",
    "t2poke1": "Sylveon",
    "t2poke2": "Falinks",
    "t2poke3": "Blastoise",
    "t2poke4": "Hoopa",
    "t2poke5": "Glaceon",
    "t2ban1": "Umbreon",
    "t2ban2": "Tyranitar",
    "t2poke1move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t2poke1move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t2poke2move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t2poke2move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t2poke3move1": "BLASTOISE_MOVE_1A_HYDROPUMP: 'Hydro Pump',",
    "t2poke3move2": "BLASTOISE_MOVE_2A_SURF: 'Surf',",
    "t2poke4move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t2poke4move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t2poke5move1": "GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',",
    "t2poke5move2": "GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',",
    "t2name": "Nemesis",
    "t2region": "NA",
    "t2player1": "Yeat",
    "t2player2": "Metallic",
    "t2player3": "Aznable",
    "t2player4": "Reckzz",
    "t2player5": "Trainer",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "6"
  },
  {
    "t1poke1": "Trevenant",
    "t1poke2": "Mew",
    "t1poke3": "Hoopa",
    "t1poke4": "Lapras",
    "t1poke5": "Gardevoir",
    "t1ban1": "Cramorant",
    "t1ban2": "Leafeon",
    "t1poke1move1": "TREVENANT_MOVE_1B_CURSE: 'Curse',",
    "t1poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t1poke2move1": "MEW_ALL_MOVES",
    "t1poke2move2": "MEW_ALL_MOVES",
    "t1poke3move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke3move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke4move1": "LAPRAS_MOVE_1A_WATERPULSE: 'Water Pulse',",
    "t1poke4move2": "LAPRAS_MOVE_2A_BUBBLEBEAM: 'Bubble Beam',",
    "t1poke5move1": "GARDEVOIR_MOVE_1A_PSYCHIC: 'Psychic',",
    "t1poke5move2": "GARDEVOIR_MOVE_2A_PSYSHOCK: 'Psyshock',",
    "t1name": "Orange Juicers",
    "t1region": "NA",
    "t1player1": "Machizzle",
    "t1player2": "Flareons",
    "t1player3": "Rollin",
    "t1player4": "zugrug",
    "t1player5": "Kraitos",
    "t2poke1": "Crustle",
    "t2poke2": "Sylveon",
    "t2poke3": "Blissey",
    "t2poke4": "Glaceon",
    "t2poke5": "Gyarados",
    "t2ban1": "Umbreon",
    "t2ban2": "Falinks",
    "t2poke1move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t2poke1move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t2poke2move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t2poke2move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t2poke3move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke3move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke4move1": "GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',",
    "t2poke4move2": "GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',",
    "t2poke5move1": "GYARADOS_MOVE_1B_BOUNCE: 'Bounce',",
    "t2poke5move2": "GYARADOS_MOVE_2A_DRAGONBREATH: 'Dragon Breath',",
    "t2name": "Nemesis",
    "t2region": "NA",
    "t2player1": "Aznable",
    "t2player2": "Yeat",
    "t2player3": "Reckzz",
    "t2player4": "Trainer",
    "t2player5": "Metallic",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "6"
  },
  {
    "t1poke1": "Leafeon",
    "t1poke2": "Falinks",
    "t1poke3": "Mr_Mime",
    "t1poke4": "Cramorant",
    "t1poke5": "Clefable",
    "t1ban1": "Umbreon",
    "t1ban2": "Tyranitar",
    "t1poke1move1": "LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',",
    "t1poke1move2": "LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',",
    "t1poke2move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t1poke2move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t1poke3move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke3move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke4move1": "CRAMORANT_MOVE_1A_HURRICANE: 'Hurricane',",
    "t1poke4move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t1poke5move1": "CLEFABLE_MOVE_1A_MOONLIGHT: 'Moonlight',",
    "t1poke5move2": "CLEFABLE_MOVE_2A_GRAVITY: 'Gravity',",
    "t1name": "Luminosity Gaming",
    "t1region": "NA",
    "t1player1": "Overlord",
    "t1player2": "Lutano",
    "t1player3": "Joey",
    "t1player4": "otter",
    "t1player5": "JL",
    "t2poke1": "Dodrio",
    "t2poke2": "Blissey",
    "t2poke3": "Lucario",
    "t2poke4": "Trevenant",
    "t2poke5": "Sylveon",
    "t2ban1": "Hoopa",
    "t2ban2": "Comfey",
    "t2poke1move1": "DODRIO_MOVE_1A_TRIATTACK: 'Tri Attack',",
    "t2poke1move2": "DODRIO_MOVE_2B_JUMPKICK: 'Jump Kick',",
    "t2poke2move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke2move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke3move1": "LUCARIO_MOVE_1A_EXTREMESPEED: 'Extreme Speed',",
    "t2poke3move2": "LUCARIO_MOVE_2A_BONERUSH: 'Bone Rush',",
    "t2poke4move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke4move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke5move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t2poke5move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t2name": "Gee",
    "t2region": "NA",
    "t2player1": "Zel0ot",
    "t2player2": "EggN00b",
    "t2player3": "OGwastaken",
    "t2player4": "slash",
    "t2player5": "BlackCH",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "7"
  },
  {
    "t1poke1": "Leafeon",
    "t1poke2": "Mr_Mime",
    "t1poke3": "Sylveon",
    "t1poke4": "Clefable",
    "t1poke5": "Blaziken",
    "t1ban1": "Umbreon",
    "t1ban2": "Tyranitar",
    "t1poke1move1": "LEAFEON_MOVE_1B_SOLARBLADE: 'Solar Blade',",
    "t1poke1move2": "LEAFEON_MOVE_2B_LEAFBLADE: 'Leaf Blade',",
    "t1poke2move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke2move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke3move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t1poke3move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t1poke4move1": "CLEFABLE_MOVE_1A_MOONLIGHT: 'Moonlight',",
    "t1poke4move2": "CLEFABLE_MOVE_2A_GRAVITY: 'Gravity',",
    "t1poke5move1": "BLAZIKEN_ALL_MOVES",
    "t1poke5move2": "BLAZIKEN_ALL_MOVES",
    "t1name": "Luminosity Gaming",
    "t1region": "NA",
    "t1player1": "Overlord",
    "t1player2": "Joey",
    "t1player3": "otter",
    "t1player4": "JL",
    "t1player5": "Lutano",
    "t2poke1": "Falinks",
    "t2poke2": "Blissey",
    "t2poke3": "Cramorant",
    "t2poke4": "Trevenant",
    "t2poke5": "Meowscarada",
    "t2ban1": "Comfey",
    "t2ban2": "Dodrio",
    "t2poke1move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t2poke1move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t2poke2move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke2move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke3move1": "CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',",
    "t2poke3move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t2poke4move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke4move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke5move1": "MEOWSCARADA_MOVE_1A_FLOWERTRICK: 'Flower Trick',",
    "t2poke5move2": "MEOWSCARADA_MOVE_2A_DOUBLETEAM: 'Double Team',",
    "t2name": "Gee",
    "t2region": "NA",
    "t2player1": "OGwastaken",
    "t2player2": "EggN00b",
    "t2player3": "BlackCH",
    "t2player4": "slash",
    "t2player5": "Zel0ot",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "7"
  },
  {
    "t1poke1": "Tyranitar",
    "t1poke2": "Hoopa",
    "t1poke3": "Cramorant",
    "t1poke4": "Mr_Mime",
    "t1poke5": "Dodrio",
    "t1ban1": "Umbreon",
    "t1ban2": "Blissey",
    "t1poke1move1": "TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',",
    "t1poke1move2": "TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',",
    "t1poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke3move1": "CRAMORANT_MOVE_1A_HURRICANE: 'Hurricane',",
    "t1poke3move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t1poke4move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke4move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke5move1": "DODRIO_MOVE_1B_DRILLPECK: 'Drill Peck',",
    "t1poke5move2": "DODRIO_MOVE_2B_JUMPKICK: 'Jump Kick',",
    "t1name": "Luminosity Gaming",
    "t1region": "NA",
    "t1player1": "Lutano",
    "t1player2": "JL",
    "t1player3": "otter",
    "t1player4": "Joey",
    "t1player5": "Overlord",
    "t2poke1": "Leafeon",
    "t2poke2": "Trevenant",
    "t2poke3": "Buzzwole",
    "t2poke4": "Eldegoss",
    "t2poke5": "Sylveon",
    "t2ban1": "Comfey",
    "t2ban2": "Falinks",
    "t2poke1move1": "LEAFEON_MOVE_1B_SOLARBLADE: 'Solar Blade',",
    "t2poke1move2": "LEAFEON_MOVE_2B_LEAFBLADE: 'Leaf Blade',",
    "t2poke2move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke2move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke3move1": "BUZZWOLE_MOVE_1B_SUPERPOWER: 'Superpower',",
    "t2poke3move2": "BUZZWOLE_MOVE_2B_SMACKDOWN: 'Smack Down',",
    "t2poke4move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t2poke4move2": "ELDEGOSS_MOVE_2B_COTTONSPORE: 'Cotton Spore',",
    "t2poke5move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t2poke5move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t2name": "Gee",
    "t2region": "NA",
    "t2player1": "Zel0ot",
    "t2player2": "slash",
    "t2player3": "OGwastaken",
    "t2player4": "EggN00b",
    "t2player5": "BlackCH",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "7"
  },
  {
    "t1poke1": "Umbreon",
    "t1poke2": "Hoopa",
    "t1poke3": "Sylveon",
    "t1poke4": "Glaceon",
    "t1poke5": "Gyarados",
    "t1ban1": "Trevenant",
    "t1ban2": "Tyranitar",
    "t1poke1move1": "UMBREON_MOVE_1A_MEANLOOK: 'Mean Look',",
    "t1poke1move2": "UMBREON_MOVE_2A_WISH: 'Wish',",
    "t1poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke3move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t1poke3move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t1poke4move1": "GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',",
    "t1poke4move2": "GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',",
    "t1poke5move1": "GYARADOS_MOVE_1B_BOUNCE: 'Bounce',",
    "t1poke5move2": "GYARADOS_MOVE_2A_DRAGONBREATH: 'Dragon Breath',",
    "t1name": "Nemesis",
    "t1region": "NA",
    "t1player1": "Aznable",
    "t1player2": "Reckzz",
    "t1player3": "Yeat",
    "t1player4": "Trainer",
    "t1player5": "Metallic",
    "t2poke1": "Blissey",
    "t2poke2": "Cramorant",
    "t2poke3": "Blaziken",
    "t2poke4": "Mr_Mime",
    "t2poke5": "Mimikyu",
    "t2ban1": "Leafeon",
    "t2ban2": "Falinks",
    "t2poke1move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke1move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke2move1": "CRAMORANT_MOVE_1A_HURRICANE: 'Hurricane',",
    "t2poke2move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t2poke3move1": "BLAZIKEN_ALL_MOVES",
    "t2poke3move2": "BLAZIKEN_ALL_MOVES",
    "t2poke4move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t2poke4move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t2poke5move1": "MIMIKYU_MOVE_1B_SHADOWCLAW: 'Shadow Claw',",
    "t2poke5move2": "MIMIKYU_MOVE_2A_SHADOWSNEAK: 'Shadow Sneak',",
    "t2name": "Luminosity Gaming",
    "t2region": "NA",
    "t2player1": "JL",
    "t2player2": "otter",
    "t2player3": "Overlord",
    "t2player4": "Joey",
    "t2player5": "Lutano",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "8"
  },
  {
    "t1poke1": "Leafeon",
    "t1poke2": "Mr_Mime",
    "t1poke3": "Cramorant",
    "t1poke4": "Clefable",
    "t1poke5": "Venusaur",
    "t1ban1": "Umbreon",
    "t1ban2": "Blissey",
    "t1poke1move1": "LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',",
    "t1poke1move2": "LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',",
    "t1poke2move1": "MRMIME_MOVE_1A_CONFUSION: 'Confusion',",
    "t1poke2move2": "MRMIME_MOVE_2A_BARRIER: 'Barrier',",
    "t1poke3move1": "CRAMORANT_MOVE_1A_HURRICANE: 'Hurricane',",
    "t1poke3move2": "CRAMORANT_MOVE_2B_DIVE: 'Dive',",
    "t1poke4move1": "CLEFABLE_MOVE_1A_MOONLIGHT: 'Moonlight',",
    "t1poke4move2": "CLEFABLE_MOVE_2A_GRAVITY: 'Gravity',",
    "t1poke5move1": "VENUSAUR_MOVE_1B_GIGADRAIN: 'Giga Drain',",
    "t1poke5move2": "VENUSAUR_MOVE_2B_PETALDANCE: 'Petal Dance',",
    "t1name": "Luminosity Gaming",
    "t1region": "NA",
    "t1player1": "Overlord",
    "t1player2": "Joey",
    "t1player3": "otter",
    "t1player4": "JL",
    "t1player5": "Lutano",
    "t2poke1": "Hoopa",
    "t2poke2": "Falinks",
    "t2poke3": "Sylveon",
    "t2poke4": "Slowbro",
    "t2poke5": "Glaceon",
    "t2ban1": "Trevenant",
    "t2ban2": "Tyranitar",
    "t2poke1move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t2poke1move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t2poke2move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t2poke2move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t2poke3move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t2poke3move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t2poke4move1": "SLOWBRO_MOVE_1B_SURF: 'Surf',",
    "t2poke4move2": "SLOWBRO_MOVE_2A_AMNESIA: 'Amnesia',",
    "t2poke5move1": "GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',",
    "t2poke5move2": "GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',",
    "t2name": "Nemesis",
    "t2region": "NA",
    "t2player1": "Reckzz",
    "t2player2": "Metallic",
    "t2player3": "Yeat",
    "t2player4": "Aznable",
    "t2player5": "Trainer",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "8"
  },
  {
    "t1poke1": "Trevenant",
    "t1poke2": "Mew",
    "t1poke3": "Hoopa",
    "t1poke4": "Buzzwole",
    "t1poke5": "Dodrio",
    "t1ban1": "Cramorant",
    "t1ban2": "Leafeon",
    "t1poke1move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t1poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t1poke2move1": "MEW_ALL_MOVES",
    "t1poke2move2": "MEW_ALL_MOVES",
    "t1poke3move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke3move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke4move1": "BUZZWOLE_MOVE_1B_SUPERPOWER: 'Superpower',",
    "t1poke4move2": "BUZZWOLE_MOVE_2B_SMACKDOWN: 'Smack Down',",
    "t1poke5move1": "DODRIO_MOVE_1A_TRIATTACK: 'Tri Attack',",
    "t1poke5move2": "DODRIO_MOVE_2B_JUMPKICK: 'Jump Kick',",
    "t1name": "Orange Juicers",
    "t1region": "NA",
    "t1player1": "zugrug",
    "t1player2": "Flareons",
    "t1player3": "Rollin",
    "t1player4": "Machizzle",
    "t1player5": "Kraitos",
    "t2poke1": "Crustle",
    "t2poke2": "Sylveon",
    "t2poke3": "Blaziken",
    "t2poke4": "Zoroark",
    "t2poke5": "Sableye",
    "t2ban1": "Umbreon",
    "t2ban2": "Falinks",
    "t2poke1move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t2poke1move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t2poke2move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t2poke2move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t2poke3move1": "BLAZIKEN_ALL_MOVES",
    "t2poke3move2": "BLAZIKEN_ALL_MOVES",
    "t2poke4move1": "ZOROARK_MOVE_1B_FEINTATTACK: 'Feint Attack',",
    "t2poke4move2": "ZOROARK_MOVE_2A_SHADOWCLAW: 'Shadow Claw',",
    "t2poke5move1": "SABLEYE_MOVE_1A_KNOCKOFF: 'Knock Off',",
    "t2poke5move2": "SABLEYE_MOVE_2B_CONFUSERAY: 'Confuse Ray',",
    "t2name": "Nemesis",
    "t2region": "NA",
    "t2player1": "Aznable",
    "t2player2": "Yeat",
    "t2player3": "Metallic",
    "t2player4": "Trainer",
    "t2player5": "Reckzz",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "9"
  },
  {
    "t1poke1": "Trevenant",
    "t1poke2": "Hoopa",
    "t1poke3": "Blaziken",
    "t1poke4": "Mew",
    "t1poke5": "Slowbro",
    "t1ban1": "Cramorant",
    "t1ban2": "Leafeon",
    "t1poke1move1": "TREVENANT_MOVE_1B_CURSE: 'Curse',",
    "t1poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t1poke2move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke2move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke3move1": "BLAZIKEN_ALL_MOVES",
    "t1poke3move2": "BLAZIKEN_ALL_MOVES",
    "t1poke4move1": "MEW_ALL_MOVES",
    "t1poke4move2": "MEW_ALL_MOVES",
    "t1poke5move1": "SLOWBRO_MOVE_1A_SCALD: 'Scald',",
    "t1poke5move2": "SLOWBRO_MOVE_2A_AMNESIA: 'Amnesia',",
    "t1name": "Orange Juicers",
    "t1region": "NA",
    "t1player1": "Machizzle",
    "t1player2": "Rollin",
    "t1player3": "Kraitos",
    "t1player4": "Flareons",
    "t1player5": "zugrug",
    "t2poke1": "Crustle",
    "t2poke2": "Sylveon",
    "t2poke3": "Comfey",
    "t2poke4": "Zoroark",
    "t2poke5": "Tyranitar",
    "t2ban1": "Umbreon",
    "t2ban2": "Falinks",
    "t2poke1move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t2poke1move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t2poke2move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t2poke2move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t2poke3move1": "COMFEY_MOVE_1A_FLORALHEALING: 'Floral Healing',",
    "t2poke3move2": "COMFEY_MOVE_2B_GRASSKNOT: 'Grass Knot',",
    "t2poke4move1": "ZOROARK_MOVE_1B_FEINTATTACK: 'Feint Attack',",
    "t2poke4move2": "ZOROARK_MOVE_2A_SHADOWCLAW: 'Shadow Claw',",
    "t2poke5move1": "TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',",
    "t2poke5move2": "TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',",
    "t2name": "Nemesis",
    "t2region": "NA",
    "t2player1": "Aznable",
    "t2player2": "Yeat",
    "t2player3": "Reckzz",
    "t2player4": "Trainer",
    "t2player5": "Metallic",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "9"
  },
  {
    "t1poke1": "Leafeon",
    "t1poke2": "Crustle",
    "t1poke3": "Inteleon",
    "t1poke4": "Gyarados",
    "t1poke5": "Hoopa",
    "t1ban1": "Umbreon",
    "t1ban2": "Metagross",
    "t1poke1move1": "LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',",
    "t1poke1move2": "LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',",
    "t1poke2move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t1poke2move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t1poke3move1": "INTELEON_MOVE_1A_FELLSTINGER: 'Fell Stinger',",
    "t1poke3move2": "INTELEON_MOVE_2A_SNIPESHOT: 'Snipe Shot',",
    "t1poke4move1": "GYARADOS_MOVE_1B_BOUNCE: 'Bounce',",
    "t1poke4move2": "GYARADOS_MOVE_2A_DRAGONBREATH: 'Dragon Breath',",
    "t1poke5move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke5move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1name": "Nemesis",
    "t1region": "NA",
    "t1player1": "Trainer",
    "t1player2": "Aznable",
    "t1player3": "Yeat",
    "t1player4": "Metallic",
    "t1player5": "Reckzz",
    "t2poke1": "Sylveon",
    "t2poke2": "Trevenant",
    "t2poke3": "Blaziken",
    "t2poke4": "Blissey",
    "t2poke5": "Dodrio",
    "t2ban1": "Cramorant",
    "t2ban2": "Falinks",
    "t2poke1move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t2poke1move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t2poke2move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke2move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke3move1": "BLAZIKEN_ALL_MOVES",
    "t2poke3move2": "BLAZIKEN_ALL_MOVES",
    "t2poke4move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke4move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke5move1": "DODRIO_MOVE_1B_DRILLPECK: 'Drill Peck',",
    "t2poke5move2": "DODRIO_MOVE_2B_JUMPKICK: 'Jump Kick',",
    "t2name": "Orange Juicers",
    "t2region": "NA",
    "t2player1": "Flareons",
    "t2player2": "zugrug",
    "t2player3": "Machizzle",
    "t2player4": "Rollin",
    "t2player5": "Kraitos",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "9"
  },
  {
    "t1poke1": "Trevenant",
    "t1poke2": "Gyarados",
    "t1poke3": "Hoopa",
    "t1poke4": "Chandelure",
    "t1poke5": "Blaziken",
    "t1ban1": "Cramorant",
    "t1ban2": "Leafeon",
    "t1poke1move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t1poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t1poke2move1": "GYARADOS_MOVE_1B_BOUNCE: 'Bounce',",
    "t1poke2move2": "GYARADOS_MOVE_2A_DRAGONBREATH: 'Dragon Breath',",
    "t1poke3move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke3move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1poke4move1": "CHANDELURE_MOVE_1B_OVERHEAT: 'Overheat',",
    "t1poke4move2": "CHANDELURE_MOVE_2B_IMPRISON: 'Imprison',",
    "t1poke5move1": "BLAZIKEN_ALL_MOVES",
    "t1poke5move2": "BLAZIKEN_ALL_MOVES",
    "t1name": "Orange Juicers",
    "t1region": "NA",
    "t1player1": "zugrug",
    "t1player2": "Machizzle",
    "t1player3": "Rollin",
    "t1player4": "Flareons",
    "t1player5": "Kraitos",
    "t2poke1": "Crustle",
    "t2poke2": "Sylveon",
    "t2poke3": "Eldegoss",
    "t2poke4": "Mimikyu",
    "t2poke5": "Tsareena",
    "t2ban1": "Umbreon",
    "t2ban2": "Falinks",
    "t2poke1move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t2poke1move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t2poke2move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t2poke2move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t2poke3move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t2poke3move2": "ELDEGOSS_MOVE_2A_COTTONGUARD: 'Cotton Guard',",
    "t2poke4move1": "MIMIKYU_MOVE_1B_SHADOWCLAW: 'Shadow Claw',",
    "t2poke4move2": "MIMIKYU_MOVE_2A_SHADOWSNEAK: 'Shadow Sneak',",
    "t2poke5move1": "TSAREENA_MOVE_1B_STOMP: 'Stomp',",
    "t2poke5move2": "TSAREENA_MOVE_2B_GRASSYGLIDE: 'Grassy Glide',",
    "t2name": "Nemesis",
    "t2region": "NA",
    "t2player1": "Aznable",
    "t2player2": "Yeat",
    "t2player3": "Reckzz",
    "t2player4": "Trainer",
    "t2player5": "Metallic",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "9"
  },
  {
    "t1poke1": "Sylveon",
    "t1poke2": "Blissey",
    "t1poke3": "Snorlax",
    "t1poke4": "Garchomp",
    "t1poke5": "Mew",
    "t1ban1": "Cramorant",
    "t1ban2": "Crustle",
    "t1poke1move1": "SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',",
    "t1poke1move2": "SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',",
    "t1poke2move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t1poke2move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t1poke3move1": "SNORLAX_MOVE_1A_HEAVYSLAM: 'Heavy Slam',",
    "t1poke3move2": "SNORLAX_MOVE_2A_BLOCK: 'Block',",
    "t1poke4move1": "GARCHOMP_MOVE_1B_DRAGONRUSH: 'Dragon Rush',",
    "t1poke4move2": "GARCHOMP_MOVE_2B_DRAGONCLAW: 'Dragon Claw',",
    "t1poke5move1": "MEW_ALL_MOVES",
    "t1poke5move2": "MEW_ALL_MOVES",
    "t1name": "Orange Juicers",
    "t1region": "NA",
    "t1player1": "Kraitos",
    "t1player2": "Rollin",
    "t1player3": "zugrug",
    "t1player4": "Machizzle",
    "t1player5": "Flareons",
    "t2poke1": "Trevenant",
    "t2poke2": "Leafeon",
    "t2poke3": "Inteleon",
    "t2poke4": "Eldegoss",
    "t2poke5": "Gyarados",
    "t2ban1": "Umbreon",
    "t2ban2": "Falinks",
    "t2poke1move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke1move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke2move1": "LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',",
    "t2poke2move2": "LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',",
    "t2poke3move1": "INTELEON_MOVE_1A_FELLSTINGER: 'Fell Stinger',",
    "t2poke3move2": "INTELEON_MOVE_2A_SNIPESHOT: 'Snipe Shot',",
    "t2poke4move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t2poke4move2": "ELDEGOSS_MOVE_2A_COTTONGUARD: 'Cotton Guard',",
    "t2poke5move1": "GYARADOS_MOVE_1B_BOUNCE: 'Bounce',",
    "t2poke5move2": "GYARADOS_MOVE_2A_DRAGONBREATH: 'Dragon Breath',",
    "t2name": "Nemesis",
    "t2region": "NA",
    "t2player1": "Aznable",
    "t2player2": "Trainer",
    "t2player3": "Yeat",
    "t2player4": "Reckzz",
    "t2player5": "Metallic",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "10"
  },
  {
    "t1poke1": "Falinks",
    "t1poke2": "Crustle",
    "t1poke3": "Venusaur",
    "t1poke4": "Glaceon",
    "t1poke5": "Hoopa",
    "t1ban1": "Umbreon",
    "t1ban2": "Sylveon",
    "t1poke1move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t1poke1move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t1poke2move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t1poke2move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t1poke3move1": "VENUSAUR_MOVE_1B_GIGADRAIN: 'Giga Drain',",
    "t1poke3move2": "VENUSAUR_MOVE_2A_SOLARBEAM: 'Solarbeam',",
    "t1poke4move1": "GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',",
    "t1poke4move2": "GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',",
    "t1poke5move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t1poke5move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t1name": "Nemesis",
    "t1region": "NA",
    "t1player1": "Metallic",
    "t1player2": "Aznable",
    "t1player3": "Yeat",
    "t1player4": "Trainer",
    "t1player5": "Reckzz",
    "t2poke1": "Blissey",
    "t2poke2": "Trevenant",
    "t2poke3": "Mew",
    "t2poke4": "Garchomp",
    "t2poke5": "Tyranitar",
    "t2ban1": "Cramorant",
    "t2ban2": "Leafeon",
    "t2poke1move1": "BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',",
    "t2poke1move2": "BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',",
    "t2poke2move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke2move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke3move1": "MEW_ALL_MOVES",
    "t2poke3move2": "MEW_ALL_MOVES",
    "t2poke4move1": "GARCHOMP_MOVE_1B_DRAGONRUSH: 'Dragon Rush',",
    "t2poke4move2": "GARCHOMP_MOVE_2B_DRAGONCLAW: 'Dragon Claw',",
    "t2poke5move1": "TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',",
    "t2poke5move2": "TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',",
    "t2name": "Orange Juicers",
    "t2region": "NA",
    "t2player1": "Rollin",
    "t2player2": "zugrug",
    "t2player3": "Flareons",
    "t2player4": "Machizzle",
    "t2player5": "Kraitos",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "10"
  },
  {
    "t1poke1": "Falinks",
    "t1poke2": "Crustle",
    "t1poke3": "Venusaur",
    "t1poke4": "Glaceon",
    "t1poke5": "Eldegoss",
    "t1ban1": "Umbreon",
    "t1ban2": "Blissey",
    "t1poke1move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t1poke1move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t1poke2move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t1poke2move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t1poke3move1": "VENUSAUR_MOVE_1B_GIGADRAIN: 'Giga Drain',",
    "t1poke3move2": "VENUSAUR_MOVE_2A_SOLARBEAM: 'Solarbeam',",
    "t1poke4move1": "GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',",
    "t1poke4move2": "GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',",
    "t1poke5move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t1poke5move2": "ELDEGOSS_MOVE_2A_COTTONGUARD: 'Cotton Guard',",
    "t1name": "Nemesis",
    "t1region": "NA",
    "t1player1": "Metallic",
    "t1player2": "Aznable",
    "t1player3": "Yeat",
    "t1player4": "Trainer",
    "t1player5": "Reckzz",
    "t2poke1": "Hoopa",
    "t2poke2": "Trevenant",
    "t2poke3": "Sylveon",
    "t2poke4": "Tyranitar",
    "t2poke5": "Garchomp",
    "t2ban1": "Cramorant",
    "t2ban2": "Leafeon",
    "t2poke1move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t2poke1move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t2poke2move1": "TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',",
    "t2poke2move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke3move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t2poke3move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t2poke4move1": "TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',",
    "t2poke4move2": "TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',",
    "t2poke5move1": "GARCHOMP_MOVE_1B_DRAGONRUSH: 'Dragon Rush',",
    "t2poke5move2": "GARCHOMP_MOVE_2B_DRAGONCLAW: 'Dragon Claw',",
    "t2name": "Orange Juicers",
    "t2region": "NA",
    "t2player1": "Rollin",
    "t2player2": "zugrug",
    "t2player3": "Flareons",
    "t2player4": "Kraitos",
    "t2player5": "Machizzle",
    "firstPick": "Team1",
    "winningTeam": 1,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "10"
  },
  {
    "t1poke1": "Falinks",
    "t1poke2": "Crustle",
    "t1poke3": "Venusaur",
    "t1poke4": "Glaceon",
    "t1poke5": "Eldegoss",
    "t1ban1": "Umbreon",
    "t1ban2": "Blissey",
    "t1poke1move1": "FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',",
    "t1poke1move2": "FALINKS_MOVE_2A_NORETREAT: 'No Retreat',",
    "t1poke2move1": "CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',",
    "t1poke2move2": "CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',",
    "t1poke3move1": "VENUSAUR_MOVE_1B_GIGADRAIN: 'Giga Drain',",
    "t1poke3move2": "VENUSAUR_MOVE_2A_SOLARBEAM: 'Solarbeam',",
    "t1poke4move1": "GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',",
    "t1poke4move2": "GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',",
    "t1poke5move1": "ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',",
    "t1poke5move2": "ELDEGOSS_MOVE_2A_COTTONGUARD: 'Cotton Guard',",
    "t1name": "Nemesis",
    "t1region": "NA",
    "t1player1": "Metallic",
    "t1player2": "Aznable",
    "t1player3": "Yeat",
    "t1player4": "Trainer",
    "t1player5": "Reckzz",
    "t2poke1": "Hoopa",
    "t2poke2": "Trevenant",
    "t2poke3": "Sylveon",
    "t2poke4": "Tyranitar",
    "t2poke5": "Lapras",
    "t2ban1": "Cramorant",
    "t2ban2": "Leafeon",
    "t2poke1move1": "HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',",
    "t2poke1move2": "HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',",
    "t2poke2move1": "TREVENANT_MOVE_1B_CURSE: 'Curse',",
    "t2poke2move2": "TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',",
    "t2poke3move1": "SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',",
    "t2poke3move2": "SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',",
    "t2poke4move1": "TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',",
    "t2poke4move2": "TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',",
    "t2poke5move1": "LAPRAS_MOVE_1A_WATERPULSE: 'Water Pulse',",
    "t2poke5move2": "LAPRAS_MOVE_2A_BUBBLEBEAM: 'Bubble Beam',",
    "t2name": "Orange Juicers",
    "t2region": "NA",
    "t2player1": "Rollin",
    "t2player2": "Machizzle",
    "t2player3": "Flareons",
    "t2player4": "Kraitos",
    "t2player5": "zugrug",
    "firstPick": "Team1",
    "winningTeam": 2,
    "event": "NAIC 2024 Day 1",
    "matchDate": "06/07/2024",
    "vodUrl": "",
    "set": "10"
  }
];

module.exports = compsData;