const pokemonData = [
  {
    "Name": "Cinderace",
    "EarlyGame": "Weak",
    "MidGame": "Weak",
    "LateGame": "Strong",
    "Mobility": "High",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Consistent",
    "DamageAffect": "SingleTarget",
    "CC": "None",
    "PlayStyle": "Teamfight",
    "Classification": "ADC",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "BlazeKick",
    "AssumedMove2": "FlameCharge"
  },
  {
    "Name": "Garchomp",
    "EarlyGame": "Medium",
    "MidGame": "Weak",
    "LateGame": "Strong",
    "Mobility": "Medium",
    "Range": "None",
    "Bulk": "Medium",
    "Damage": "High",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "DragonRush",
    "AssumedMove2": "DragonClaw"
  },
  {
    "Name": "Gengar",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "SingleTarget",
    "CC": "Low",
    "PlayStyle": "Poke",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "None",
    "AssumedMove1": "DreamEater",
    "AssumedMove2": "ShadowBall"
  },
  {
    "Name": "Cramorant",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "UtilityMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "Hurricane",
    "AssumedMove2": "Dive"
  },
  {
    "Name": "Alolan-Ninetales",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "UtilityMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "Avalanche",
    "AssumedMove2": "Blizzard"
  },
  {
    "Name": "Wigglytuff",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "Buffer",
    "Class": "Supporter",
    "OtherAttr": "AntiCC",
    "AssumedMove1": "Sing",
    "AssumedMove2": "DazzlingGleam"
  },
  {
    "Name": "Machamp",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "None",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "SplitMap",
    "Classification": "Engage",
    "Class": "AllRounder",
    "OtherAttr": "AntiCC",
    "AssumedMove1": "Submission",
    "AssumedMove2": "CloseCombat"
  },
  {
    "Name": "Absol",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Weak",
    "Mobility": "High",
    "Range": "None",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "SingleTarget",
    "CC": "None",
    "PlayStyle": "SplitMap",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "None",
    "AssumedMove1": "Pursuit",
    "AssumedMove2": "PsychoCut"
  },
  {
    "Name": "Slowbro",
    "EarlyGame": "Medium",
    "MidGame": "Weak",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "MediumAOE",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "CCTank",
    "Class": "Defender",
    "OtherAttr": "Lockdown",
    "AssumedMove1": "Surf",
    "AssumedMove2": "Amnesia"
  },
  {
    "Name": "Mr-Mime",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "Engage",
    "Class": "Supporter",
    "OtherAttr": "SpaceControl",
    "AssumedMove1": "Confusion",
    "AssumedMove2": "Barrier"
  },
  {
    "Name": "Venusaur",
    "EarlyGame": "Weak",
    "MidGame": "Weak",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "High",
    "Bulk": "Medium",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "LargeAOE",
    "CC": "None",
    "PlayStyle": "Teamfight",
    "Classification": "BurstMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "GigaDrain",
    "AssumedMove2": "Solarbeam"
  },
  {
    "Name": "Lucario",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SingleTarget",
    "CC": "Low",
    "PlayStyle": "SplitMap",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "AntiCC",
    "AssumedMove1": "PowerUpPunch",
    "AssumedMove2": "CloseCombat"
  },
  {
    "Name": "Talonflame",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Low",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "None",
    "PlayStyle": "SplitMap",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "None",
    "AssumedMove1": "AerialAce",
    "AssumedMove2": "BraveBird"
  },
  {
    "Name": "Eldegoss",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "SingleTarget",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Healer",
    "Class": "Supporter",
    "OtherAttr": "Heals",
    "AssumedMove1": "PollenPuff",
    "AssumedMove2": "CottonGuard"
  },
  {
    "Name": "Greninja",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "Smokescreen",
    "AssumedMove2": "Surf"
  },
  {
    "Name": "Crustle",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "None",
    "Bulk": "High",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "Engage",
    "Class": "Defender",
    "OtherAttr": "SpaceControl",
    "AssumedMove1": "RockTomb",
    "AssumedMove2": "XScissor"
  },
  {
    "Name": "Snorlax",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "Engage",
    "Class": "Defender",
    "OtherAttr": "Peel",
    "AssumedMove1": "HeavySlam",
    "AssumedMove2": "Block"
  },
  {
    "Name": "Charizard",
    "EarlyGame": "Weak",
    "MidGame": "Weak",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Dive",
    "Classification": "Engage",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "Flamethrower",
    "AssumedMove2": "FireBlast"
  },
  {
    "Name": "Pikachu",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "UtilityMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "ElectroBall",
    "AssumedMove2": "VoltTackle"
  },
  {
    "Name": "Zeraora",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Low",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "None",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "None",
    "AssumedMove1": "VoltSwitch",
    "AssumedMove2": "Discharge"
  },
  {
    "Name": "Gardevoir",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "BurstMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "Psyshock",
    "AssumedMove2": "Psychic"
  },
  {
    "Name": "Blissey",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Buffer",
    "Class": "Supporter",
    "OtherAttr": "Heals",
    "AssumedMove1": "SoftBoiled",
    "AssumedMove2": "EggBomb"
  },
  {
    "Name": "Blastoise",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "LargeAOE",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "Engage",
    "Class": "Defender",
    "OtherAttr": "Peel",
    "AssumedMove1": "HydroPump",
    "AssumedMove2": "Surf"
  },
  {
    "Name": "Mamoswine",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Weak",
    "Mobility": "Low",
    "Range": "None",
    "Bulk": "High",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "CCTank",
    "Class": "Defender",
    "OtherAttr": "Lockdown",
    "AssumedMove1": "IceFang",
    "AssumedMove2": "Earthquake"
  },
  {
    "Name": "Sylveon",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SingleTarget",
    "CC": "None",
    "PlayStyle": "Teamfight",
    "Classification": "DrainTank",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "MyticalFire",
    "AssumedMove2": "DrainingKiss"
  },
  {
    "Name": "Greedent",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "SplitMap",
    "Classification": "Engage",
    "Class": "Defender",
    "OtherAttr": "AntiCC",
    "AssumedMove1": "Covet",
    "AssumedMove2": "Belch"
  },
  {
    "Name": "Decidueye",
    "EarlyGame": "Medium",
    "MidGame": "Weak",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "High",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "None",
    "PlayStyle": "Poke",
    "Classification": "ADC",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "SpiritShackle",
    "AssumedMove2": "ShadowSneak"
  },
  {
    "Name": "Tsareena",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "High",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Dive",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "Lockdown",
    "AssumedMove1": "TripleAxel",
    "AssumedMove2": "TropKick"
  },
  {
    "Name": "Dragonite",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Medium",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "ADC",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "DragonDance",
    "AssumedMove2": "HyperBeam"
  },
  {
    "Name": "Trevenant",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "LargeAOE",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "CCTank",
    "Class": "Defender",
    "OtherAttr": "None",
    "AssumedMove1": "WoodHammer",
    "AssumedMove2": "HornLeech"
  },
  {
    "Name": "Aegislash",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "SacredSword",
    "AssumedMove2": "WideGuard"
  },
  {
    "Name": "Hoopa",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Low",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "LargeAOE",
    "CC": "Medium",
    "PlayStyle": "Assist",
    "Classification": "Healer",
    "Class": "Supporter",
    "OtherAttr": "Peel",
    "AssumedMove1": "HyperspaceHole",
    "AssumedMove2": "PhantomForce"
  },
  {
    "Name": "Duraludon",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Teamfight",
    "Classification": "ADC",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "FlashCannon",
    "AssumedMove2": "StealthRocks"
  },
  {
    "Name": "Azumarill",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Weak",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SingleTarget",
    "CC": "Low",
    "PlayStyle": "SplitMap",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "Whirlpool",
    "AssumedMove2": "Playrough"
  },
  {
    "Name": "Espeon",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "BurstMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "Psyshock",
    "AssumedMove2": "Psybeam"
  },
  {
    "Name": "Delphox",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "LargeAOE",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "UtilityMage",
    "Class": "Attacker",
    "OtherAttr": "SpaceControl",
    "AssumedMove1": "FireBlast",
    "AssumedMove2": "FireSpin"
  },
  {
    "Name": "Glaceon",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "Low",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Teamfight",
    "Classification": "ADC",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "IcicleSpear",
    "AssumedMove2": "IceShard"
  },
  {
    "Name": "Buzzwole",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SingleTarget",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "Superpower",
    "AssumedMove2": "SmackDown"
  },
  {
    "Name": "Tyranitar",
    "EarlyGame": "Weak",
    "MidGame": "Weak",
    "LateGame": "Strong",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "High",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "StoneEdge",
    "AssumedMove2": "SandTomb"
  },
  {
    "Name": "Mew",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Weak",
    "Mobility": "High",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Assist",
    "Classification": "UtilityMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "None",
    "AssumedMove2": "None"
  },
  {
    "Name": "Dodrio",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Low",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SingleTarget",
    "CC": "Low",
    "PlayStyle": "SplitMap",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "TriAttack",
    "AssumedMove2": "Agility"
  },
  {
    "Name": "Scizor",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "BulletPunch",
    "AssumedMove2": "SwordsDance"
  },
  {
    "Name": "Scyther",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "None",
    "AssumedMove1": "DualWingbeat",
    "AssumedMove2": "SwordsDance"
  },
  {
    "Name": "Clefable",
    "EarlyGame": "Medium",
    "MidGame": "Weak",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "None",
    "Bulk": "Low",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "Healer",
    "Class": "Supporter",
    "OtherAttr": "SpaceControl",
    "AssumedMove1": "Moonlight",
    "AssumedMove2": "Gravity"
  },
  {
    "Name": "Zoroark",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Low",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "None",
    "AssumedMove1": "FeintAttack",
    "AssumedMove2": "ShadowClaw"
  },
  {
    "Name": "Sableye",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Weak",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Low",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "High",
    "PlayStyle": "SplitMap",
    "Classification": "Engage",
    "Class": "Supporter",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "KnockOff",
    "AssumedMove2": "ConfuseRay"
  },
  {
    "Name": "Urshifu-SS",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Strong",
    "Mobility": "Medium",
    "Range": "None",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Engage",
    "Class": "AllRounder",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "WickedBlow",
    "AssumedMove2": "ThroatChop"
  },
  {
    "Name": "Urshifu-RS",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "High",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "AllRounder",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "SurgingStrikes",
    "AssumedMove2": "Liquidation"
  },
  {
    "Name": "Dragapult",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "Medium",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Teamfight",
    "Classification": "ADC",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "PhantomForce",
    "AssumedMove2": "ShadowBall"
  },
  {
    "Name": "Comfey",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Low",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "High",
    "PlayStyle": "Dive",
    "Classification": "Healer",
    "Class": "Supporter",
    "OtherAttr": "None",
    "AssumedMove1": "SweetKiss",
    "AssumedMove2": "GrassKnot"
  },
  {
    "Name": "Zacian",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Weak",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Engage",
    "Class": "AllRounder",
    "OtherAttr": "Peel",
    "AssumedMove1": "SacredSword",
    "AssumedMove2": "Agility"
  },
  {
    "Name": "Goodra",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "Defender",
    "OtherAttr": "None",
    "AssumedMove1": "MuddyWater",
    "AssumedMove2": "AcidSpray"
  },
  {
    "Name": "Lapras",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "MediumAOE",
    "CC": "Medium",
    "PlayStyle": "SplitMap",
    "Classification": "DrainTank",
    "Class": "Defender",
    "OtherAttr": "None",
    "AssumedMove1": "WaterPulse",
    "AssumedMove2": "BubbleBeam"
  },
  {
    "Name": "Chandelure",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "BurstMage",
    "Class": "Attacker",
    "OtherAttr": "SpaceControl",
    "AssumedMove1": "Flamethrower",
    "AssumedMove2": "Imprison"
  },
  {
    "Name": "Umbreon",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "SingleTarget",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "Buffer",
    "Class": "Defender",
    "OtherAttr": "Lockdown",
    "AssumedMove1": "MeanLook",
    "AssumedMove2": "Wish"
  },
  {
    "Name": "Leafeon",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Low",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "RazorLeaf",
    "AssumedMove2": "AerialAce"
  },
  {
    "Name": "Inteleon",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "Low",
    "Range": "High",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "SingleTarget",
    "CC": "None",
    "PlayStyle": "Poke",
    "Classification": "BurstMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "FellStinger",
    "AssumedMove2": "SnipeShot"
  },
  {
    "Name": "Mewtwo-Y",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "High",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "ADC",
    "Class": "Attacker",
    "OtherAttr": "Peel",
    "AssumedMove1": "FutureSight",
    "AssumedMove2": "Teleport"
  },
  {
    "Name": "Mewtwo-X",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "High",
    "PlayStyle": "SplitMap",
    "Classification": "Engage",
    "Class": "AllRounder",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "FutureSight",
    "AssumedMove2": "Recover"
  },
  {
    "Name": "Blaziken",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "MediumAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "None",
    "AssumedMove2": "None"
  },
  {
    "Name": "Mimikyu",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Medium",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "AllRounder",
    "OtherAttr": "Lockdown",
    "AssumedMove1": "ShadowClaw",
    "AssumedMove2": "ShadowSneak"
  },
  {
    "Name": "Meowscarada",
    "EarlyGame": "Strong",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "None",
    "AssumedMove1": "FlowerTrick",
    "AssumedMove2": "DoubleTeam"
  },
  {
    "Name": "Metagross",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Strong",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "GyroBall",
    "AssumedMove2": "ZenHeadbutt"
  },
  {
    "Name": "Gyarados",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Strong",
    "Mobility": "Medium",
    "Range": "Medium",
    "Bulk": "Medium",
    "Damage": "High",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Medium",
    "PlayStyle": "Dive",
    "Classification": "Engage",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "DragonBreath",
    "AssumedMove2": "Waterfall"
  },
  {
    "Name": "Miraidon",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "High",
    "Bulk": "Low",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "MediumAOE",
    "CC": "None",
    "PlayStyle": "Teamfight",
    "Classification": "BurstMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "ChargeBeam",
    "AssumedMove2": "Thunder"
  },
  {
    "Name": "Falinks",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "IronHead",
    "AssumedMove2": "BeatUp"
  },
  {
    "Name": "Ceruledge",
    "EarlyGame": "Weak",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "Dive",
    "Classification": "Assassin",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "PsychoCut",
    "AssumedMove2": "PhantomForce"
  },
  {
    "Name": "Ho-Oh",
    "EarlyGame": "Medium",
    "MidGame": "Weak",
    "LateGame": "Strong",
    "Mobility": "Medium",
    "Range": "Low",
    "Bulk": "High",
    "Damage": "Medium",
    "DamageType": "Consistent",
    "DamageAffect": "SmallAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "DrainTank",
    "Class": "Defender",
    "OtherAttr": "None",
    "AssumedMove1": "SacredFire",
    "AssumedMove2": "FireSpin"
  },
  {
    "Name": "Armarouge",
    "EarlyGame": "Weak",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Low",
    "PlayStyle": "Teamfight",
    "Classification": "BurstMage",
    "Class": "Attacker",
    "OtherAttr": "None",
    "AssumedMove1": "ArmorCannon",
    "AssumedMove2": "Psyshock"
  },
  {
    "Name": "Darkrai",
    "EarlyGame": "Medium",
    "MidGame": "Strong",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "High",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "High",
    "PlayStyle": "SplitMap",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "Lockdown",
    "AssumedMove1": "DarkVoid",
    "AssumedMove2": "NastyPlot"
  },
  {
    "Name": "Psyduck",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Medium",
    "Bulk": "Low",
    "Damage": "Low",
    "DamageType": "Consistent",
    "DamageAffect": "MediumAOE",
    "CC": "High",
    "PlayStyle": "Teamfight",
    "Classification": "Engage",
    "Class": "Supporter",
    "OtherAttr": "None",
    "AssumedMove1": "Surf",
    "AssumedMove2": "Psychic"
  },
  {
    "Name": "Tinkaton",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "Low",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "Bruiser",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "GigatonHammer",
    "AssumedMove2": "Thief"
  },
  {
    "Name": "Galarian-Rapidash",
    "EarlyGame": "Medium",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "High",
    "Range": "Low",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "SmallAOE",
    "CC": "None",
    "PlayStyle": "SplitMap",
    "Classification": "Assassin",
    "Class": "Speedster",
    "OtherAttr": "PickFinding",
    "AssumedMove1": "DazzlingGleam",
    "AssumedMove2": "Agility"
  },
  {
    "Name": "Suicune",
    "EarlyGame": "Strong",
    "MidGame": "Medium",
    "LateGame": "Medium",
    "Mobility": "None",
    "Range": "Medium",
    "Bulk": "Medium",
    "Damage": "Medium",
    "DamageType": "Burst",
    "DamageAffect": "MediumAOE",
    "CC": "Medium",
    "PlayStyle": "Teamfight",
    "Classification": "UtilityMage",
    "Class": "AllRounder",
    "OtherAttr": "None",
    "AssumedMove1": "Whirlpool",
    "AssumedMove2": "IceBeam"
  }
];

module.exports = pokemonData;