-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.comps_comp_id_seq;

CREATE SEQUENCE public.comps_comp_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.events_event_id_seq;

CREATE SEQUENCE public.events_event_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.matches_match_id_seq;

CREATE SEQUENCE public.matches_match_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.professional_players_player_id_seq;

CREATE SEQUENCE public.professional_players_player_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.professional_sets_set_id_seq;

CREATE SEQUENCE public.professional_sets_set_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.professional_teams_team_id_seq;

CREATE SEQUENCE public.professional_teams_team_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.playable_characters definition

-- Drop table

-- DROP TABLE public.playable_characters;

CREATE TABLE public.playable_characters (
	pokemon_id int4 NOT NULL,
	pokemon_name text NOT NULL,
	pokemon_class text NOT NULL,
	pokedex_number int4 NOT NULL,
	release_date date NOT NULL,
	CONSTRAINT playable_characters_pkey PRIMARY KEY (pokemon_id)
);


-- public.pro_events definition

-- Drop table

-- DROP TABLE public.pro_events;

CREATE TABLE public.pro_events (
	event_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	event_name text NOT NULL,
	event_date date NOT NULL,
	CONSTRAINT events_pkey PRIMARY KEY (event_id)
);


-- public.pro_players definition

-- Drop table

-- DROP TABLE public.pro_players;

CREATE TABLE public.pro_players (
	player_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	player_name text NOT NULL,
	other_names text NULL,
	CONSTRAINT professional_players_pkey PRIMARY KEY (player_id)
);


-- public.pro_teams definition

-- Drop table

-- DROP TABLE public.pro_teams;

CREATE TABLE public.pro_teams (
	team_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	team_name text NOT NULL,
	team_region text NOT NULL,
	CONSTRAINT professional_teams_pkey PRIMARY KEY (team_id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	user_google_id text NOT NULL,
	user_name text NOT NULL,
	user_email text NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (user_google_id)
);


-- public.pokemon_attributes definition

-- Drop table

-- DROP TABLE public.pokemon_attributes;

CREATE TABLE public.pokemon_attributes (
	pokemon_id int4 NOT NULL,
	early_game text NOT NULL,
	mid_game text NOT NULL,
	late_game text NOT NULL,
	mobility text NOT NULL,
	"range" text NOT NULL,
	bulk text NOT NULL,
	damage text NOT NULL,
	damage_type text NOT NULL,
	damage_affect text NOT NULL,
	cc text NOT NULL,
	play_style text NOT NULL,
	classification text NOT NULL,
	other_attr text NOT NULL,
	can_exp_share text NOT NULL,
	can_top_lane_carry text NOT NULL,
	can_jungle_carry text NOT NULL,
	can_bottom_lane_carry text NOT NULL,
	best_lane text NOT NULL,
	assumed_move_1 text NOT NULL,
	assumed_move_2 text NOT NULL,
	early_spike int2 NOT NULL,
	ult_level int2 NOT NULL,
	key_spike int2 NOT NULL,
	"6_30_to_4" int2 NOT NULL,
	laning_phase int2 NOT NULL,
	"8_50_to_7_30" int2 NOT NULL,
	"7_30_to_6_30" int2 NOT NULL,
	"4_to_end" int2 NOT NULL,
	CONSTRAINT pokemon_attributes_pkey PRIMARY KEY (pokemon_id),
	CONSTRAINT pokemon_attributes_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id)
);


-- public.pokemon_insights definition

-- Drop table

-- DROP TABLE public.pokemon_insights;

CREATE TABLE public.pokemon_insights (
	pokemon_id int8 NOT NULL,
	"text" text NULL,
	match_title text NULL,
	match_link text NULL,
	CONSTRAINT pokemon_insights_pkey PRIMARY KEY (pokemon_id),
	CONSTRAINT pokemon_insights_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id)
);


-- public.pokemon_moves definition

-- Drop table

-- DROP TABLE public.pokemon_moves;

CREATE TABLE public.pokemon_moves (
	move_id int4 NOT NULL,
	move_name text NOT NULL,
	pokemon_id int4 NOT NULL,
	CONSTRAINT pokemon_moves_pkey PRIMARY KEY (move_id),
	CONSTRAINT pokemon_moves_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id)
);


-- public.pro_comps definition

-- Drop table

-- DROP TABLE public.pro_comps;

CREATE TABLE public.pro_comps (
	comp_id int4 DEFAULT nextval('comps_comp_id_seq'::regclass) NOT NULL,
	did_win bool NOT NULL,
	first_pick bool NOT NULL,
	team_id int4 NOT NULL,
	CONSTRAINT comps_pkey PRIMARY KEY (comp_id),
	CONSTRAINT comps_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.pro_teams(team_id)
);


-- public.pro_performance definition

-- Drop table

-- DROP TABLE public.pro_performance;

CREATE TABLE public.pro_performance (
	comp_id int4 NOT NULL,
	pokemon_id int4 NOT NULL,
	kills int4 NOT NULL,
	assists int4 NOT NULL,
	damage_dealt int4 NOT NULL,
	damage_taken int4 NOT NULL,
	damage_healed int4 NOT NULL,
	points_scored int2 NOT NULL,
	CONSTRAINT pokemon_performance_pkey PRIMARY KEY (comp_id, pokemon_id),
	CONSTRAINT pokemon_performance_comp_id_fkey FOREIGN KEY (comp_id) REFERENCES public.pro_comps(comp_id),
	CONSTRAINT pokemon_performance_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id)
);


-- public.pro_picks definition

-- Drop table

-- DROP TABLE public.pro_picks;

CREATE TABLE public.pro_picks (
	comp_id int4 NOT NULL,
	pokemon_id int4 NOT NULL,
	pick_position int4 NOT NULL,
	player_id int4 NOT NULL,
	position_played text NULL,
	move_1_id int4 NOT NULL,
	move_2_id int4 NOT NULL,
	CONSTRAINT pro_picks_pkey PRIMARY KEY (comp_id, pokemon_id),
	CONSTRAINT picks_comp_id_fkey FOREIGN KEY (comp_id) REFERENCES public.pro_comps(comp_id),
	CONSTRAINT picks_move_1_id_fkey FOREIGN KEY (move_1_id) REFERENCES public.pokemon_moves(move_id),
	CONSTRAINT picks_move_2_id_fkey FOREIGN KEY (move_2_id) REFERENCES public.pokemon_moves(move_id),
	CONSTRAINT picks_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.pro_players(player_id),
	CONSTRAINT picks_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id)
);


-- public.pro_sets definition

-- Drop table

-- DROP TABLE public.pro_sets;

CREATE TABLE public.pro_sets (
	set_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	event_id int4 NOT NULL,
	set_descriptor text NOT NULL,
	CONSTRAINT professional_sets_pkey PRIMARY KEY (set_id),
	CONSTRAINT professional_sets_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.pro_events(event_id)
);


-- public.tier_list definition

-- Drop table

-- DROP TABLE public.tier_list;

CREATE TABLE public.tier_list (
	tier_name text NOT NULL,
	pokemon_id int4 NOT NULL,
	CONSTRAINT tier_list_pkey PRIMARY KEY (pokemon_id),
	CONSTRAINT tier_list_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id)
);


-- public.verified_users definition

-- Drop table

-- DROP TABLE public.verified_users;

CREATE TABLE public.verified_users (
	user_google_id text NOT NULL,
	CONSTRAINT verified_users_pkey PRIMARY KEY (user_google_id),
	CONSTRAINT verified_users_user_google_id_fkey FOREIGN KEY (user_google_id) REFERENCES public.users(user_google_id)
);


-- public.pro_bans definition

-- Drop table

-- DROP TABLE public.pro_bans;

CREATE TABLE public.pro_bans (
	comp_id int4 NOT NULL,
	pokemon_id int4 NOT NULL,
	ban_position int4 NOT NULL,
	CONSTRAINT pro_bans_pkey PRIMARY KEY (comp_id, pokemon_id),
	CONSTRAINT bans_comp_id_fkey FOREIGN KEY (comp_id) REFERENCES public.pro_comps(comp_id),
	CONSTRAINT bans_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id)
);


-- public.pro_matches definition

-- Drop table

-- DROP TABLE public.pro_matches;

CREATE TABLE public.pro_matches (
	match_id int4 DEFAULT nextval('matches_match_id_seq'::regclass) NOT NULL,
	set_id int4 NOT NULL,
	comp_1_id int4 NOT NULL,
	comp_2_id int4 NOT NULL,
	vod_url text NOT NULL,
	CONSTRAINT matches_pkey PRIMARY KEY (match_id),
	CONSTRAINT matches_comp_1_id_fkey FOREIGN KEY (comp_1_id) REFERENCES public.pro_comps(comp_id),
	CONSTRAINT matches_comp_2_id_fkey FOREIGN KEY (comp_2_id) REFERENCES public.pro_comps(comp_id),
	CONSTRAINT matches_set_id_fkey FOREIGN KEY (set_id) REFERENCES public.pro_sets(set_id)
);