// All the basic naming conventions of things. Keeping as const cause naming conventions may change. For example: Alolan Ninetales could be A-Ninetales, Alolan_Ninetales, etc
// Also just makes it easier to prevent typos and just change stuff as needed.

// Pokemon
const constants = {
    CINDERACE_NAME: 'Cinderace',
    GARCHOMP_NAME: 'Garchomp',
    GENGAR_NAME: 'Gengar',
    CRAMORANT_NAME: 'Cramorant',
    ALOLANNINETALES_NAME: 'Alolan-Ninetales',
    WIGGLYTUFF_NAME: 'Wigglytuff',
    MACHAMP_NAME: 'Machamp',
    ABSOL_NAME: 'Absol',
    SLOWBRO_NAME: 'Slowbro',
    MRMIME_NAME: 'Mr-Mime',
    VENUSAUR_NAME: 'Venusaur',
    LUCARIO_NAME: 'Lucario',
    TALONFLAME_NAME: 'Talonflame',
    ELDEGOSS_NAME: 'Eldegoss',
    GRENINJA_NAME: 'Greninja',
    CRUSTLE_NAME: 'Crustle',
    SNORLAX_NAME: 'Snorlax',
    CHARIZARD_NAME: 'Charizard',
    PIKACHU_NAME: 'Pikachu',
    ZERAORA_NAME: 'Zeraora',
    GARDEVOIR_NAME: 'Gardevoir',
    BLISSEY_NAME: 'Blissey',
    BLASTOISE_NAME: 'Blastoise',
    MAMOSWINE_NAME: 'Mamoswine',
    SYLVEON_NAME: 'Sylveon',
    GREEDENT_NAME: 'Greedent',
    DECIDUEYE_NAME: 'Decidueye',
    TSAREENA_NAME: 'Tsareena',
    DRAGONITE_NAME: 'Dragonite',
    TREVENANT_NAME: 'Trevenant',
    AEGISLASH_NAME: 'Aegislash',
    HOOPA_NAME: 'Hoopa',
    DURALUDON_NAME: 'Duraludon',
    AZUMARILL_NAME: 'Azumarill',
    ESPEON_NAME: 'Espeon',
    DELPHOX_NAME: 'Delphox',
    GLACEON_NAME: 'Glaceon',
    BUZZWOLE_NAME: 'Buzzwole',
    TYRANITAR_NAME: 'Tyranitar',
    MEW_NAME: 'Mew',
    DODRIO_NAME: 'Dodrio',
    SCIZOR_NAME: 'Scizor',
    SCYTHER_NAME: 'Scyther',
    CLEFABLE_NAME: 'Clefable',
    ZOROARK_NAME: 'Zoroark',
    SABLEYE_NAME: 'Sableye',
    URSHIFUSS_NAME: 'Urshifu-SS', // Single-Strike (Red)
    URSHIFURS_NAME: 'Urshifu-RS', // Rapid-Strike (Blue)
    DRAGAPULT_NAME: 'Dragapult',
    COMFEY_NAME: 'Comfey',
    ZACIAN_NAME: 'Zacian',
    GOODRA_NAME: 'Goodra',
    LAPRAS_NAME: 'Lapras',
    CHANDELURE_NAME: 'Chandelure',
    UMBREON_NAME: 'Umbreon',
    LEAFEON_NAME: 'Leafeon',
    INTELEON_NAME: 'Inteleon',
    MEWTWOY_NAME: 'Mewtwo-Y',
    MEWTWOX_NAME: 'Mewtwo-X',
    BLAZIKEN_NAME: 'Blaziken',
    MIMIKYU_NAME: 'Mimikyu',
    MEOWSCARADA_NAME: 'Meowscarada',
    METAGROSS_NAME: 'Metagross',
    GYARADOS_NAME: 'Gyarados',
    MIRAIDON_NAME: 'Miraidon',
    FALINKS_NAME: 'Falinks',
    

    // Roles
    ATTACKER: 'Attacker',
    DEFENDER: 'Defender',
    ALL_ROUNDER: 'All-Rounder',
    SPEEDSTER: 'Speedster',
    SUPPORTER: 'Supporter',

    //// Attributes
    //// Split into good and bad attributes. Try to mimic the good attributes of known comps and minimize the bad attributes or cancel out the bad attributes.
    // General Attributes
    GOOD_LANE: 'Good Laner',
    GOOD_JUNGLER: 'Good Jungler',
    STRONG_EARLY: 'Strong Early Game',
    STRONG_MIDDLE: 'Strong Mid Game',
    STRONG_LATE: 'Strong Late Game',
    MEELE: 'Melee',
    LOW_RANGE: 'Low Range',
    MID_RANGE: 'Mid Range',
    LONG_RANGE: 'Long Range',
    SUSCEPTIBLE_TO_INVADES: 'Susceptible To Invades', // Things like Kubfu that struggle to do their first clear quickly
    SPLITS_JUNGLE: 'Splits Jungle', // Things like eldegoss that like to take red buff and help speed up the jungler's first clear
    FULL_SPLIT_JUNGLE: 'Full Split Jungler', // Things like two eevees that can each take half of the jungle or really anything that spikes at level 4.

    HIGH_MOBILITY: 'Very Mobile',
    ADC: 'ADC',
    GOOD_SCORING: 'Good Scoring',
    GROUP_HEALING: 'Group Healing',
    GOOD_SUSTAIN: 'Good Sustain',
    SINGLE_TARGET_HEALING: 'Single Target Healing',
    HEAVY_SHIELDS: 'Heavy Shields',
    TRUE_DAMAGE: 'True Damage',
    GIVES_UNSTOPPABLE: 'Gives Unstoppable',
    HAS_UNSTOPPABLE: 'Has Unstoppable',
    GROUP_CC: 'Group CC',
    SINGLE_CC: 'Single Target CC',
    SNOWBALL: 'Snowballs',
    SOLO_CARRY: 'Solo Carry',
    BURST_DAMAGE: 'Burst Damage',
    TEAMFIGHTER: 'Good Teamfight',
    GOOD_1V1: 'Good Duelist',
    FINDS_PICKS: 'Forces Picks',
    GOOD_BACKCAP: 'Good Backcapper',
    FAST_RIP: 'Fast Rip',
}

module.exports = constants;