// All the basic naming conventions of things. Keeping as const cause naming conventions may change. For example: Alolan Ninetales could be A_Ninetales, Alolan_Ninetales, etc
// Also just makes it easier to prevent typos and just change stuff as needed.

// Pokemon
export const NAME_CONSTANTS = {
    CINDERACE_NAME: 'Cinderace',
    GARCHOMP_NAME: 'Garchomp',
    GENGAR_NAME: 'Gengar',
    CRAMORANT_NAME: 'Cramorant', 
    ALOLANNINETALES_NAME: 'Alolan_Ninetales',
    WIGGLYTUFF_NAME: 'Wigglytuff',
    MACHAMP_NAME: 'Machamp', 
    ABSOL_NAME: 'Absol',
    SLOWBRO_NAME: 'Slowbro',
    MRMIME_NAME: 'Mr_Mime', 
    VENUSAUR_NAME: 'Venusaur', 
    LUCARIO_NAME: 'Lucario',
    TALONFLAME_NAME: 'Talonflame',
    ELDEGOSS_NAME: 'Eldegoss', 
    GRENINJA_NAME: 'Greninja', 
    CRUSTLE_NAME: 'Crustle',
    SNORLAX_NAME: 'Snorlax', 
    CHARIZARD_NAME: 'Charizard', 
    PIKACHU_NAME: 'Pikachu', 
    ZERAORA_NAME: 'Zeraora', 
    GARDEVOIR_NAME: 'Gardevoir',
    BLISSEY_NAME: 'Blissey', 
    BLASTOISE_NAME: 'Blastoise', 
    MAMOSWINE_NAME: 'Mamoswine', 
    SYLVEON_NAME: 'Sylveon', 
    GREEDENT_NAME: 'Greedent', 
    DECIDUEYE_NAME: 'Decidueye', 
    TSAREENA_NAME: 'Tsareena', 
    DRAGONITE_NAME: 'Dragonite', 
    TREVENANT_NAME: 'Trevenant',
    AEGISLASH_NAME: 'Aegislash', 
    HOOPA_NAME: 'Hoopa', 
    DURALUDON_NAME: 'Duraludon',
    AZUMARILL_NAME: 'Azumarill',
    ESPEON_NAME: 'Espeon',
    DELPHOX_NAME: 'Delphox', 
    GLACEON_NAME: 'Glaceon', 
    BUZZWOLE_NAME: 'Buzzwole', 
    TYRANITAR_NAME: 'Tyranitar',
    MEW_NAME: 'Mew',
    DODRIO_NAME: 'Dodrio',
    SCIZOR_NAME: 'Scizor',
    SCYTHER_NAME: 'Scyther',
    CLEFABLE_NAME: 'Clefable',
    ZOROARK_NAME: 'Zoroark',
    SABLEYE_NAME: 'Sableye',
    URSHIFUSS_NAME: 'Urshifu_SS', // Single_Strike (Red)
    URSHIFURS_NAME: 'Urshifu_RS', // Rapid_Strike (Blue)
    DRAGAPULT_NAME: 'Dragapult',
    COMFEY_NAME: 'Comfey',
    ZACIAN_NAME: 'Zacian',
    GOODRA_NAME: 'Goodra',
    LAPRAS_NAME: 'Lapras',
    CHANDELURE_NAME: 'Chandelure',
    UMBREON_NAME: 'Umbreon',
    LEAFEON_NAME: 'Leafeon',
    INTELEON_NAME: 'Inteleon',
    MEWTWOY_NAME: 'Mewtwo_Y',
    MEWTWOX_NAME: 'Mewtwo_X',
    BLAZIKEN_NAME: 'Blaziken',
    MIMIKYU_NAME: 'Mimikyu',
    MEOWSCARADA_NAME: 'Meowscarada',
    METAGROSS_NAME: 'Metagross',
    GYARADOS_NAME: 'Gyarados',
    MIRAIDON_NAME: 'Miraidon',
    FALINKS_NAME: 'Falinks',
    CERULEDGE_NAME: 'Ceruledge',
    HOOH_NAME: 'Ho_Oh',
    ARMAROUGE_NAME: 'Armarouge',
    DARKRAI_NAME: 'Darkrai',
    PSYDUCK_NAME: 'Psyduck',
    TINKATON_NAME: 'Tinkaton',
    GALARIANRAPIDASH_NAME: 'Galarian_Rapidash',
    SUICUNE_NAME: 'Suicune',
}

export const MOVE_CONSTANTS = {
    // Moves
    CINDERACE_MOVE_1A_PYROBALL: 'Pyro Ball',
    CINDERACE_MOVE_1B_BLAZEKICK: 'Blaze Kick',
    CINDERACE_MOVE_2A_FLAMECHARGE: 'Flame Charge',
    CINDERACE_MOVE_2B_FEINT: 'Feint',
    GARCHOMP_MOVE_1A_DIG: 'Dig',
    GARCHOMP_MOVE_1B_DRAGONRUSH: 'Dragon Rush',
    GARCHOMP_MOVE_2A_EARTHQUAKE: 'Earthquake',
    GARCHOMP_MOVE_2B_DRAGONCLAW: 'Dragon Claw',
    GENGAR_MOVE_1A_DREAMEATER: 'Dream Eater',
    GENGAR_MOVE_1B_HEX: 'Hex',
    GENGAR_MOVE_2A_SHADOWBALL: 'Shadow Ball',
    GENGAR_MOVE_2B_SLUDGEBOMB: 'Sludge Bomb',
    CRAMORANT_MOVE_1A_HURRICANE: 'Hurricane',
    CRAMORANT_MOVE_1B_AIRSLASH: 'Air Slash',
    CRAMORANT_MOVE_2A_SURF: 'Surf',
    CRAMORANT_MOVE_2B_DIVE: 'Dive',
    ALOLANNINETALES_MOVE_1A_AVALANCHE: 'Avalanche',
    ALOLANNINETALES_MOVE_1B_DAZZLINGGLEAM: 'Dazzling Gleam',
    ALOLANNINETALES_MOVE_2A_BLIZZARD: 'Blizzard',
    ALOLANNINETALES_MOVE_2B_AURORAVEIL: 'Aurora Veil',
    WIGGLYTUFF_MOVE_1A_DOUBLESLAP: 'Double Slap',
    WIGGLYTUFF_MOVE_1B_DAZZLINGGLEAM: 'Dazzling Gleam',
    WIGGLYTUFF_MOVE_2A_ROLLOUT: 'Rollout',
    WIGGLYTUFF_MOVE_2B_SING: 'Sing',
    MACHAMP_MOVE_1A_DYNAMICPUNCH: 'Dynamic Punch',
    MACHAMP_MOVE_1B_SUBMISSION: 'Submission',
    MACHAMP_MOVE_2A_CLOSECOMBAT: 'Close Combat',
    MACHAMP_MOVE_2B_CROSSCHOP: 'Cross Chop',
    ABSOL_MOVE_1A_NIGHTSLASH: 'Night Slash',
    ABSOL_MOVE_1B_PURSUIT: 'Pursuit',
    ABSOL_MOVE_2A_PSYCHOCUT: 'Psycho Cut',
    ABSOL_MOVE_2B_SUCKERPUNCH: 'Sucker Punch',
    SLOWBRO_MOVE_1A_SCALD: 'Scald',
    SLOWBRO_MOVE_1B_SURF: 'Surf',
    SLOWBRO_MOVE_2A_AMNESIA: 'Amnesia',
    SLOWBRO_MOVE_2B_TELEKINESIS: 'Telekinesis',
    MRMIME_MOVE_1A_CONFUSION: 'Confusion',
    MRMIME_MOVE_1B_PSYCHIC: 'Psychic',
    MRMIME_MOVE_2A_BARRIER: 'Barrier',
    MRMIME_MOVE_2B_POWERSWAP: 'Power Swap',
    VENUSAUR_MOVE_1A_SLUDGEBOMB: 'Sludge Bomb',
    VENUSAUR_MOVE_1B_GIGADRAIN: 'Giga Drain',
    VENUSAUR_MOVE_2A_SOLARBEAM: 'Solarbeam',
    VENUSAUR_MOVE_2B_PETALDANCE: 'Petal Dance',
    LUCARIO_MOVE_1A_EXTREMESPEED: 'Extreme Speed',
    LUCARIO_MOVE_1B_POWERUPPUNCH: 'Power-Up Punch',
    LUCARIO_MOVE_2A_BONERUSH: 'Bone Rush',
    LUCARIO_MOVE_2B_CLOSECOMBAT: 'Close Combat',
    TALONFLAME_MOVE_1A_FLAMECHARGE: 'Flame Charge',
    TALONFLAME_MOVE_1B_AERIALACE: 'Aerial Ace',
    TALONFLAME_MOVE_2A_FLY: 'Fly',
    TALONFLAME_MOVE_2B_BRAVEBIRD: 'Brave Bird',
    ELDEGOSS_MOVE_1A_POLLENPUFF: 'Pollen Puff',
    ELDEGOSS_MOVE_1B_LEAFTORNADO: 'Leaf Tornado',
    ELDEGOSS_MOVE_2A_COTTONGUARD: 'Cotton Guard',
    ELDEGOSS_MOVE_2B_COTTONSPORE: 'Cotton Spore',
    GRENINJA_MOVE_1A_DOUBLETEAM: 'Double Team',
    GRENINJA_MOVE_1B_SMOKESCREEN: 'Smokescreen',
    GRENINJA_MOVE_2A_WATERSHURIKEN: 'Water Shuriken',
    GRENINJA_MOVE_2B_SURF: 'Surf',
    CRUSTLE_MOVE_1A_ROCKTOMB: 'Rock Tomb',
    CRUSTLE_MOVE_1B_SHELLSMASH: 'Shell Smash',
    CRUSTLE_MOVE_2A_STEALTHROCK: 'Stealth Rock',
    CRUSTLE_MOVE_2B_XSCISSOR: 'X-Scissor',
    SNORLAX_MOVE_1A_HEAVYSLAM: 'Heavy Slam',
    SNORLAX_MOVE_1B_FLAIL: 'Flail',
    SNORLAX_MOVE_2A_BLOCK: 'Block',
    SNORLAX_MOVE_2B_YAWN: 'Yawn',
    CHARIZARD_MOVE_1A_FLAMETHROWER: 'Flamethrower',
    CHARIZARD_MOVE_1B_FIREPUNCH: 'Fire Punch',
    CHARIZARD_MOVE_2A_FIREBLAST: 'Fire Blast',
    CHARIZARD_MOVE_2B_FLAREBLITZ: 'Flare Blitz',
    PIKACHU_MOVE_1A_ELECTROBALL: 'Electro Ball',
    PIKACHU_MOVE_1B_THUNDER: 'Thunder',
    PIKACHU_MOVE_2A_VOLTTACKLE: 'Volt Tackle',
    PIKACHU_MOVE_2B_THUNDERBOLT: 'Thunderbolt',
    ZERAORA_MOVE_1A_VOLTSWITCH: 'Volt Switch',
    ZERAORA_MOVE_1B_SPARK: 'Spark',
    ZERAORA_MOVE_2A_DISCHARGE: 'Discharge',
    ZERAORA_MOVE_2B_WILDCHARGE: 'Wild Charge',
    GARDEVOIR_MOVE_1A_PSYCHIC: 'Psychic',
    GARDEVOIR_MOVE_1B_MOONBLAST: 'Moonblast',
    GARDEVOIR_MOVE_2A_PSYSHOCK: 'Psyshock',
    GARDEVOIR_MOVE_2B_FUTURESIGHT: 'Future Sight',
    BLISSEY_MOVE_1A_SOFTBOILED: 'Soft-Boiled',
    BLISSEY_MOVE_1B_SAFEGUARD: 'Safeguard',
    BLISSEY_MOVE_2A_EGGBOMB: 'Egg Bomb',
    BLISSEY_MOVE_2B_HELPINGHAND: 'Helping Hand',
    BLASTOISE_MOVE_1A_HYDROPUMP: 'Hydro Pump',
    BLASTOISE_MOVE_1B_WATERSPOUT: 'Water Spout',
    BLASTOISE_MOVE_2A_SURF: 'Surf',
    BLASTOISE_MOVE_2B_RAPIDSPIN: 'Rapid Spin',
    MAMOSWINE_MOVE_1A_ICICLECRASH: 'Icicle Crash',
    MAMOSWINE_MOVE_1B_ICEFANG: 'Ice Fang',
    MAMOSWINE_MOVE_2A_HIGHHORSEPOWER: 'High Horsepower',
    MAMOSWINE_MOVE_2B_EARTHQUAKE: 'Earthquake',
    SYLVEON_MOVE_1A_MYSTICALFIRE: 'Mystical Fire',
    SYLVEON_MOVE_1B_HYPERVOICE: 'Hyper Voice',
    SYLVEON_MOVE_2A_DRAININGKISS: 'Draining Kiss',
    SYLVEON_MOVE_2B_CALMMIND: 'Calm Mind',
    GREEDENT_MOVE_1A_STUFFCHEEKS: 'Stuff Cheeks',
    GREEDENT_MOVE_1B_COVET: 'Covet',
    GREEDENT_MOVE_2A_BULLETSEED: 'Bullet Seed',
    GREEDENT_MOVE_2B_BELCH: 'Belch',
    DECIDUEYE_MOVE_1A_RAZORLEAF: 'Razor Leaf',
    DECIDUEYE_MOVE_1B_SPIRITSHACKLE: 'Spirit Shackle',
    DECIDUEYE_MOVE_2A_LEAFSTORM: 'Leaf Storm',
    DECIDUEYE_MOVE_2B_SHADOWSNEAK: 'Shadow Sneak',
    TSAREENA_MOVE_1A_TRIPLEAXEL: 'Triple Axel',
    TSAREENA_MOVE_1B_STOMP: 'Stomp',
    TSAREENA_MOVE_2A_TROPKICK: 'Trop Kick',
    TSAREENA_MOVE_2B_GRASSYGLIDE: 'Grassy Glide',
    DRAGONITE_MOVE_1A_DRAGONDANCE: 'Dragon Dance',
    DRAGONITE_MOVE_1B_EXTREMESPEED: 'Extreme Speed',
    DRAGONITE_MOVE_2A_HYPERBEAM: 'Hyper Beam',
    DRAGONITE_MOVE_2B_OUTRAGE: 'Outrage',
    TREVENANT_MOVE_1A_WOODHAMMER: 'Wood Hammer',
    TREVENANT_MOVE_1B_CURSE: 'Curse',
    TREVENANT_MOVE_2A_HORNLEECH: 'Horn Leech',
    TREVENANT_MOVE_2B_PAINSPLIT: 'Pain Split',
    AEGISLASH_MOVE_1A_SACREDSWORD: 'Sacred Sword',
    AEGISLASH_MOVE_1B_SHADOWCLAW: 'Shadow Claw',
    AEGISLASH_MOVE_2A_WIDEGUARD: 'Wide Guard',
    AEGISLASH_MOVE_2B_IRONHEAD: 'Iron Head',
    HOOPA_MOVE_1A_HYPERSPACEHOLE: 'Hyperspace Hole',
    HOOPA_MOVE_1B_TRICK: 'Trick',
    HOOPA_MOVE_2A_PHANTOMFORCE: 'Phantom Force',
    HOOPA_MOVE_2B_SHADOWBALL: 'Shadow Ball',
    DURALUDON_MOVE_1A_FLASHCANNON: 'Flash Cannon',
    DURALUDON_MOVE_1B_DRAGONPULSE: 'Dragon Pulse',
    DURALUDON_MOVE_2A_DRAGONTAIL: 'Dragon Tail',
    DURALUDON_MOVE_2B_STEALTHROCK: 'Stealth Rock',
    AZUMARILL_MOVE_1A_WHIRLPOOL: 'Whirlpool',
    AZUMARILL_MOVE_1B_AQUATAIL: 'Aqua Tail',
    AZUMARILL_MOVE_2A_PLAYROUGH: 'Play Rough',
    AZUMARILL_MOVE_2B_WATERPULSE: 'Water Pulse',
    ESPEON_MOVE_1A_PSYSHOCK: 'Psyshock',
    ESPEON_MOVE_1B_STOREDPOWER: 'Stored Power',
    ESPEON_MOVE_2A_PSYBEAM: 'Psybeam',
    ESPEON_MOVE_2B_FUTURESIGHT: 'Future Sight',
    DELPHOX_MOVE_1A_FIREBLAST: 'Fire Blast',
    DELPHOX_MOVE_1B_MYSTICALFIRE: 'Mystical Fire',
    DELPHOX_MOVE_2A_FIRESPIN: 'Fire Spin',
    DELPHOX_MOVE_2B_FLAMECHARGE: 'Flame Charge',
    GLACEON_MOVE_1A_ICICLESPEAR: 'Icicle Spear',
    GLACEON_MOVE_1B_ICYWIND: 'Icy Wind',
    GLACEON_MOVE_2A_ICESHARD: 'Ice Shard',
    GLACEON_MOVE_2B_FREEZEDRY: 'Freeze Dry',
    BUZZWOLE_MOVE_1A_LEECHLIFE: 'Leech Life',
    BUZZWOLE_MOVE_1B_SUPERPOWER: 'Superpower',
    BUZZWOLE_MOVE_2A_LUNGE: 'Lunge',
    BUZZWOLE_MOVE_2B_SMACKDOWN: 'Smack Down',
    TYRANITAR_MOVE_1A_DARKPULSE: 'Dark Pulse',
    TYRANITAR_MOVE_1B_STONEEDGE: 'Stone Edge',
    TYRANITAR_MOVE_2A_ANCIENTPOWER: 'Ancient Power',
    TYRANITAR_MOVE_2B_SANDTOMB: 'Sand Tomb',
    MEW_MOVE_1: 'Move 1',
    MEW_MOVE_2: 'Move 2',
    DODRIO_MOVE_1A_TRIATTACK: 'Tri Attack',
    DODRIO_MOVE_1B_DRILLPECK: 'Drill Peck',
    DODRIO_MOVE_2A_AGILITY: 'Agility',
    DODRIO_MOVE_2B_JUMPKICK: 'Jump Kick',
    SCIZOR_MOVE_1A_BULLETPUNCH: 'Bullet Punch',
    SCIZOR_MOVE_2A_DOUBLEHIT: 'Double Hit',
    SCIZOR_MOVE_2B_SWORDSDANCE: 'Swords Dance',
    SCYTHER_MOVE_1A_DUALWINGBEAT: 'Dual Wingbeat',
    SCYTHER_MOVE_2A_DOUBLEHIT: 'Double Hit',
    SCYTHER_MOVE_2B_SWORDSDANCE: 'Swords Dance',
    CLEFABLE_MOVE_1A_MOONLIGHT: 'Moonlight',
    CLEFABLE_MOVE_1B_DRAININGKISS: 'Draining Kiss',
    CLEFABLE_MOVE_2A_GRAVITY: 'Gravity',
    CLEFABLE_MOVE_2B_FOLLOWME: 'Follow Me',
    ZOROARK_MOVE_1A_NIGHTSLASH: 'Night Slash',
    ZOROARK_MOVE_1B_FEINTATTACK: 'Feint Attack',
    ZOROARK_MOVE_2A_SHADOWCLAW: 'Shadow Claw',
    ZOROARK_MOVE_2B_CUT: 'Cut',
    SABLEYE_MOVE_1A_KNOCKOFF: 'Knock Off',
    SABLEYE_MOVE_1B_SHADOWSNEAK: 'Shadow Sneak',
    SABLEYE_MOVE_2A_FEINTATTACK: 'Feint Attack',
    SABLEYE_MOVE_2B_CONFUSERAY: 'Confuse Ray',
    URSHIFUSS_MOVE_1A_WICKEDBLOW: 'Wicked Blow',
    URSHIFUSS_MOVE_2A_THROATCHOP: 'Throat Chop',
    URSHIFURS_MOVE_1A_SURGINGSTRIKES: 'Surging Strikes',
    URSHIFURS_MOVE_2A_LIQUIDATION: 'Liquidation',
    DRAGAPULT_MOVE_1A_DRAGONDANCE: 'Dragon Dance',
    DRAGAPULT_MOVE_1B_PHANTOMFORCE: 'Phantom Force',
    DRAGAPULT_MOVE_2A_DRAGONBREATH: 'Dragon Breath',
    DRAGAPULT_MOVE_2B_SHADOWBALL: 'Shadow Ball',
    COMFEY_MOVE_1A_FLORALHEALING: 'Floral Healing',
    COMFEY_MOVE_1B_SWEETKISS: 'Sweet Kiss',
    COMFEY_MOVE_2A_MAGICALLEAF: 'Magical Leaf',
    COMFEY_MOVE_2B_GRASSKNOT: 'Grass Knot',
    ZACIAN_MOVE_1A_METALCLAW: 'Metal Claw',
    ZACIAN_MOVE_1B_SACREDSWORD: 'Sacred Sword',
    ZACIAN_MOVE_2A_AGILITY: 'Agility',
    ZACIAN_MOVE_2B_PLAYROUGH: 'Play Rough',
    GOODRA_MOVE_1A_MUDDYWATER: 'Muddy Water',
    GOODRA_MOVE_1B_DRAGONPULSE: 'Dragon Pulse',
    GOODRA_MOVE_2A_POWERWHIP: 'Power Whip',
    GOODRA_MOVE_2B_ACIDSPRAY: 'Acid Spray',
    LAPRAS_MOVE_1A_WATERPULSE: 'Water Pulse',
    LAPRAS_MOVE_1B_PERISHSONG: 'Perish Song',
    LAPRAS_MOVE_2A_BUBBLEBEAM: 'Bubble Beam',
    LAPRAS_MOVE_2B_ICEBEAM: 'Ice Beam',
    CHANDELURE_MOVE_1A_FLAMETHROWER: 'Flamethrower',
    CHANDELURE_MOVE_1B_OVERHEAT: 'Overheat',
    CHANDELURE_MOVE_2A_POLTERGEIST: 'Poltergeist',
    CHANDELURE_MOVE_2B_IMPRISON: 'Imprison',
    UMBREON_MOVE_1A_MEANLOOK: 'Mean Look',
    UMBREON_MOVE_1B_FOULPLAY: 'Foul Play',
    UMBREON_MOVE_2A_WISH: 'Wish',
    UMBREON_MOVE_2B_SNARL: 'Snarl',
    LEAFEON_MOVE_1A_RAZORLEAF: 'Razor Leaf',
    LEAFEON_MOVE_1B_SOLARBLADE: 'Solar Blade',
    LEAFEON_MOVE_2A_AERIALACE: 'Aerial Ace',
    LEAFEON_MOVE_2B_LEAFBLADE: 'Leaf Blade',
    INTELEON_MOVE_1A_FELLSTINGER: 'Fell Stinger',
    INTELEON_MOVE_1B_ACROBATICS: 'Acrobatics',
    INTELEON_MOVE_2A_SNIPESHOT: 'Snipe Shot',
    INTELEON_MOVE_2B_LIQUIDATION: 'Liquidation',
    MEWTWOY_MOVE_1A_FUTURESIGHT: 'Future Sight',
    MEWTWOY_MOVE_1B_PSYSTRIKE: 'Psystrike',
    MEWTWOY_MOVE_2A_RECOVER: 'Recover',
    MEWTWOY_MOVE_2B_TELEPORT: 'Teleport',
    MEWTWOX_MOVE_1A_FUTURESIGHT: 'Future Sight',
    MEWTWOX_MOVE_1B_PSYSTRIKE: 'Psystrike',
    MEWTWOX_MOVE_2A_RECOVER: 'Recover',
    MEWTWOX_MOVE_2B_TELEPORT: 'Teleport',
    BLAZIKEN_MOVE_1: 'Move 1',
    BLAZIKEN_MOVE_2: 'Move 2',
    MIMIKYU_MOVE_1A_PLAYROUGH: 'Play Rough',
    MIMIKYU_MOVE_1B_SHADOWCLAW: 'Shadow Claw',
    MIMIKYU_MOVE_2A_SHADOWSNEAK: 'Shadow Sneak',
    MIMIKYU_MOVE_2B_TRICKROOM: 'Trick Room',
    MEOWSCARADA_MOVE_1A_FLOWERTRICK: 'Flower Trick',
    MEOWSCARADA_MOVE_1B_NIGHTSLASH: 'Night Slash',
    MEOWSCARADA_MOVE_2A_DOUBLETEAM: 'Double Team',
    MEOWSCARADA_MOVE_2B_TRAILBLAZE: 'Trailblaze',
    METAGROSS_MOVE_1A_METEORMASH: 'Meteor Mash',
    METAGROSS_MOVE_1B_GYROBALL: 'Gyro Ball',
    METAGROSS_MOVE_2A_ZENHEADBUTT: 'Zen Headbutt',
    METAGROSS_MOVE_2B_MAGNETRISE: 'Magnet Rise',
    GYARADOS_MOVE_1A_WATERFALL: 'Waterfall',
    GYARADOS_MOVE_1B_BOUNCE: 'Bounce',
    GYARADOS_MOVE_2A_DRAGONBREATH: 'Dragon Breath',
    GYARADOS_MOVE_2B_AQUATAIL: 'Aqua Tail',
    MIRAIDON_MOVE_1A_CHARGEBEAM: 'Charge Beam',
    MIRAIDON_MOVE_1B_ELECTRODRIFT: 'Electro Drift',
    MIRAIDON_MOVE_2A_THUNDER: 'Thunder',
    MIRAIDON_MOVE_2B_PARABOLICCHARGE: 'Parabolic Charge',
    FALINKS_MOVE_1A_MEGAHORN: 'Megahorn',
    FALINKS_MOVE_1B_IRONHEAD: 'Iron Head',
    FALINKS_MOVE_2A_NORETREAT: 'No Retreat',
    FALINKS_MOVE_2B_BEATUP: 'Beat Up',
    CERULEDGE_MOVE_1A_BITTERBLADE: 'Bitter Blade',
    CERULEDGE_MOVE_2A_PSYCHOCUT: 'Psycho Cut',
    CERULEDGE_MOVE_1B_PHANTOMFORCE: 'Phantom Force',
    CERULEDGE_MOVE_2B_FLAMECHARGE: 'Flame Charge',
    HOOH_MOVE_1A_FLAMETHROWER: 'Flamethrower',
    HOOH_MOVE_1B_SKYATTACK: 'Sky Attack',
    HOOH_MOVE_2A_FLY: 'Fly',
    HOOH_MOVE_2B_FIRESPIN: 'Fire Spin',
    ARMAROUGE_MOVE_1A_FIRESPIN: 'Fire Spin',
    ARMAROUGE_MOVE_1B_ARMORCANNON: 'Armor Cannon',
    ARMAROUGE_MOVE_2A_FLAMECHARGE: 'Flame Charge',
    ARMAROUGE_MOVE_2B_PSYSHOCK: 'Psyshock',
    DARKRAI_MOVE_1A_DARKVOID: 'Dark Void',
    DARKRAI_MOVE_1B_SHADOWCLAW: 'Shadow Claw',
    DARKRAI_MOVE_2A_NASTYPLOT: 'Nasty Plot',
    DARKRAI_MOVE_2A_DARKPULSE: 'Dark Pulse',
    PSYDUCK_MOVE_1A_SURF: 'Surf',
    PSYDUCK_MOVE_1B_BUBBLEBEAM: 'Bubble Beam',
    PSYDUCK_MOVE_2A_DISABLE: 'Disable',
    PSYDUCK_MOVE_2B_PSYCHIC: 'Psychic',
    TINKATON_MOVE_1A_ICEHAMMER: 'Ice Hammer',
    TINKATON_MOVE_1B_THIEF: 'Thief',
    TINKATON_MOVE_2A_GIGATONHAMMER: 'Gigaton Hammer',
    TINKATON_MOVE_2B_SMACKDOWN: 'Smack Down',
    GALARIANRAPIDASH_MOVE_1A_DAZZLINGGLEAM: 'Dazzling Gleam',
    GALARIANRAPIDASH_MOVE_1B_FAIRYWIND: 'Fairy Wind',
    GALARIANRAPIDASH_MOVE_2A_AGILITY: 'Agility',
    GALARIANRAPIDASH_MOVE_2B_SMARTSTRIKE: 'Smart Strike',
    SUICUNE_MOVE_1A_WHIRLPOOL: 'Whirlpool',
    SUICUNE_MOVE_1B_SURF: 'Surf',
    SUICUNE_MOVE_2A_ICEBEAM: 'Ice Beam',
    SUICUNE_MOVE_2B_ICYWIND: 'Icy Wind',
}

export const CLASS_CONSTANTS = {
    // Roles
    ATTACKER: 'Attacker',
    DEFENDER: 'Defender',
    ALL_ROUNDER: 'All_Rounder',
    SPEEDSTER: 'Speedster',
    SUPPORTER: 'Supporter',
}

export const ATTRIBUTE_CONSTANTS = {
    //// Attributes
    //// Split into good and bad attributes. Try to mimic the good attributes of known comps and minimize the bad attributes or cancel out the bad attributes.
    // General Attributes
    GOOD_LANE: 'Good Laner',
    GOOD_JUNGLER: 'Good Jungler',
    STRONG_EARLY: 'Strong Early Game',
    STRONG_MIDDLE: 'Strong Mid Game',
    STRONG_LATE: 'Strong Late Game',
    MEELE: 'Melee',
    LOW_RANGE: 'Low Range',
    MID_RANGE: 'Mid Range',
    LONG_RANGE: 'Long Range',
    SUSCEPTIBLE_TO_INVADES: 'Susceptible To Invades', // Things like Kubfu that struggle to do their first clear quickly
    SPLITS_JUNGLE: 'Splits Jungle', // Things like eldegoss that like to take red buff and help speed up the jungler's first clear
    FULL_SPLIT_JUNGLE: 'Full Split Jungler', // Things like two eevees that can each take half of the jungle or really anything that spikes at level 4.

    HIGH_MOBILITY: 'Very Mobile',
    ADC: 'ADC',
    GOOD_SCORING: 'Good Scoring',
    GROUP_HEALING: 'Group Healing',
    GOOD_SUSTAIN: 'Good Sustain',
    SINGLE_TARGET_HEALING: 'Single Target Healing',
    HEAVY_SHIELDS: 'Heavy Shields',
    TRUE_DAMAGE: 'True Damage',
    GIVES_UNSTOPPABLE: 'Gives Unstoppable',
    HAS_UNSTOPPABLE: 'Has Unstoppable',
    GROUP_CC: 'Group CC',
    SINGLE_CC: 'Single Target CC',
    SNOWBALL: 'Snowballs',
    SOLO_CARRY: 'Solo Carry',
    BURST_DAMAGE: 'Burst Damage',
    TEAMFIGHTER: 'Good Teamfight',
    GOOD_1V1: 'Good Duelist',
    FINDS_PICKS: 'Forces Picks',
    GOOD_BACKCAP: 'Good Backcapper',
    FAST_RIP: 'Fast Rip',
}   

function localName() {
    if (window.location.hostname === 'localhost') {
        return 'http://localhost:3001';
    }
    return '';
}

export const constants = {
    ...NAME_CONSTANTS,
    ...MOVE_CONSTANTS,
    ...CLASS_CONSTANTS,
    ...ATTRIBUTE_CONSTANTS,
    WEBSITE_URL: localName()
};