export const routes = {
    GET_ALL_DRAFT_INFO: '/api/GETallDraftInfo',
    GET_ALL_ATTRIBUTES: '/api/GETallCharacterAttributes',
    GET_SINGLE_ATTRIBUTES: '/api/GETsingleCharacterAttributes',
    PUT_CHARACTER_ATTRIBUTES: '/api/PUTCharacterAttributes',
    GET_RUN_A_STAR_ALGORITHM: '/api/GETrunAStarAlgorithm',
    GET_ALL_COMPS: '/api/GETallComps',
    GET_ALL_EVENTS: '/api/GETallEvents',
    GET_ALL_TEAMS: '/api/GETallTeams',
    GET_ALL_PLAYERS: '/api/GETallPlayers',
    GET_ALL_CHARACTERS_AND_MOVES: '/api/GETallCharactersAndMoves',
    POST_EVENT: '/api/POSTevent',
    POST_TEAM: '/api/POSTteam',
    POST_PLAYER: '/api/POSTplayer',
    POST_SET: '/api/POSTset',
    POST_ROOMS: '/api/POSTrooms',
    GET_ROOMS: '/api/GETrooms',
    GET_ROOM_INFO: '/api/GETrooms/',
    GET_CHARACTER_STATS: '/api/GETcharacterStats',
    GET_RATE_COMP: '/api/GETrateComp',
    GET_TIER_LIST: '/api/GETtierList',
    POST_TIER_LIST_ENTRY: '/api/POSTtierListEntry',
    GET_IS_VERIFIED_USER: '/api/GETisVerifiedUser',
    GET_IS_ADMIN: '/api/GETisAdmin'
};