// All the basic naming conventions of things. Keeping as const cause naming conventions may change. For example: Alolan Ninetales could be A-Ninetales, Alolan_Ninetales, etc
// Also just makes it easier to prevent typos and just change stuff as needed.

// Pokemon
const constants = {
    CINDERACE_NAME: 'Cinderace',
    GARCHOMP_NAME: 'Garchomp',
    GENGAR_NAME: 'Gengar',
    CRAMORANT_NAME: 'Cramorant', 
    ALOLANNINETALES_NAME: 'Alolan-Ninetales',
    WIGGLYTUFF_NAME: 'Wigglytuff',
    MACHAMP_NAME: 'Machamp', 
    ABSOL_NAME: 'Absol',
    SLOWBRO_NAME: 'Slowbro',
    MRMIME_NAME: 'Mr-Mime', 
    VENUSAUR_NAME: 'Venusaur', 
    LUCARIO_NAME: 'Lucario',
    TALONFLAME_NAME: 'Talonflame',
    ELDEGOSS_NAME: 'Eldegoss', 
    GRENINJA_NAME: 'Greninja', 
    CRUSTLE_NAME: 'Crustle',
    SNORLAX_NAME: 'Snorlax', 
    CHARIZARD_NAME: 'Charizard', 
    PIKACHU_NAME: 'Pikachu', 
    ZERAORA_NAME: 'Zeraora', 
    GARDEVOIR_NAME: 'Gardevoir',
    BLISSEY_NAME: 'Blissey', 
    BLASTOISE_NAME: 'Blastoise', 
    MAMOSWINE_NAME: 'Mamoswine', 
    SYLVEON_NAME: 'Sylveon', 
    GREEDENT_NAME: 'Greedent', 
    DECIDUEYE_NAME: 'Decidueye', 
    TSAREENA_NAME: 'Tsareena', 
    DRAGONITE_NAME: 'Dragonite', 
    TREVENANT_NAME: 'Trevenant',
    AEGISLASH_NAME: 'Aegislash', 
    HOOPA_NAME: 'Hoopa', 
    DURALUDON_NAME: 'Duraludon',
    AZUMARILL_NAME: 'Azumarill',
    ESPEON_NAME: 'Espeon',
    DELPHOX_NAME: 'Delphox', 
    GLACEON_NAME: 'Glaceon', 
    BUZZWOLE_NAME: 'Buzzwole', 
    TYRANITAR_NAME: 'Tyranitar',
    MEW_NAME: 'Mew',
    DODRIO_NAME: 'Dodrio',
    SCIZOR_NAME: 'Scizor',
    SCYTHER_NAME: 'Scyther',
    CLEFABLE_NAME: 'Clefable',
    ZOROARK_NAME: 'Zoroark',
    SABLEYE_NAME: 'Sableye',
    URSHIFUSS_NAME: 'Urshifu-SS', // Single-Strike (Red)
    URSHIFURS_NAME: 'Urshifu-RS', // Rapid-Strike (Blue)
    DRAGAPULT_NAME: 'Dragapult',
    COMFEY_NAME: 'Comfey',
    ZACIAN_NAME: 'Zacian',
    GOODRA_NAME: 'Goodra',
    LAPRAS_NAME: 'Lapras',
    CHANDELURE_NAME: 'Chandelure',
    UMBREON_NAME: 'Umbreon',
    LEAFEON_NAME: 'Leafeon',
    INTELEON_NAME: 'Inteleon',
    MEWTWOY_NAME: 'Mewtwo-Y',
    MEWTWOX_NAME: 'Mewtwo-X',
    BLAZIKEN_NAME: 'Blaziken',
    MIMIKYU_NAME: 'Mimikyu',
    MEOWSCARADA_NAME: 'Meowscarada',
    METAGROSS_NAME: 'Metagross',
    GYARADOS_NAME: 'Gyarados',
    MIRAIDON_NAME: 'Miraidon',
    FALINKS_NAME: 'Falinks',
    CERULEDGE_NAME: 'Ceruledge',
    HOOH_NAME: 'Ho-Oh',
    ARMAROUGE_NAME: 'Armarouge',
    DARKRAI_NAME: 'Darkrai',
    PSYDUCK_NAME: 'Psyduck',
    TINKATON_NAME: 'Tinkaton',
    GALARIANRAPIDASH_NAME: 'Galarian-Rapidash',

    // Moves
    // CINDERACE_MOVE_1A_PYROBALL: `${CINDERACE_NAME} - Pyro Ball`,
    // CINDERACE_MOVE_1B_BLAZEKICK: `${CINDERACE_NAME} - Blaze Kick`,
    // CINDERACE_MOVE_2A_LOWSWEEP: `${CINDERACE_NAME} - Low Sweep`,
    // CINDERACE_MOVE_2B_FEINT: `${CINDERACE_NAME} - Feint`,
    // GARCHOMP_MOVE_1A_DIG: `${GARCHOMP_NAME} - Dig`,
    // GARCHOMP_MOVE_1B_DRAGONRUSH: `${GARCHOMP_NAME} - Dragon Rush`,
    // GARCHOMP_MOVE_2A_EARTHQUAKE: `${GARCHOMP_NAME} - Earthquake`,
    // GARCHOMP_MOVE_2B_DRAGONCLAW: `${GARCHOMP_NAME} - Dragon Claw`,
    // GENGAR_MOVE_1A_SHADOWBALL: `${GENGAR_NAME} - Shadow Ball`,
    // GENGAR_MOVE_1B_SLUDGEBOMB: `${GENGAR_NAME} - Sludge Bomb`,
    // GENGAR_MOVE_2A_DREAMEATER: `${GENGAR_NAME} - Dream Eater`,
    // GENGAR_MOVE_2B_HEX: `${GENGAR_NAME} - Hex`,
    // CRAMORANT_MOVE_1A_SURF: `${CRAMORANT_NAME} - Surf`,
    // CRAMORANT_MOVE_1B_DIVE: `${CRAMORANT_NAME} - Dive`,
    // CRAMORANT_MOVE_2A_HURRICANE: `${CRAMORANT_NAME} - Hurricane`,
    // CRAMORANT_MOVE_2B_AIRSLASH: `${CRAMORANT_NAME} - Air Slash`,
    // ALOLANNINETALES_MOVE_1A_AVALANCHE: `${ALOLANNINETALES_NAME} - Avalanche`,
    // ALOLANNINETALES_MOVE_1B_DAZZLINGGLEAM: `${ALOLANNINETALES_NAME} - Dazzling Gleam`,
    // ALOLANNINETALES_MOVE_2A_BLIZZARD: `${ALOLANNINETALES_NAME} - Blizzard`,
    // ALOLANNINETALES_MOVE_2B_AURORAVEIL: `${ALOLANNINETALES_NAME} - Aurora Veil`,
    // WIGGLYTUFF_MOVE_1A_DOUBLESLAP: `${WIGGLYTUFF_NAME} - Double Slap`,
    // WIGGLYTUFF_MOVE_1B_DAZZLINGGLEAM: `${WIGGLYTUFF_NAME} - Dazzling Gleam`,
    // WIGGLYTUFF_MOVE_2A_ROLLOUT: `${WIGGLYTUFF_NAME} - Rollout`,
    // WIGGLYTUFF_MOVE_2B_SING: `${WIGGLYTUFF_NAME} - Sing`,
    // MACHAMP_MOVE_1A_CLOSECOMBAT: `${MACHAMP_NAME} - Close Combat`,
    // MACHAMP_MOVE_1B_CROSSCHOP: `${MACHAMP_NAME} - Cross Chop`,
    // MACHAMP_MOVE_2A_DYNAMICPUNCH: `${MACHAMP_NAME} - Dynamic Punch`,
    // MACHAMP_MOVE_2B_SUBMISSION: `${MACHAMP_NAME} - Submission`,
    // ABSOL_MOVE_1A_NIGHTSLASH: `${ABSOL_NAME} - Night Slash`,
    // ABSOL_MOVE_1B_PURSUIT: `${ABSOL_NAME} - Pursuit`,
    // ABSOL_MOVE_2A_PSYCHOCUT: `${ABSOL_NAME} - Psycho Cut`,
    // ABSOL_MOVE_2B_SUCKERPUNCH: `${ABSOL_NAME} - Sucker Punch`,
    // SLOWBRO_MOVE_1A_SCALD: `${SLOWBRO_NAME} - Scald`,
    // SLOWBRO_MOVE_1B_SURF: `${SLOWBRO_NAME} - Surf`,
    // SLOWBRO_MOVE_2A_AMNESIA: `${SLOWBRO_NAME} - Amnesia`,
    // SLOWBRO_MOVE_2B_TELEKINESIS: `${SLOWBRO_NAME} - Telekinesis`,
    // MRMIME_MOVE_1A_CONFUSION: `${MRMIME_NAME} - Confusion`,
    // MRMIME_MOVE_1B_PSYCHIC: `${MRMIME_NAME} - Psychic`,
    // MRMIME_MOVE_2A_BARRIER: `${MRMIME_NAME} - Barrier`,
    // MRMIME_MOVE_2B_POWERSWAP: `${MRMIME_NAME} - Power Swap`,
    // VENUSAUR_MOVE_1A_SLUDGEBOMB: `${VENUSAUR_NAME} - Sludge Bomb`,
    // VENUSAUR_MOVE_1B_GIGADRAIN: `${VENUSAUR_NAME} - Giga Drain`,
    // VENUSAUR_MOVE_2A_SOLARBEAM: `${VENUSAUR_NAME} - Solarbeam`,
    // VENUSAUR_MOVE_2B_PETALDANCE: `${VENUSAUR_NAME} - Petal Dance`,
    // LUCARIO_MOVE_1A_EXTREMESPEED: `${LUCARIO_NAME} - Extreme Speed`,
    // LUCARIO_MOVE_1B_POWERUPPUNCH: `${LUCARIO_NAME} - Power-Up Punch`,
    // LUCARIO_MOVE_2A_BONERUSH: `${LUCARIO_NAME} - Bone Rush`,
    // LUCARIO_MOVE_2B_CLOSECOMBAT: `${LUCARIO_NAME} - Close Combat`,
    // TALONFLAME_MOVE_1A_FLAMECHARGE: `${TALONFLAME_NAME} - Flame Charge`,
    // TALONFLAME_MOVE_1B_AERIALACE: `${TALONFLAME_NAME} - Aerial Ace`,
    // TALONFLAME_MOVE_2A_FLY: `${TALONFLAME_NAME} - Fly`,
    // TALONFLAME_MOVE_2B_BRAVEBIRD: `${TALONFLAME_NAME} - Brave Bird`,
    // ELDEGOSS_MOVE_1A_POLLENPUFF: `${ELDEGOSS_NAME} - Pollen Puff`,
    // ELDEGOSS_MOVE_1B_LEAFTORNADO: `${ELDEGOSS_NAME} - Leaf Tornado`,
    // ELDEGOSS_MOVE_2A_COTTONGUARD: `${ELDEGOSS_NAME} - Cotton Guard`,
    // ELDEGOSS_MOVE_2B_COTTONSPORE: `${ELDEGOSS_NAME} - Cotton Spore`,
    // GRENINJA_MOVE_1A_WATERSHURIKEN: `${GRENINJA_NAME} - Water Shuriken`,
    // GRENINJA_MOVE_1B_SURF: `${GRENINJA_NAME} - Surf`,
    // GRENINJA_MOVE_2A_DOUBLETEAM: `${GRENINJA_NAME} - Double Team`,
    // GRENINJA_MOVE_2B_SMOKESCREEN: `${GRENINJA_NAME} - Smokescreen`,
    // CRUSTLE_MOVE_1A_ROCKTOMB: `${CRUSTLE_NAME} - Rock Tomb`,
    // CRUSTLE_MOVE_1B_SHELLSMASH: `${CRUSTLE_NAME} - Shell Smash`,
    // CRUSTLE_MOVE_2A_STEALTHROCK: `${CRUSTLE_NAME} - Stealth Rock`,
    // CRUSTLE_MOVE_2B_XSCISSOR: `${CRUSTLE_NAME} - X-Scissor`,
    // SNORLAX_MOVE_1A_HEAVYSLAM: `${SNORLAX_NAME} - Heavy Slam`,
    // SNORLAX_MOVE_1B_FLAIL: `${SNORLAX_NAME} - Flail`,
    // SNORLAX_MOVE_2A_BLOCK: `${SNORLAX_NAME} - Block`,
    // SNORLAX_MOVE_2B_YAWN: `${SNORLAX_NAME} - Yawn`,
    // CHARIZARD_MOVE_1A_FLAMETHROWER: `${CHARIZARD_NAME} - Flamethrower`,
    // CHARIZARD_MOVE_1B_FIREPUNCH: `${CHARIZARD_NAME} - Fire Punch`,
    // CHARIZARD_MOVE_2A_FIREBLAST: `${CHARIZARD_NAME} - Fire Blast`,
    // CHARIZARD_MOVE_2B_FLAREBLITZ: `${CHARIZARD_NAME} - Flare Blitz`,
    // PIKACHU_MOVE_1A_ELECTROBALL: `${PIKACHU_NAME} - Electro Ball`,
    // PIKACHU_MOVE_1B_THUNDER: `${PIKACHU_NAME} - Thunder`,
    // PIKACHU_MOVE_2A_VOLTTACKLE: `${PIKACHU_NAME} - Volt Tackle`,
    // PIKACHU_MOVE_2B_THUNDERBOLT: `${PIKACHU_NAME} - Thunderbolt`,
    // ZERAORA_MOVE_1A_VOLTSWITCH: `${ZERAORA_NAME} - Volt Switch`,
    // ZERAORA_MOVE_1B_SPARK: `${ZERAORA_NAME} - Spark`,
    // ZERAORA_MOVE_2A_DISCHARGE: `${ZERAORA_NAME} - Discharge`,
    // ZERAORA_MOVE_2B_WILDCHARGE: `${ZERAORA_NAME} - Wild Charge`,
    // GARDEVOIR_MOVE_1A_PSYCHIC: `${GARDEVOIR_NAME} - Psychic`,
    // GARDEVOIR_MOVE_1B_MOONBLAST: `${GARDEVOIR_NAME} - Moonblast`,
    // GARDEVOIR_MOVE_2A_PSYSHOCK: `${GARDEVOIR_NAME} - Psyshock`,
    // GARDEVOIR_MOVE_2B_FUTURESIGHT: `${GARDEVOIR_NAME} - Future Sight`,
    // BLISSEY_MOVE_1A_EGGBOMB: `${BLISSEY_NAME} - Egg Bomb`,
    // BLISSEY_MOVE_1B_HELPINGHAND: `${BLISSEY_NAME} - Helping Hand`,
    // BLISSEY_MOVE_2A_SOFTBOILED: `${BLISSEY_NAME} - Soft-Boiled`,
    // BLISSEY_MOVE_2B_SAFEGUARD: `${BLISSEY_NAME} - Safeguard`,
    // BLASTOISE_MOVE_1A_HYDROPUMP: `${BLASTOISE_NAME} - Hydro Pump`,
    // BLASTOISE_MOVE_1B_WATERSPOUT: `${BLASTOISE_NAME} - Water Spout`,
    // BLASTOISE_MOVE_2A_SURF: `${BLASTOISE_NAME} - Surf`,
    // BLASTOISE_MOVE_2B_RAPIDSPIN: `${BLASTOISE_NAME} - Rapid Spin`,
    // MAMOSWINE_MOVE_1A_ICICLECRASH: `${MAMOSWINE_NAME} - Icicle Crash`,
    // MAMOSWINE_MOVE_1B_ICEFANG: `${MAMOSWINE_NAME} - Ice Fang`,
    // MAMOSWINE_MOVE_2A_HIGHHORSEPOWER: `${MAMOSWINE_NAME} - High Horsepower`,
    // MAMOSWINE_MOVE_2B_EARTHQUAKE: `${MAMOSWINE_NAME} - Earthquake`,
    // SYLVEON_MOVE_1A_MYSTICALFIRE: `${SYLVEON_NAME} - Mystical Fire`,
    // SYLVEON_MOVE_1B_HYPERVOICE: `${SYLVEON_NAME} - Hyper Voice`,
    // SYLVEON_MOVE_2A_DRAININGKISS: `${SYLVEON_NAME} - Draining Kiss`,
    // SYLVEON_MOVE_2B_CALMMIND: `${SYLVEON_NAME} - Calm Mind`,
    // GREEDENT_MOVE_1A_BULLETSEED: `${GREEDENT_NAME} - Bullet Seed`,
    // GREEDENT_MOVE_1B_BELCH: `${GREEDENT_NAME} - Belch`,
    // GREEDENT_MOVE_2A_STUFFCHEEKS: `${GREEDENT_NAME} - Stuff Cheeks`,
    // GREEDENT_MOVE_2B_COVET: `${GREEDENT_NAME} - Covet`,
    // DECIDUEYE_MOVE_1A_RAZORLEAF: `${DECIDUEYE_NAME} - Razor Leaf`,
    // DECIDUEYE_MOVE_1B_SPIRITSHACKLE: `${DECIDUEYE_NAME} - Spirit Shackle`,
    // DECIDUEYE_MOVE_2A_LEAFSTORM: `${DECIDUEYE_NAME} - Leaf Storm`,
    // DECIDUEYE_MOVE_2B_SHADOWSNEAK: `${DECIDUEYE_NAME} - Shadow Sneak`,
    // TSAREENA_MOVE_1A_TRIPLEAXEL: `${TSAREENA_NAME} - Triple Axel`,
    // TSAREENA_MOVE_1B_STOMP: `${TSAREENA_NAME} - Stomp`,
    // TSAREENA_MOVE_2A_TROPKICK: `${TSAREENA_NAME} - Trop Kick`,
    // TSAREENA_MOVE_2B_GRASSYGLIDE: `${TSAREENA_NAME} - Grassy Glide`,
    // DRAGONITE_MOVE_1A_DRAGONDANCE: `${DRAGONITE_NAME} - Dragon Dance`,
    // DRAGONITE_MOVE_1B_EXTREMESPEED: `${DRAGONITE_NAME} - Extreme Speed`,
    // DRAGONITE_MOVE_2A_HYPERBEAM: `${DRAGONITE_NAME} - Hyper Beam`,
    // DRAGONITE_MOVE_2B_OUTRAGE: `${DRAGONITE_NAME} - Outrage`,
    // TREVENANT_MOVE_1A_WOODHAMMER: `${TREVENANT_NAME} - Wood Hammer`,
    // TREVENANT_MOVE_1B_CURSE: `${TREVENANT_NAME} - Curse`,
    // TREVENANT_MOVE_2A_HORNLEECH: `${TREVENANT_NAME} - Horn Leech`,
    // TREVENANT_MOVE_2B_PAINSPLIT: `${TREVENANT_NAME} - Pain Split`,
    // AEGISLASH_MOVE_1A_SACREDSWORD: `${AEGISLASH_NAME} - Sacred Sword`,
    // AEGISLASH_MOVE_1B_SHADOWCLAW: `${AEGISLASH_NAME} - Shadow Claw`,
    // AEGISLASH_MOVE_2A_WIDEGUARD: `${AEGISLASH_NAME} - Wide Guard`,
    // AEGISLASH_MOVE_2B_IRONHEAD: `${AEGISLASH_NAME} - Iron Head`,
    // HOOPA_MOVE_1A_PHANTOMFORCE: `${HOOPA_NAME} - Phantom Force`,
    // HOOPA_MOVE_1B_SHADOWBALL: `${HOOPA_NAME} - Shadow Ball`,
    // HOOPA_MOVE_2A_HYPERSPACEHOLE: `${HOOPA_NAME} - Hyperspace Hole`,
    // HOOPA_MOVE_2B_TRICK: `${HOOPA_NAME} - Trick`,
    // DURALUDON_MOVE_1A_FLASHCANNON: `${DURALUDON_NAME} - Flash Cannon`,
    // DURALUDON_MOVE_1B_DRAGONPULSE: `${DURALUDON_NAME} - Dragon Pulse`,
    // DURALUDON_MOVE_2A_DRAGONTAIL: `${DURALUDON_NAME} - Dragon Tail`,
    // DURALUDON_MOVE_2B_STEALTHROCK: `${DURALUDON_NAME} - Stealth Rock`,
    // AZUMARILL_MOVE_1A_PLAYROUGH: `${AZUMARILL_NAME} - Play Rough`,
    // AZUMARILL_MOVE_1B_WATERPULSE: `${AZUMARILL_NAME} - Water Pulse`,
    // AZUMARILL_MOVE_2A_WHIRLPOOL: `${AZUMARILL_NAME} - Whirlpool`,
    // AZUMARILL_MOVE_2B_AQUATAIL: `${AZUMARILL_NAME} - Aquatail`,
    // ESPEON_MOVE_1A_PSYSHOCK: `${ESPEON_NAME} - Psyshock`,
    // ESPEON_MOVE_1B_STOREDPOWER: `${ESPEON_NAME} - Stored Power`,
    // ESPEON_MOVE_2A_PSYBEAM: `${ESPEON_NAME} - Psybeam`,
    // ESPEON_MOVE_2B_FUTURESIGHT: `${ESPEON_NAME} - Future Sight`,
    // DELPHOX_MOVE_1A_FIREBLAST: `${DELPHOX_NAME} - Fire Blast`,
    // DELPHOX_MOVE_1B_MYSTICALFIRE: `${DELPHOX_NAME} - Mystical Fire`,
    // DELPHOX_MOVE_2A_FIRESPIN: `${DELPHOX_NAME} - Fire Spin`,
    // DELPHOX_MOVE_2B_FLAMECHARGE: `${DELPHOX_NAME} - Flame Charge`,
    // GLACEON_MOVE_1A_ICICLESPEAR: `${GLACEON_NAME} - Icicle Spear`,
    // GLACEON_MOVE_1B_ICYWIND: `${GLACEON_NAME} - Icy Wind`,
    // GLACEON_MOVE_2A_ICESHARD: `${GLACEON_NAME} - Ice Shard`,
    // GLACEON_MOVE_2B_FREEZEDRY: `${GLACEON_NAME} - Freeze Dry`,
    // BUZZWOLE_MOVE_1A_LUNGE: `${BUZZWOLE_NAME} - Lunge`,
    // BUZZWOLE_MOVE_1B_SMACKDOWN: `${BUZZWOLE_NAME} - Smack Down`,
    // BUZZWOLE_MOVE_2A_LEECHLIFE: `${BUZZWOLE_NAME} - Leech Life`,
    // BUZZWOLE_MOVE_2B_SUPERPOWER: `${BUZZWOLE_NAME} - Superpower`,
    // TYRANITAR_MOVE_1A_DARKPULSE: `${TYRANITAR_NAME} - Dark Pulse`,
    // TYRANITAR_MOVE_1B_STONEEDGE: `${TYRANITAR_NAME} - Stone Edge`,
    // TYRANITAR_MOVE_2A_ANCIENTPOWER: `${TYRANITAR_NAME} - Ancient Power`,
    // TYRANITAR_MOVE_2B_SANDTOMB: `${TYRANITAR_NAME} - Sand Tomb`,
    // // Mew is a special case and will naturally be treated like she has all her moves
    // DODRIO_MOVE_1A_TRIATTACK: `${DODRIO_NAME} - Tri Attack`,
    // DODRIO_MOVE_1B_DRILLPECK: `${DODRIO_NAME} - Drill Peck`,
    // DODRIO_MOVE_2A_AGILITY: `${DODRIO_NAME} - Agility`,
    // DODRIO_MOVE_2B_JUMPKICK: `${DODRIO_NAME} - Jump Kick`,
    // // Scizor and Scyther are special cases with one 1 move
    // SCIZOR_MOVE_1A_BULLETPUNCH: `${SCIZOR_NAME} - Bullet Punch`,
    // SCIZOR_MOVE_2A_DOUBLEHIT: `${SCIZOR_NAME} - Double Hit`,
    // SCIZOR_MOVE_2B_SWORDSDANCE: `${SCIZOR_NAME} - Swords Dance`,
    // SCYTHER_MOVE_1A_DUALWINGBEAT: `${SCYTHER_NAME} - Dual Wingbeat`,
    // SCYTHER_MOVE_2A_DOUBLEHIT: `${SCYTHER_NAME} - Double Hit`,
    // SCYTHER_MOVE_2B_SWORDSDANCE: `${SCYTHER_NAME} - Swords Dance`,
    // CLEFABLE_MOVE_1A_MOONLIGHT: `${CLEFABLE_NAME} - Moonlight`,
    // CLEFABLE_MOVE_1B_DRAININGKISS: `${CLEFABLE_NAME} - Draining Kiss`,
    // CLEFABLE_MOVE_2A_GRAVITY: `${CLEFABLE_NAME} - Gravity`,
    // CLEFABLE_MOVE_2B_FOLLOWME: `${CLEFABLE_NAME} - Follow Me`,
    // ZOROARK_MOVE_1A_SHADOWCLAW: `${ZOROARK_NAME} - Shadow Claw`,
    // ZOROARK_MOVE_1B_CUT: `${ZOROARK_NAME} - Cut`,
    // ZOROARK_MOVE_2A_NIGHTSLASH: `${ZOROARK_NAME} - Night Slash`,
    // ZOROARK_MOVE_2B_FEINTATTACK: `${ZOROARK_NAME} - Feint Attack`,
    // SABLEYE_MOVE_1A_KNOCKOFF: `${SABLEYE_NAME} - Knock Off`,
    // SABLEYE_MOVE_1B_SHADOWSNEAK: `${SABLEYE_NAME} - Shadow Sneak`,
    // SABLEYE_MOVE_2A_FEINTATTACK: `${SABLEYE_NAME} - Feint Attack`,
    // SABLEYE_MOVE_2B_CONFUSERAY: `${SABLEYE_NAME} - Confuse Ray`,
    // // BOTH URSHIFUS ONLY HAVE ONE OPTION
    // URSHIFUSS_MOVE_1A_WICKEDBLOW: `${URSHIFUSS_NAME} - Wicked Blow`,
    // URSHIFUSS_MOVE_2A_THROATCHOP: `${URSHIFUSS_NAME} - Throat Chop`,
    // URSHIFURS_MOVE_1A_SURGINGSTRIKES: `${URSHIFURS_NAME} - Surging Strikes`,
    // URSHIFURS_MOVE_2A_LIQUIDATION: `${URSHIFURS_NAME} - Liquidation`,
    // DRAGAPULT_MOVE_1A_DRAGONBREATH: `${DRAGAPULT_NAME} - Dragon Breath`,
    // DRAGAPULT_MOVE_1B_SHADOWBALL: `${DRAGAPULT_NAME} - Shadow Ball`,
    // DRAGAPULT_MOVE_2A_DRAGONDANCE: `${DRAGAPULT_NAME} - Dragon Dance`,
    // DRAGAPULT_MOVE_2B_PHANTOMFORCE: `${DRAGAPULT_NAME} - Phantom Force`,
    // COMFEY_MOVE_1A_FLORALHEALING: `${COMFEY_NAME} - Floral Healing`,
    // COMFEY_MOVE_1B_SWEETKISS: `${COMFEY_NAME} - Sweet Kiss`,
    // COMFEY_MOVE_2A_MAGICALLEAF: `${COMFEY_NAME} - Magical Leaf`,
    // COMFEY_MOVE_2B_GRASSKNOT: `${COMFEY_NAME} - Grass Knot`,
    // ZACIAN_MOVE_1A_METALCLAW: `${ZACIAN_NAME} - Metal Claw`,
    // ZACIAN_MOVE_1B_SACREDSWORD: `${ZACIAN_NAME} - Sacred Sword`,
    // ZACIAN_MOVE_2A_AGILITY: `${ZACIAN_NAME} - Agility`,
    // ZACIAN_MOVE_2B_PLAYROUGH: `${ZACIAN_NAME} - Play Rough`,
    // GOODRA_MOVE_1A_MUDDYWATER: `${GOODRA_NAME} - Muddy Water`,
    // GOODRA_MOVE_1B_DRAGONPULSE: `${GOODRA_NAME} - Dragon Pulse`,
    // GOODRA_MOVE_2A_POWERWHIP: `${GOODRA_NAME} - Power Whip`,
    // GOODRA_MOVE_2B_ACIDSPRAY: `${GOODRA_NAME} - Acid Spray`,
    // LAPRAS_MOVE_1A_WATERPULSE: `${LAPRAS_NAME} - Water Pulse`,
    // LAPRAS_MOVE_1B_PERISHSONG: `${LAPRAS_NAME} - Perish Song`,
    // LAPRAS_MOVE_2A_BUBBLEBEAM: `${LAPRAS_NAME} - Bubble Beam`,
    // LAPRAS_MOVE_2B_ICEBEAM: `${LAPRAS_NAME} - Ice Beam`,
    // CHANDELURE_MOVE_1A_FLAMETHROWER: `${CHANDELURE_NAME} - Flamethrower`,
    // CHANDELURE_MOVE_1B_OVERHEAT: `${CHANDELURE_NAME} - Overheat`,
    // CHANDELURE_MOVE_2A_POLTERGEIST: `${CHANDELURE_NAME} - Poltergeist`,
    // CHANDELURE_MOVE_2B_IMPRISON: `${CHANDELURE_NAME} - Imprison`,
    // UMBREON_MOVE_1A_MEANLOOK: `${UMBREON_NAME} - Mean Look`,
    // UMBREON_MOVE_1B_FOULPLAY: `${UMBREON_NAME} - Foul Play`,
    // UMBREON_MOVE_2A_WISH: `${UMBREON_NAME} - Wish`,
    // UMBREON_MOVE_2B_SNARL: `${UMBREON_NAME} - Snarl`,
    // LEAFEON_MOVE_1A_RAZORLEAF: `${LEAFEON_NAME} - Razor Leaf`,
    // LEAFEON_MOVE_1B_SOLARBLADE: `${LEAFEON_NAME} - Solar Blade`,
    // LEAFEON_MOVE_2A_AERIALACE: `${LEAFEON_NAME} - Aerial Ace`,
    // LEAFEON_MOVE_2B_LEAFBLADE: `${LEAFEON_NAME} - Leaf Blade`,
    // INTELEON_MOVE_1A_FELLSTINGER: `${INTELEON_NAME} - Fell Stinger`,
    // INTELEON_MOVE_1B_ACROBATICS: `${INTELEON_NAME} - Acrobatics`,
    // INTELEON_MOVE_2A_SNIPESHOT: `${INTELEON_NAME} - Snipe Shot`,
    // INTELEON_MOVE_2B_LIQUIDATION: `${INTELEON_NAME} - Liquidation`,
    // MEWTWOY_MOVE_1A_FUTURESIGHT: `${MEWTWOY_NAME} - Future Sight`,
    // MEWTWOY_MOVE_1B_PSYSTRIKE: `${MEWTWOY_NAME} - Psystrike`,
    // MEWTWOY_MOVE_2A_RECOVER: `${MEWTWOY_NAME} - Recover`,
    // MEWTWOY_MOVE_2B_TELEPORT: `${MEWTWOY_NAME} - Teleport`,
    // MEWTWOX_MOVE_1A_FUTURESIGHT: `${MEWTWOX_NAME} - Future Sight`,
    // MEWTWOX_MOVE_1B_PSYSTRIKE: `${MEWTWOX_NAME} - Psystrike`,
    // MEWTWOX_MOVE_2A_RECOVER: `${MEWTWOX_NAME} - Recover`,
    // MEWTWOX_MOVE_2B_TELEPORT: `${MEWTWOX_NAME} - Teleport`,
    // // Blaziken will be treated like Mew, like he has all his moves
    // MIMIKYU_MOVE_1A_PLAYROUGH: `${MIMIKYU_NAME} - Play Rought`,
    // MIMIKYU_MOVE_1B_SHADOWCLAW: `${MIMIKYU_NAME} - Shadow Claw`,
    // MIMIKYU_MOVE_2A_SHADOWSNEAK: `${MIMIKYU_NAME} - Shadow Sneak`,
    // MIMIKYU_MOVE_2B_TRICKROOM: `${MIMIKYU_NAME} - Trick Room`,
    // MEOWSCARADA_MOVE_1A_FLOWERTRICK: `${MEOWSCARADA_NAME} - Flower Trick`,
    // MEOWSCARADA_MOVE_1B_NIGHTSLASH: `${MEOWSCARADA_NAME} - Night Slash`,
    // MEOWSCARADA_MOVE_2A_DOUBLETEAM: `${MEOWSCARADA_NAME} - Double Team`,
    // MEOWSCARADA_MOVE_2B_TRAILBLAZE: `${MEOWSCARADA_NAME} - Trailblaze`,
    // METAGROSS_MOVE_1A_METEORMASH: `${METAGROSS_NAME} - Meteor Mash`,
    // METAGROSS_MOVE_1B_GYROBALL: `${METAGROSS_NAME} - Gyro Ball`,
    // METAGROSS_MOVE_2A_ZENHEADBUTT: `${METAGROSS_NAME} - Zen Headbutt`,
    // METAGROSS_MOVE_2B_MAGNETRISE: `${METAGROSS_NAME} - Magnet Rise`,
    // GYARADOS_MOVE_1A_DRAGONBREATH: `${GYARADOS_NAME} - Dragon Breath`,
    // GYARADOS_MOVE_1B_AQUATAIL: `${GYARADOS_NAME} - Aqua Tail`,
    // GYARADOS_MOVE_2A_WATERFALL: `${GYARADOS_NAME} - Waterfall`,
    // GYARADOS_MOVE_2B_BOUNCE: `${GYARADOS_NAME} - Bounce`,
    // MIRAIDON_MOVE_1A_CHARGEBEAM: `${MIRAIDON_NAME} - Charge Beam`,
    // MIRAIDON_MOVE_1B_ELECTRODRIFT: `${MIRAIDON_NAME} - Electro Drift`,
    // MIRAIDON_MOVE_2A_THUNDER: `${MIRAIDON_NAME} - Thunder`,
    // MIRAIDON_MOVE_2B_PARABOLICCHARGE: `${MIRAIDON_NAME} - Parabolic Charge`,
    // FALINKS_MOVE_1A_MEGAHORN: `${FALINKS_NAME} - Megahorn`,
    // FALINKS_MOVE_1B_IRONHEAD: `${FALINKS_NAME} - Iron Head`,
    // FALINKS_MOVE_2A_NORETREAT: `${FALINKS_NAME} - No Retreat`,
    // FALINKS_MOVE_2B_BEATUP: `${FALINKS_NAME} - Beat Up`,
    // CERULEDGE_MOVE_1A_BITTERBLADE: `${CERULEDGE_NAME} - Bitter Blade`,
    // CERULEDGE_MOVE_2A_PSYCHOCUT: `${CERULEDGE_NAME} - Psycho Cut`,
    // CERULEDGE_MOVE_1B_PHANTOMFORCE: `${CERULEDGE_NAME} - Phantom Force`,
    // CERULEDGE_MOVE_2B_FLAMECHARGE: `${CERULEDGE_NAME} - Flame Charge`,
    // HOOH_MOVE_1A_FLY: `${HOOH_NAME} - Fly`,
    // HOOH_MOVE_1B_FIRESPIN: `${HOOH_NAME} - Fire Spine`,
    // HOOH_MOVE_2A_FLAMETHROWER: `${HOOH_NAME} - Flamethrower`,
    // HOOH_MOVE_2B_SKYATTACK: `${HOOH_NAME} - Sky Attack`,
    // ARMAROUGE_MOVE_1A_FIRESPIN: `${ARMAROUGE_NAME} - Fire Spin`,
    // ARMAROUGE_MOVE_1B_ARMORCANNON: `${ARMAROUGE_NAME} - Armor Cannon`,
    // ARMAROUGE_MOVE_2A_FLAMECHARGE: `${ARMAROUGE_NAME} - Flame Charge`,
    // ARMAROUGE_MOVE_2B_PSYSHOCK: `${ARMAROUGE_NAME} - Psyshock`,

    // Roles
    ATTACKER: 'Attacker',
    DEFENDER: 'Defender',
    ALL_ROUNDER: 'All-Rounder',
    SPEEDSTER: 'Speedster',
    SUPPORTER: 'Supporter',

    //// Attributes
    //// Split into good and bad attributes. Try to mimic the good attributes of known comps and minimize the bad attributes or cancel out the bad attributes.
    // Character-Only Attributes
    CAN_LANE: 'Can Be A Laner',
    CAN_JUNGLE: 'Can Be A Jungler',
    STRONG_EARLY: 'Strong Early Game', // This should change to or maybe be supplemented by what levels they spike
    STRONG_MIDDLE: 'Strong Mid Game',
    STRONG_LATE: 'Strong Late Game',
    MELEE: 'Melee',
    LOW_RANGE: 'Low Range',
    MID_RANGE: 'Mid Range',
    LONG_RANGE: 'Long Range',
    HIGH_MOBILITY: 'Very Mobile',
    MEDIUM_MOBILITY: 'Somewhat Mobile',
    GOOD_SCORING: 'Good Scoring',
    TRUE_DAMAGE: 'True Damage',
    SNOWBALL: 'Snowballs',

    // Jungle Attributes (Character-Only)
    SUSCEPTIBLE_TO_INVADES: 'Susceptible To Invades', // Things like Kubfu that struggle to do their first clear quickly
    SPLITS_JUNGLE: 'Splits Jungle', // Things like eldegoss that like to take red buff and help speed up the jungler's first clear
    FULL_SPLIT_JUNGLE: 'Full Split Jungler', // Things like two eevees that can each take half of the jungle or really anything that spikes at level 4.
    INVADES: 'Likes To Invade',

    // Sub-classes of characters (Put on Moveset. If by moveset it is specified on one set of moves EX: Venusaur Petal Dance = Bruiser while Solarbeam = artillery)
    ADC: 'ADC',
    BRUISER: 'Bruiser',
    BURST_MAGE: 'Burst Mage',
    CONTROL_MAGE: 'Control Mage',
    CLERIC: 'Cleric',
    LOCKDOWN: 'Lockdown', // As in it does a good job of locking down other opponents
    ENGAGE: 'Has Good Engage',
    ASSASSAIN: 'Assassain',
    TANK: 'Tank',
    DRAIN_MAGE: 'Drain Mage',
    ARTILLERY_MAGE: 'Artillery Mage',
    
    // Other Attributes
    PEEL: 'Has Good Peel',
    SELF_PEEL: 'Has Self Peel',
    ENGAGE: 'Has Good Engage',
    DISENGAGE: 'Has Good Disengage',
    POKE: 'Poke Damage',
    GOOD_SUSTAIN: 'Good Sustain',
    GROUP_HEALING: 'Group Healing',
    SINGLE_TARGET_HEALING: 'Single Target Healing',
    USES_SHIELDS: 'Uses Shields',
    GIVES_UNSTOPPABLE: 'Gives Unstoppable',
    HAS_UNSTOPPABLE: 'Has Unstoppable',
    BUFFS: 'Gives Buffs',
    DEBUFFS: 'Applies Debuffs',
    GROUP_CC: 'Group CC',
    SINGLE_CC: 'Single Target CC',
    SOLO_CARRY: 'Solo Carry',
    BURST_DAMAGE: 'Burst Damage',
    TEAMFIGHTER: 'Good Teamfight',
    GOOD_1V1: 'Good Duelist',
    FINDS_PICKS: 'Forces Picks',
    FAST_RIP: 'Fast Rip',
    GOOD_SECURE: 'Good Secure',
    SPACE_CONTROL: 'Controls Space',
    VISION: 'Grants Vision',
    BACKLINE_ACCESS: 'Kills Backline',
}

// Drawbacks:
// Needs support at all times (decid)
// Bad early
// Falls off
// Bad secure
// Squishy
// Bad teamfight
// Bad duelist
// Slow rip
// Only strong for brief windows

module.exports = constants;