-- public.playable_characters definition

-- Drop table

-- DROP TABLE public.playable_characters;

CREATE TABLE public.playable_characters (
	pokemon_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	pokemon_name text NOT NULL,
	pokemon_class text NOT NULL,
	pokedex_number int4 NOT NULL,
	release_date date NOT NULL,
	CONSTRAINT playable_characters_pkey PRIMARY KEY (pokemon_id)
);

-- public.pokemon_moves definition

-- Drop table

-- DROP TABLE public.pokemon_moves;

CREATE TABLE public.pokemon_moves (
	move_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	move_name text NOT NULL,
	pokemon_id int4 NOT NULL,
	move_position int2 NULL,
	CONSTRAINT pokemon_moves_pkey PRIMARY KEY (move_id)
);


-- public.pokemon_moves foreign keys

ALTER TABLE public.pokemon_moves ADD CONSTRAINT pokemon_moves_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id);

-- public.pokemon_draft_information definition

-- Drop table

-- DROP TABLE public.pokemon_draft_information;

CREATE TABLE public.pokemon_draft_information (
	pokemon_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	can_exp_share bool NOT NULL,
	can_top_carry bool NOT NULL,
	can_jungle_carry bool NOT NULL,
	can_bottom_carry bool NOT NULL,
	best_lane int2 NOT NULL, -- 1 = Top Carry, 2 = Top EXP Share, 3 = Jungle Carry, 4 = Bottom Carry, 5 = Bot EXP Share
	CONSTRAINT pokemon_draft_information_pkey PRIMARY KEY (pokemon_id)
);

-- Column comments

COMMENT ON COLUMN public.pokemon_draft_information.best_lane IS '1 = Top Carry, 2 = Top EXP Share, 3 = Jungle Carry, 4 = Bottom Carry, 5 = Bot EXP Share';


-- public.pokemon_draft_information foreign keys

ALTER TABLE public.pokemon_draft_information ADD CONSTRAINT pokemon_draft_information_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id);

-- public.pokemon_insights definition

-- Drop table

-- DROP TABLE public.pokemon_insights;

CREATE TABLE public.pokemon_insights (
	pokemon_id int8 NOT NULL,
	"text" text NULL,
	match_title text NULL,
	match_link text NULL,
	good_teammates _jsonb NULL, -- {pokemon: [pokemon_name], reason: [text]}
	CONSTRAINT pokemon_insights_pkey PRIMARY KEY (pokemon_id)
);

-- Column comments

COMMENT ON COLUMN public.pokemon_insights.good_teammates IS '{pokemon: [pokemon_name], reason: [text]}';


-- public.pokemon_insights foreign keys

ALTER TABLE public.pokemon_insights ADD CONSTRAINT pokemon_insights_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id);

-- public.pokemon_traits definition

-- Drop table

-- DROP TABLE public.pokemon_traits;

CREATE TABLE public.pokemon_traits (
	pokemon_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	mobility int2 NULL, -- 0 = No mobility (Venusaur), 1 = Movement buff (Raichu, Pikachu, Tinkaton), 2 = Short Dash on Long CD (able to go over small walls) (Latios, Ninetales), 3 = Long Dash on long CD or Short Dash on Short CD (Feraligatr, Machamp), 4 = Combo of Long Dash on long CD or Short Dash on Short CD or movement buffs (Leafeon / Absol), 5 = Multiple dashes and/or movement buffs (Zoroark / Talonflame)
	"range" int2 NULL, -- 1 = Pokemon must be in melee range to do significant damage, 2 = Pokemon can be short range away (Metagross Gyro Ball), 3 = Pokemon can be a decent distance away (A9 Blizzard / Raichu Electro Ball / Espeon Psyshock), 4 = Somewhat long range (Miraidon charge beam), 5 = Very long range (Inteleon Snipe Shot, Venusaur Solar Beam)
	bulk int2 NULL, -- 1 = Very squishy (Greninja), 2 = Can be OHKO'd but harder (Typhlosion/Sylveon/Absol), 3 = Some decent natural bulk or extra tools (Blaziken/Suicune/Psyduck), 4 = Takes several people to kill (Metagross/Scizor/Mewtwo X/Mamoswine), 5 = Survives against many people for long periods (Goodra/Crustle)
	damage int2 NULL -- 1 = Little to none (Blissey/Comfey/Umbreon), 2 = Small damage output (Hoopa, Mamoswine), 3 = Deals decent damage but isn't primary reason it's picked (Sylveon, Mewtwos), 4 = Good damage output (Tsareena, Metagross, Empoleon), 5 = Pumping damage (Mega Lucario, Latios, Cinderace),
	damage_consistency int2 NULL, -- How many seconds it takes for the Pokemon to get another round of damage out. (ADC = 0)
	damage_area text NULL, -- SingleTarget, SmallAOE (Raichu Electro Ball), MediumAOE (A9 Blizzard, Heavy Slam Snorlax), LargeAOE (Venusaur Solarbeam, Miraidon Charge Beam)
	cc int2 NULL, -- 0 = No CC or minor slow, 1 = Small Interrupt (Cinderace Blaze Kick), 2 = Medium Single Stun / Short Group Stun (Muddy Water Vaporeon / Garchomp Rush+Claw), 3 = Long Single Stun / Medium Group Stun (Heavy Slam Snorlax / Volt Tackle Pikachu), 4 = Significant CC to consistently stun large groups or single players for long times, 5 = Multiple significant stuns
	play_style text NULL, -- Teamfight = Target frontline down first and protect your carries. Count on them to kill enemy team frontline faster than they kill yours, Dive = Go past frontline to kill backline first with burst, Split Map = Characters that excel in 2v2s or 1v1s more than 5v5s, Poke = Characters that are good at dealing damage from long range or supporting said characters, Brawl = Stick on enemies in a drawn out fight where you out sustain the enemy while killing them
	classification text NULL, -- Class type
	special_attributes _text NULL, -- Special Attributes of a Pokemon that are uncommon like Umbreon's ability to steal shields.
	level_strength _jsonb NULL,
	CONSTRAINT pokemon_traits_pkey PRIMARY KEY (pokemon_id)
);

-- Column comments

COMMENT ON COLUMN public.pokemon_traits.mobility IS '0 = No mobility (Venusaur), 1 = Movement buff (Raichu, Pikachu, Tinkaton), 2 = Short Dash on Long CD (able to go over small walls) (Latios, Ninetales), 3 = Long Dash on long CD or Short Dash on Short CD (Feraligatr, Machamp), 4 = Combo of Long Dash on long CD or Short Dash on Short CD or movement buffs (Leafeon / Absol), 5 = Multiple dashes and/or movement buffs (Zoroark / Talonflame)';
COMMENT ON COLUMN public.pokemon_traits."range" IS '1 = Pokemon must be in melee range to do significant damage, 2 = Pokemon can be short range away (Metagross Gyro Ball), 3 = Pokemon can be a decent distance away (A9 Blizzard / Raichu Electro Ball / Espeon Psyshock), 4 = Somewhat long range (Miraidon charge beam), 5 = Very long range (Inteleon Snipe Shot, Venusaur Solar Beam)';
COMMENT ON COLUMN public.pokemon_traits.bulk IS '1 = Very squishy (Greninja), 2 = Can be OHKO''d but harder (Typhlosion/Sylveon/Absol), 3 = Some decent natural bulk or extra tools (Blaziken/Suicune/Psyduck), 4 = Takes several people to kill (Metagross/Scizor/Mewtwo X/Mamoswine), 5 = Survives against many people for long periods (Goodra/Crustle)';
COMMENT ON COLUMN public.pokemon_traits.damage IS '1 = Little to none (Blissey/Comfey/Umbreon), 2 = Small damage output (Hoopa, Mamoswine), 3 = Deals decent damage but isn''t primary reason it''s picked (Sylveon, Mewtwos), 4 = Good damage output (Tsareena, Metagross, Empoleon), 5 = Pumping damage (Mega Lucario, Latios, Cinderace)';
COMMENT ON COLUMN public.pokemon_traits.damage_consistency IS 'How many seconds it takes for the Pokemon to get another round of damage out. (ADC = 0)';
COMMENT ON COLUMN public.pokemon_traits.damage_area IS 'SingleTarget, SmallAOE (Raichu Electro Ball), MediumAOE (A9 Blizzard, Heavy Slam Snorlax), LargeAOE (Venusaur Solarbeam, Miraidon Charge Beam)';
COMMENT ON COLUMN public.pokemon_traits.cc IS '0 = No CC or minor slow, 1 = Small Interrupt (Cinderace Blaze Kick), 2 = Medium Single Stun / Short Group Stun (Muddy Water Vaporeon / Garchomp Rush+Claw), 3 = Long Single Stun / Medium Group Stun (Heavy Slam Snorlax / Volt Tackle Pikachu), 4 = Significant CC to consistently stun large groups or single players for long times, 5 = Multiple significant stuns';
COMMENT ON COLUMN public.pokemon_traits.play_style IS 'Teamfight = Target frontline down first and protect your carries. Count on them to kill enemy team frontline faster than they kill yours, Dive = Go past frontline to kill backline first with burst, Split Map = Characters that excel in 2v2s or 1v1s more than 5v5s, Poke = Characters that are good at dealing damage from long range or supporting said characters, Brawl = Stick on enemies in a drawn out fight where you out sustain the enemy while killing them';
COMMENT ON COLUMN public.pokemon_traits.classification IS 'Class type';
COMMENT ON COLUMN public.pokemon_traits.special_attributes IS 'Special Attributes of a Pokemon that are uncommon like Umbreon''s ability to steal shields.';


-- public.pokemon_traits foreign keys

ALTER TABLE public.pokemon_traits ADD CONSTRAINT pokemon_traits_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id);

-- public.tier_list definition

-- Drop table

-- DROP TABLE public.tier_list;

CREATE TABLE public.tier_list (
	tier_name text NOT NULL,
	pokemon_id int4 NOT NULL,
	CONSTRAINT tier_list_pkey PRIMARY KEY (pokemon_id)
);


-- public.tier_list foreign keys

ALTER TABLE public.tier_list ADD CONSTRAINT tier_list_pokemon_id_fkey FOREIGN KEY (pokemon_id) REFERENCES public.playable_characters(pokemon_id);

-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	user_google_id text NOT NULL,
	user_name text NOT NULL,
	user_email text NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (user_google_id)
);

-- public.verified_users definition

-- Drop table

-- DROP TABLE public.verified_users;

CREATE TABLE public.verified_users (
	user_google_id text NOT NULL,
	CONSTRAINT verified_users_pkey PRIMARY KEY (user_google_id)
);


-- public.verified_users foreign keys

ALTER TABLE public.verified_users ADD CONSTRAINT verified_users_user_google_id_fkey FOREIGN KEY (user_google_id) REFERENCES public.users(user_google_id);